package ru.cherryngine.lib.minecraft.protocol.packets.registry

import ru.cherryngine.lib.minecraft.protocol.packets.ProtocolState
import ru.cherryngine.lib.minecraft.protocol.packets.common.*
import ru.cherryngine.lib.minecraft.protocol.packets.configurations.*
import ru.cherryngine.lib.minecraft.protocol.packets.login.*
import ru.cherryngine.lib.minecraft.protocol.packets.play.clientbound.*
import ru.cherryngine.lib.minecraft.protocol.packets.status.ClientboundStatusResponsePacket

class ClientboundPacketRegistry : AbstractPacketRegistry() {
    init {
        register(ProtocolState.STATUS, ClientboundStatusResponsePacket::class, ClientboundStatusResponsePacket.STREAM_CODEC)
        register(ProtocolState.STATUS, ClientboundPongResponsePacket::class, ClientboundPongResponsePacket.STREAM_CODEC)

        register(ProtocolState.LOGIN, ClientboundLoginDisconnectPacket::class, ClientboundLoginDisconnectPacket.STREAM_CODEC)
        register(ProtocolState.LOGIN, ClientboundEncryptionRequestPacket::class, ClientboundEncryptionRequestPacket.STREAM_CODEC)
        register(ProtocolState.LOGIN, ClientboundLoginFinishedPacket::class, ClientboundLoginFinishedPacket.STREAM_CODEC)
        register(ProtocolState.LOGIN, ClientboundLoginCompressionPacket::class, ClientboundLoginCompressionPacket.STREAM_CODEC)
        register(ProtocolState.LOGIN, ClientboundLoginCustomQueryPacket::class, ClientboundLoginCustomQueryPacket.STREAM_CODEC)
        skip(ProtocolState.LOGIN, "Cookie Request")

        skip(ProtocolState.CONFIGURATION, "Cookie Request")
        register(ProtocolState.CONFIGURATION, ClientboundConfigurationPluginMessagePacket::class, ClientboundConfigurationPluginMessagePacket.STREAM_CODEC)
        register(ProtocolState.CONFIGURATION, ClientboundDisconnectPacket::class, ClientboundDisconnectPacket.STREAM_CODEC)
        register(ProtocolState.CONFIGURATION, ClientboundFinishConfigurationPacket::class, ClientboundFinishConfigurationPacket.STREAM_CODEC)
        register(ProtocolState.CONFIGURATION, ClientboundKeepAlivePacket::class, ClientboundKeepAlivePacket.STREAM_CODEC)
        register(ProtocolState.CONFIGURATION, ClientboundPingPacket::class, ClientboundPingPacket.STREAM_CODEC)
        skip(ProtocolState.CONFIGURATION, "Reset Chat")
        register(ProtocolState.CONFIGURATION, ClientboundRegistryDataPacket::class, ClientboundRegistryDataPacket.STREAM_CODEC)
        skip(ProtocolState.CONFIGURATION, "ClientboundConfigurationRemoveResourcePackPacket") // addConfiguration, ClientboundConfigurationRemoveResourcePackPacket::class, ClientboundConfigurationRemoveResourcePackPacket.streamCodec)
        skip(ProtocolState.CONFIGURATION, "ClientboundConfigurationAddResourcePackPacket") // addConfiguration, ClientboundConfigurationAddResourcePackPacket::class, ClientboundConfigurationAddResourcePackPacket.streamCodec)
        skip(ProtocolState.CONFIGURATION, "Cookie Store")
        skip(ProtocolState.CONFIGURATION, "Transfer Packet")
        register(ProtocolState.CONFIGURATION, ClientboundFeatureFlagsPacket::class, ClientboundFeatureFlagsPacket.STREAM_CODEC)
        register(ProtocolState.CONFIGURATION, ClientboundUpdateTagsPacket::class, ClientboundUpdateTagsPacket.STREAM_CODEC)
        register(ProtocolState.CONFIGURATION, ClientboundKnownPacksPacket::class, ClientboundKnownPacksPacket.STREAM_CODEC)
        skip(ProtocolState.CONFIGURATION, "Custom Reports")
        skip(ProtocolState.CONFIGURATION, "ClientboundConfigurationServerLinksPacket") // addConfiguration, ClientboundConfigurationServerLinksPacket::class, ClientboundConfigurationServerLinksPacket.streamCodec)
        register(ProtocolState.CONFIGURATION, ClientboundClearDialogPacket::class, ClientboundClearDialogPacket.STREAM_CODEC)
        skip(ProtocolState.CONFIGURATION, "show dialog")

        register(ProtocolState.PLAY, ClientboundBundleDelimiterPacket::class, ClientboundBundleDelimiterPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundAddEntityPacket::class, ClientboundAddEntityPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundAnimatePacket::class, ClientboundAnimatePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Statistics")
        register(ProtocolState.PLAY, ClientboundBlockChangedAckPacket::class, ClientboundBlockChangedAckPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Block break animation")
        skip(ProtocolState.PLAY, "Block entity data")
        register(ProtocolState.PLAY, ClientboundBlockEventPacket::class, ClientboundBlockEventPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Block change")
        register(ProtocolState.PLAY, ClientboundBossEventPacket::class, ClientboundBossEventPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundChangeDifficultyPacket::class, ClientboundChangeDifficultyPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Chunk batch finished")
        skip(ProtocolState.PLAY, "Chunk batch start")
        skip(ProtocolState.PLAY, "Chunk biomes")
        register(ProtocolState.PLAY, ClientboundClearTitlesPacket::class, ClientboundClearTitlesPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundCommandSuggestionsPacket::class, ClientboundCommandSuggestionsPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "ClientboundCommandsPacket") // addPlay, ClientboundCommandsPacket::class, ClientboundCommandsPacket.streamCodec)
        register(ProtocolState.PLAY, ClientboundContainerClosePacket::class, ClientboundContainerClosePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundContainerSetContentPacket::class, ClientboundContainerSetContentPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Container property")
        register(ProtocolState.PLAY, ClientboundContainerSetSlotPacket::class, ClientboundContainerSetSlotPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Cookie request")
        register(ProtocolState.PLAY, ClientboundCooldownPacket::class, ClientboundCooldownPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Chat suggestion")
        register(ProtocolState.PLAY, ClientboundPlayPluginMessagePacket::class, ClientboundPlayPluginMessagePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundDamageEventPacket::class, ClientboundDamageEventPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Debug sample")
        skip(ProtocolState.PLAY, "Delete chat")
        register(ProtocolState.PLAY, ClientboundDisconnectPacket::class, ClientboundDisconnectPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Disguised chat packet")
        register(ProtocolState.PLAY, ClientboundEntityEventPacket::class, ClientboundEntityEventPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundEntityPositionSyncPacket::class, ClientboundEntityPositionSyncPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Explosion")
        register(ProtocolState.PLAY, ClientboundForgetLevelChunkPacket::class, ClientboundForgetLevelChunkPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundGameEventPacket::class, ClientboundGameEventPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "open horse inventory")
        skip(ProtocolState.PLAY, "hit animation")
        register(ProtocolState.PLAY, ClientboundInitializeBorderPacket::class, ClientboundInitializeBorderPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundKeepAlivePacket::class, ClientboundKeepAlivePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundLevelChunkWithLightPacket::class, ClientboundLevelChunkWithLightPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundLevelEventPacket::class, ClientboundLevelEventPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "ClientboundSendParticlePacket") // addPlay, ClientboundSendParticlePacket::class, ClientboundSendParticlePacket.streamCodec)
        skip(ProtocolState.PLAY, "update light")
        register(ProtocolState.PLAY, ClientboundLoginPacket::class, ClientboundLoginPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "map data")
        skip(ProtocolState.PLAY, "trade list")
        register(ProtocolState.PLAY, ClientboundMoveEntityPosPacket::class, ClientboundMoveEntityPosPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundMoveEntityPosRotPacket::class, ClientboundMoveEntityPosRotPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "move minecart")
        register(ProtocolState.PLAY, ClientboundMoveEntityRotPacket::class, ClientboundMoveEntityRotPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundMoveVehiclePacket::class, ClientboundMoveVehiclePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "open book")
        register(ProtocolState.PLAY, ClientboundOpenScreenPacket::class, ClientboundOpenScreenPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "open signed book")
        register(ProtocolState.PLAY, ClientboundPingPacket::class, ClientboundPingPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundPongResponsePacket::class, ClientboundPongResponsePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "place ghost recipe")
        register(ProtocolState.PLAY, ClientboundPlayerAbilitiesPacket::class, ClientboundPlayerAbilitiesPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "player chat message")
        skip(ProtocolState.PLAY, "end combat")
        skip(ProtocolState.PLAY, "enter combat")
        skip(ProtocolState.PLAY, "death combat")
        register(ProtocolState.PLAY, ClientboundPlayerInfoRemovePacket::class, ClientboundPlayerInfoRemovePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "ClientboundPlayerInfoUpdatePacket") // addPlay, ClientboundPlayerInfoUpdatePacket::class, ClientboundPlayerInfoUpdatePacket.streamCodec)
        skip(ProtocolState.PLAY, "face player")
        register(ProtocolState.PLAY, ClientboundPlayerPositionPacket::class, ClientboundPlayerPositionPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "player rotation")
        skip(ProtocolState.PLAY, "recipe book add")
        skip(ProtocolState.PLAY, "recipe book remove")
        skip(ProtocolState.PLAY, "recipe book settings")
        register(ProtocolState.PLAY, ClientboundRemoveEntitiesPacket::class, ClientboundRemoveEntitiesPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundRemoveMobEffectPacket::class, ClientboundRemoveMobEffectPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundResetScorePacket::class, ClientboundResetScorePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundPlayRemoveResourcepackPacket::class, ClientboundPlayRemoveResourcepackPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "ClientboundPlayAddResourcepackPacket") // addPlay, ClientboundPlayAddResourcepackPacket::class, ClientboundPlayAddResourcepackPacket.streamCodec)
        register(ProtocolState.PLAY, ClientboundRespawnPacket::class, ClientboundRespawnPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundRotateHeadPacket::class, ClientboundRotateHeadPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "multi block change")
        register(ProtocolState.PLAY, ClientboundSelectAdvancementsTabPacket::class, ClientboundSelectAdvancementsTabPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "server data")
        skip(ProtocolState.PLAY, "actionbar")
        skip(ProtocolState.PLAY, "world border center")
        skip(ProtocolState.PLAY, "world border lerp size")
        skip(ProtocolState.PLAY, "world border size")
        skip(ProtocolState.PLAY, "world border warning delay")
        register(ProtocolState.PLAY, ClientboundSetBorderWarningDistancePacket::class, ClientboundSetBorderWarningDistancePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "camera")
        register(ProtocolState.PLAY, ClientboundSetChunkCacheCenterPacket::class, ClientboundSetChunkCacheCenterPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "view distance")
        register(ProtocolState.PLAY, ClientboundSetCursorItemPacket::class, ClientboundSetCursorItemPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "spawn position")
        register(ProtocolState.PLAY, ClientboundSetDisplayObjectivePacket::class, ClientboundSetDisplayObjectivePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetEntityDataPacket::class, ClientboundSetEntityDataPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "attach entity packet")
        register(ProtocolState.PLAY, ClientboundSetEntityMotionPacket::class, ClientboundSetEntityMotionPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "ClientboundSetEntityEquipmentPacket") // addPlay, ClientboundSetEntityEquipmentPacket::class, ClientboundSetEntityEquipmentPacket.streamCodec)
        register(ProtocolState.PLAY, ClientboundSetExperiencePacket::class, ClientboundSetExperiencePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetHealthPacket::class, ClientboundSetHealthPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetHeldSlotPacket::class, ClientboundSetHeldSlotPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetObjectivePacket::class, ClientboundSetObjectivePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetPassengersPacket::class, ClientboundSetPassengersPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetPlayerInventoryPacket::class, ClientboundSetPlayerInventoryPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "ClientboundTeamsPacket") // addPlay, ClientboundTeamsPacket::class, ClientboundTeamsPacket.streamCodec)
        register(ProtocolState.PLAY, ClientboundSetScorePacket::class, ClientboundSetScorePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "update simulation distance")
        register(ProtocolState.PLAY, ClientboundSetSubtitleTextPacket::class, ClientboundSetSubtitleTextPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetTimePacket::class, ClientboundSetTimePacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetTitleTextPacket::class, ClientboundSetTitleTextPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSetTitlesAnimationPacket::class, ClientboundSetTitlesAnimationPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSoundEntityPacket::class, ClientboundSoundEntityPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundSoundPacket::class, ClientboundSoundPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "start configuration")
        register(ProtocolState.PLAY, ClientboundStopSoundPacket::class, ClientboundStopSoundPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "cookie store")
        register(ProtocolState.PLAY, ClientboundSystemChatPacket::class, ClientboundSystemChatPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundTabListPacket::class, ClientboundTabListPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "nbt query response")
        register(ProtocolState.PLAY, ClientboundTakeItemEntityPacket::class, ClientboundTakeItemEntityPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundTeleportEntityPacket::class, ClientboundTeleportEntityPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "Test Instance block status")
        register(ProtocolState.PLAY, ClientboundTickingStatePacket::class, ClientboundTickingStatePacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "tick step")
        skip(ProtocolState.PLAY, "transfer packet")
        skip(ProtocolState.PLAY, "ClientboundUpdateAdvancementsPacket") // addPlay, ClientboundUpdateAdvancementsPacket::class, ClientboundUpdateAdvancementsPacket.streamCodec)
        skip(ProtocolState.PLAY, "ClientboundUpdateAttributesPacket") // addPlay, ClientboundUpdateAttributesPacket::class, ClientboundUpdateAttributesPacket.streamCodec)
        register(ProtocolState.PLAY, ClientboundUpdateMobEffectPacket::class, ClientboundUpdateMobEffectPacket.STREAM_CODEC)
        skip(ProtocolState.PLAY, "declare recipes")
        skip(ProtocolState.PLAY, "tags")
        skip(ProtocolState.PLAY, "projectile power")
        skip(ProtocolState.PLAY, "custom report details")
        skip(ProtocolState.PLAY, "server links")
        skip(ProtocolState.PLAY, "ClientboundTrackedWaypointPacket") // addPlay, ClientboundTrackedWaypointPacket::class, ClientboundTrackedWaypointPacket.streamCodec)
        register(ProtocolState.PLAY, ClientboundClearDialogPacket::class, ClientboundClearDialogPacket.STREAM_CODEC)
        register(ProtocolState.PLAY, ClientboundShowDialogPacket::class, ClientboundShowDialogPacket.STREAM_CODEC)
    }
}


