package ru.cherryngine.lib.minecraft.generator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.decodeFromStream
import kotlin.io.path.Path

object Main {
    @JvmStatic
    fun main(args: Array<String>) {
        generateDataDrivenRegistry(
            "Attributes",
            "AttributeRegistry",
            "Attribute",
            "attribute.json"
        )
        generateDataDrivenRegistry(
            "BannerPatterns",
            "BannerPatternRegistry",
            "BannerPattern",
            "banner_pattern.json"
        )
        generateDataDrivenRegistry(
            "Biomes",
            "BiomeRegistry",
            "Biome",
            "worldgen/biome.json"
        )
        generateDataDrivenRegistry(
            "Blocks",
            "BlockRegistry",
            "RegistryBlock",
            "block.json"
        )
        generateDataDrivenRegistry(
            "CatVariants",
            "CatVariantRegistry",
            "CatVariant",
            "cat_variant.json"
        )
        generateDataDrivenRegistry(
            "ChickenVariants",
            "ChickenVariantRegistry",
            "ChickenVariant",
            "chicken_variant.json"
        )
        generateDataDrivenRegistry(
            "CowVariants",
            "CowVariantRegistry",
            "CowVariant",
            "cow_variant.json"
        )
        generateDataDrivenRegistry(
            "DamageTypes",
            "DamageTypeRegistry",
            "DamageType",
            "damage_type.json"
        )
        generateDataDrivenRegistry(
            "EntityTypes",
            "EntityTypeRegistry",
            "EntityType",
            "entity_type.json"
        )
        generateDataDrivenRegistry(
            "FrogVariants",
            "FrogVariantRegistry",
            "FrogVariant",
            "frog_variant.json"
        )
        generateDataDrivenRegistry(
            "Items",
            "ItemRegistry",
            "Item",
            "item.json"
        )
        generateDataDrivenRegistry(
            "JukeboxSongs",
            "JukeboxSongRegistry",
            "JukeboxSong",
            "jukebox_song.json"
        )
        generateDataDrivenRegistry(
            "PaintingVariants",
            "PaintingVariantRegistry",
            "PaintingVariant",
            "painting_variant.json"
        )
        generateDataDrivenRegistry(
            "Particles",
            "ParticleRegistry",
            "Particle",
            "particle.json"
        )
        generateDataDrivenRegistry(
            "PigVariants",
            "PigVariantRegistry",
            "PigVariant",
            "pig_variant.json"
        )
        generateDataDrivenRegistry(
            "PotionEffects",
            "PotionEffectRegistry",
            "PotionEffect",
            "potion_effect.json"
        )
        generateDataDrivenRegistry(
            "TrimMaterials",
            "TrimMaterialRegistry",
            "TrimMaterial",
            "trim_material.json"
        )
        generateDataDrivenRegistry(
            "TrimPatterns",
            "TrimPatternRegistry",
            "TrimPattern",
            "trim_pattern.json"
        )
        generateDataDrivenRegistry(
            "WolfSoundVariants",
            "WolfSoundVariantRegistry",
            "WolfSoundVariant",
            "wolf_sound_variant.json"
        )
        generateDataDrivenRegistry(
            "WolfVariants",
            "WolfVariantRegistry",
            "WolfVariant",
            "wolf_variant.json"
        )
        generateDataDrivenRegistry(
            "ZombieNautilusVariants",
            "ZombieNautilusVariantRegistry",
            "ZombieNautilusVariant",
            "zombie_nautilus_variant.json"
        )

        generateSounds()
        generateTags()
    }

    @OptIn(ExperimentalSerializationApi::class)
    fun getKeys(resource: String): Set<String> {
        val resource = ClassLoader.getSystemResource(resource)!!
        val stream = resource.openStream()
        val parsed = Json.decodeFromStream<Map<String, JsonObject>>(stream)
        return parsed.keys
    }

    fun writeFile(keyClass: ClassName, typeSpec: TypeSpec) {
        val fileSpec = FileSpec.builder(keyClass)
            .addFileComment("AUTOGENERATED. DO NOT EDIT.")
            .addType(typeSpec)
            .build()

        fileSpec.writeTo(Path("../../src/main/kotlin"))
    }

    fun generateDataDrivenRegistry(
        keyClassName: String,
        registryClassName: String,
        entryClassName: String,
        resource: String,
    ) {
        val keyClass = ClassName("ru.cherryngine.lib.minecraft.registry.keys", keyClassName)
        val registryClass = ClassName("ru.cherryngine.lib.minecraft.registry.registries", registryClassName)
        val entryClass = ClassName("ru.cherryngine.lib.minecraft.registry.entries", entryClassName)

        val objectBuilder = TypeSpec.objectBuilder(keyClass.simpleName)

        getKeys(resource).forEach { key ->
            val constName = key.substringAfter(":").uppercase()

            val property = PropertySpec.builder(constName, entryClass)
                .initializer("%T[%S]", registryClass, key)
                .build()

            objectBuilder.addProperty(property)
        }

        writeFile(keyClass, objectBuilder.build())
    }

    fun generateSounds() {
        val keyClass = ClassName("ru.cherryngine.lib.minecraft.registry.keys", "Sounds")
        val entryClass = ClassName("net.kyori.adventure.key", "Key")

        val objectBuilder = TypeSpec.objectBuilder(keyClass.simpleName)

        getKeys("sound_event.json").forEach { key ->
            val constName = key.substringAfter(":").uppercase().replace(".", "_")

            val property = PropertySpec.builder(constName, entryClass)
                .initializer("%T.key(%S)", entryClass, key)
                .build()

            objectBuilder.addProperty(property)
        }

        writeFile(keyClass, objectBuilder.build())
    }

    fun generateTags() {
        val keyClass = ClassName("ru.cherryngine.lib.minecraft.registry.keys", "Tags")
        val entryClass = ClassName("ru.cherryngine.lib.minecraft.registry", "Tag")

        val objectBuilder = TypeSpec.objectBuilder(keyClass.simpleName)

        listOf(
            TagType(
                "biome",
                "BiomeTagRegistry",
                "tags/biome.json"
            ),
            TagType(
                "block",
                "BlockTagRegistry",
                "tags/block.json"
            ),
            TagType(
                "entity_type",
                "EntityTypeTagRegistry",
                "tags/entity_type.json"
            ),
            TagType(
                "fluid",
                "FluidTagRegistry",
                "tags/fluid.json"
            ),
            TagType(
                "item",
                "ItemTagRegistry",
                "tags/item.json"
            ),
        ).forEach { tagType ->
            val registryClass =
                ClassName("ru.cherryngine.lib.minecraft.registry.registries.tags", tagType.registryClassName)
            getKeys(tagType.resource).forEach { key ->

                val constName = key.substringAfter(":")
                    .let { "${tagType.prefix}_$it" }
                    .replace(".", "_")
                    .replace("/", "_")
                    .uppercase()
                val property = PropertySpec.builder(constName, entryClass)
                    .initializer("%T[%S]", registryClass, key)
                    .build()

                objectBuilder.addProperty(property)
            }
        }

        writeFile(keyClass, objectBuilder.build())
    }

    data class TagType(
        val prefix: String,
        val registryClassName: String,
        val resource: String,
    )
}