package ru.cherryngine.lib.minecraft.registry

import net.kyori.adventure.key.Key
import ru.cherryngine.lib.minecraft.registry.registries.BannerPattern

object BannerPatterns {
    val BASE = RegistryKey<BannerPattern>(Key.key("minecraft:base"))
    val BORDER = RegistryKey<BannerPattern>(Key.key("minecraft:border"))
    val BRICKS = RegistryKey<BannerPattern>(Key.key("minecraft:bricks"))
    val CIRCLE = RegistryKey<BannerPattern>(Key.key("minecraft:circle"))
    val CREEPER = RegistryKey<BannerPattern>(Key.key("minecraft:creeper"))
    val CROSS = RegistryKey<BannerPattern>(Key.key("minecraft:cross"))
    val CURLY_BORDER = RegistryKey<BannerPattern>(Key.key("minecraft:curly_border"))
    val DIAGONAL_LEFT = RegistryKey<BannerPattern>(Key.key("minecraft:diagonal_left"))
    val DIAGONAL_RIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:diagonal_right"))
    val DIAGONAL_UP_LEFT = RegistryKey<BannerPattern>(Key.key("minecraft:diagonal_up_left"))
    val DIAGONAL_UP_RIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:diagonal_up_right"))
    val FLOW = RegistryKey<BannerPattern>(Key.key("minecraft:flow"))
    val FLOWER = RegistryKey<BannerPattern>(Key.key("minecraft:flower"))
    val GLOBE = RegistryKey<BannerPattern>(Key.key("minecraft:globe"))
    val GRADIENT = RegistryKey<BannerPattern>(Key.key("minecraft:gradient"))
    val GRADIENT_UP = RegistryKey<BannerPattern>(Key.key("minecraft:gradient_up"))
    val GUSTER = RegistryKey<BannerPattern>(Key.key("minecraft:guster"))
    val HALF_HORIZONTAL = RegistryKey<BannerPattern>(Key.key("minecraft:half_horizontal"))
    val HALF_HORIZONTAL_BOTTOM = RegistryKey<BannerPattern>(Key.key("minecraft:half_horizontal_bottom"))
    val HALF_VERTICAL = RegistryKey<BannerPattern>(Key.key("minecraft:half_vertical"))
    val HALF_VERTICAL_RIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:half_vertical_right"))
    val MOJANG = RegistryKey<BannerPattern>(Key.key("minecraft:mojang"))
    val PIGLIN = RegistryKey<BannerPattern>(Key.key("minecraft:piglin"))
    val RHOMBUS = RegistryKey<BannerPattern>(Key.key("minecraft:rhombus"))
    val SKULL = RegistryKey<BannerPattern>(Key.key("minecraft:skull"))
    val SMALL_STRIPES = RegistryKey<BannerPattern>(Key.key("minecraft:small_stripes"))
    val SQUARE_BOTTOM_LEFT = RegistryKey<BannerPattern>(Key.key("minecraft:square_bottom_left"))
    val SQUARE_BOTTOM_RIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:square_bottom_right"))
    val SQUARE_TOP_LEFT = RegistryKey<BannerPattern>(Key.key("minecraft:square_top_left"))
    val SQUARE_TOP_RIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:square_top_right"))
    val STRAIGHT_CROSS = RegistryKey<BannerPattern>(Key.key("minecraft:straight_cross"))
    val STRIPE_BOTTOM = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_bottom"))
    val STRIPE_CENTER = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_center"))
    val STRIPE_DOWNLEFT = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_downleft"))
    val STRIPE_DOWNRIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_downright"))
    val STRIPE_LEFT = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_left"))
    val STRIPE_MIDDLE = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_middle"))
    val STRIPE_RIGHT = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_right"))
    val STRIPE_TOP = RegistryKey<BannerPattern>(Key.key("minecraft:stripe_top"))
    val TRIANGLE_BOTTOM = RegistryKey<BannerPattern>(Key.key("minecraft:triangle_bottom"))
    val TRIANGLE_TOP = RegistryKey<BannerPattern>(Key.key("minecraft:triangle_top"))
    val TRIANGLES_BOTTOM = RegistryKey<BannerPattern>(Key.key("minecraft:triangles_bottom"))
    val TRIANGLES_TOP = RegistryKey<BannerPattern>(Key.key("minecraft:triangles_top"))
}
