package ru.cherryngine.lib.minecraft.registry

import net.kyori.adventure.key.Key
import ru.cherryngine.lib.minecraft.registry.registries.Biome

object Biomes {
    val BADLANDS = RegistryKey<Biome>(Key.key("minecraft:badlands"))
    val BAMBOO_JUNGLE = RegistryKey<Biome>(Key.key("minecraft:bamboo_jungle"))
    val BASALT_DELTAS = RegistryKey<Biome>(Key.key("minecraft:basalt_deltas"))
    val BEACH = RegistryKey<Biome>(Key.key("minecraft:beach"))
    val BIRCH_FOREST = RegistryKey<Biome>(Key.key("minecraft:birch_forest"))
    val CHERRY_GROVE = RegistryKey<Biome>(Key.key("minecraft:cherry_grove"))
    val COLD_OCEAN = RegistryKey<Biome>(Key.key("minecraft:cold_ocean"))
    val CRIMSON_FOREST = RegistryKey<Biome>(Key.key("minecraft:crimson_forest"))
    val DARK_FOREST = RegistryKey<Biome>(Key.key("minecraft:dark_forest"))
    val DEEP_COLD_OCEAN = RegistryKey<Biome>(Key.key("minecraft:deep_cold_ocean"))
    val DEEP_DARK = RegistryKey<Biome>(Key.key("minecraft:deep_dark"))
    val DEEP_FROZEN_OCEAN = RegistryKey<Biome>(Key.key("minecraft:deep_frozen_ocean"))
    val DEEP_LUKEWARM_OCEAN = RegistryKey<Biome>(Key.key("minecraft:deep_lukewarm_ocean"))
    val DEEP_OCEAN = RegistryKey<Biome>(Key.key("minecraft:deep_ocean"))
    val DESERT = RegistryKey<Biome>(Key.key("minecraft:desert"))
    val DRIPSTONE_CAVES = RegistryKey<Biome>(Key.key("minecraft:dripstone_caves"))
    val END_BARRENS = RegistryKey<Biome>(Key.key("minecraft:end_barrens"))
    val END_HIGHLANDS = RegistryKey<Biome>(Key.key("minecraft:end_highlands"))
    val END_MIDLANDS = RegistryKey<Biome>(Key.key("minecraft:end_midlands"))
    val ERODED_BADLANDS = RegistryKey<Biome>(Key.key("minecraft:eroded_badlands"))
    val FLOWER_FOREST = RegistryKey<Biome>(Key.key("minecraft:flower_forest"))
    val FOREST = RegistryKey<Biome>(Key.key("minecraft:forest"))
    val FROZEN_OCEAN = RegistryKey<Biome>(Key.key("minecraft:frozen_ocean"))
    val FROZEN_PEAKS = RegistryKey<Biome>(Key.key("minecraft:frozen_peaks"))
    val FROZEN_RIVER = RegistryKey<Biome>(Key.key("minecraft:frozen_river"))
    val GROVE = RegistryKey<Biome>(Key.key("minecraft:grove"))
    val ICE_SPIKES = RegistryKey<Biome>(Key.key("minecraft:ice_spikes"))
    val JAGGED_PEAKS = RegistryKey<Biome>(Key.key("minecraft:jagged_peaks"))
    val JUNGLE = RegistryKey<Biome>(Key.key("minecraft:jungle"))
    val LUKEWARM_OCEAN = RegistryKey<Biome>(Key.key("minecraft:lukewarm_ocean"))
    val LUSH_CAVES = RegistryKey<Biome>(Key.key("minecraft:lush_caves"))
    val MANGROVE_SWAMP = RegistryKey<Biome>(Key.key("minecraft:mangrove_swamp"))
    val MEADOW = RegistryKey<Biome>(Key.key("minecraft:meadow"))
    val MUSHROOM_FIELDS = RegistryKey<Biome>(Key.key("minecraft:mushroom_fields"))
    val NETHER_WASTES = RegistryKey<Biome>(Key.key("minecraft:nether_wastes"))
    val OCEAN = RegistryKey<Biome>(Key.key("minecraft:ocean"))
    val OLD_GROWTH_BIRCH_FOREST = RegistryKey<Biome>(Key.key("minecraft:old_growth_birch_forest"))
    val OLD_GROWTH_PINE_TAIGA = RegistryKey<Biome>(Key.key("minecraft:old_growth_pine_taiga"))
    val OLD_GROWTH_SPRUCE_TAIGA = RegistryKey<Biome>(Key.key("minecraft:old_growth_spruce_taiga"))
    val PLAINS = RegistryKey<Biome>(Key.key("minecraft:plains"))
    val RIVER = RegistryKey<Biome>(Key.key("minecraft:river"))
    val SAVANNA = RegistryKey<Biome>(Key.key("minecraft:savanna"))
    val SAVANNA_PLATEAU = RegistryKey<Biome>(Key.key("minecraft:savanna_plateau"))
    val SMALL_END_ISLANDS = RegistryKey<Biome>(Key.key("minecraft:small_end_islands"))
    val SNOWY_BEACH = RegistryKey<Biome>(Key.key("minecraft:snowy_beach"))
    val SNOWY_PLAINS = RegistryKey<Biome>(Key.key("minecraft:snowy_plains"))
    val SNOWY_SLOPES = RegistryKey<Biome>(Key.key("minecraft:snowy_slopes"))
    val SNOWY_TAIGA = RegistryKey<Biome>(Key.key("minecraft:snowy_taiga"))
    val SOUL_SAND_VALLEY = RegistryKey<Biome>(Key.key("minecraft:soul_sand_valley"))
    val SPARSE_JUNGLE = RegistryKey<Biome>(Key.key("minecraft:sparse_jungle"))
    val STONY_PEAKS = RegistryKey<Biome>(Key.key("minecraft:stony_peaks"))
    val STONY_SHORE = RegistryKey<Biome>(Key.key("minecraft:stony_shore"))
    val SUNFLOWER_PLAINS = RegistryKey<Biome>(Key.key("minecraft:sunflower_plains"))
    val SWAMP = RegistryKey<Biome>(Key.key("minecraft:swamp"))
    val TAIGA = RegistryKey<Biome>(Key.key("minecraft:taiga"))
    val THE_END = RegistryKey<Biome>(Key.key("minecraft:the_end"))
    val THE_VOID = RegistryKey<Biome>(Key.key("minecraft:the_void"))
    val WARM_OCEAN = RegistryKey<Biome>(Key.key("minecraft:warm_ocean"))
    val WARPED_FOREST = RegistryKey<Biome>(Key.key("minecraft:warped_forest"))
    val WINDSWEPT_FOREST = RegistryKey<Biome>(Key.key("minecraft:windswept_forest"))
    val WINDSWEPT_GRAVELLY_HILLS = RegistryKey<Biome>(Key.key("minecraft:windswept_gravelly_hills"))
    val WINDSWEPT_HILLS = RegistryKey<Biome>(Key.key("minecraft:windswept_hills"))
    val WINDSWEPT_SAVANNA = RegistryKey<Biome>(Key.key("minecraft:windswept_savanna"))
    val WOODED_BADLANDS = RegistryKey<Biome>(Key.key("minecraft:wooded_badlands"))
}