package ru.cherryngine.lib.minecraft.registry

import ru.cherryngine.lib.minecraft.registry.registries.ChickenVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object ChickenVariants {
    val COLD = ChickenVariantRegistry["minecraft:cold"]
    val TEMPERATE = ChickenVariantRegistry["minecraft:temperate"]
    val WARM = ChickenVariantRegistry["minecraft:warm"]
}
