package ru.cherryngine.lib.minecraft.registry

import net.kyori.adventure.key.Key
import ru.cherryngine.lib.minecraft.registry.registries.DamageType

object DamageTypes {
    val ARROW = RegistryKey<DamageType>(Key.key("minecraft:arrow"))
    val BAD_RESPAWN_POINT = RegistryKey<DamageType>(Key.key("minecraft:bad_respawn_point"))
    val CACTUS = RegistryKey<DamageType>(Key.key("minecraft:cactus"))
    val CAMPFIRE = RegistryKey<DamageType>(Key.key("minecraft:campfire"))
    val CRAMMING = RegistryKey<DamageType>(Key.key("minecraft:cramming"))
    val DRAGON_BREATH = RegistryKey<DamageType>(Key.key("minecraft:dragon_breath"))
    val DROWN = RegistryKey<DamageType>(Key.key("minecraft:drown"))
    val DRY_OUT = RegistryKey<DamageType>(Key.key("minecraft:dry_out"))
    val ENDER_PEARL = RegistryKey<DamageType>(Key.key("minecraft:ender_pearl"))
    val EXPLOSION = RegistryKey<DamageType>(Key.key("minecraft:explosion"))
    val FALL = RegistryKey<DamageType>(Key.key("minecraft:fall"))
    val FALLING_ANVIL = RegistryKey<DamageType>(Key.key("minecraft:falling_anvil"))
    val FALLING_BLOCK = RegistryKey<DamageType>(Key.key("minecraft:falling_block"))
    val FALLING_STALACTITE = RegistryKey<DamageType>(Key.key("minecraft:falling_stalactite"))
    val FIREBALL = RegistryKey<DamageType>(Key.key("minecraft:fireball"))
    val FIREWORKS = RegistryKey<DamageType>(Key.key("minecraft:fireworks"))
    val FLY_INTO_WALL = RegistryKey<DamageType>(Key.key("minecraft:fly_into_wall"))
    val FREEZE = RegistryKey<DamageType>(Key.key("minecraft:freeze"))
    val GENERIC = RegistryKey<DamageType>(Key.key("minecraft:generic"))
    val GENERIC_KILL = RegistryKey<DamageType>(Key.key("minecraft:generic_kill"))
    val HOT_FLOOR = RegistryKey<DamageType>(Key.key("minecraft:hot_floor"))
    val IN_FIRE = RegistryKey<DamageType>(Key.key("minecraft:in_fire"))
    val IN_WALL = RegistryKey<DamageType>(Key.key("minecraft:in_wall"))
    val INDIRECT_MAGIC = RegistryKey<DamageType>(Key.key("minecraft:indirect_magic"))
    val LAVA = RegistryKey<DamageType>(Key.key("minecraft:lava"))
    val LIGHTNING_BOLT = RegistryKey<DamageType>(Key.key("minecraft:lightning_bolt"))
    val MACE_SMASH = RegistryKey<DamageType>(Key.key("minecraft:mace_smash"))
    val MAGIC = RegistryKey<DamageType>(Key.key("minecraft:magic"))
    val MOB_ATTACK = RegistryKey<DamageType>(Key.key("minecraft:mob_attack"))
    val MOB_ATTACK_NO_AGGRO = RegistryKey<DamageType>(Key.key("minecraft:mob_attack_no_aggro"))
    val MOB_PROJECTILE = RegistryKey<DamageType>(Key.key("minecraft:mob_projectile"))
    val ON_FIRE = RegistryKey<DamageType>(Key.key("minecraft:on_fire"))
    val OUT_OF_WORLD = RegistryKey<DamageType>(Key.key("minecraft:out_of_world"))
    val OUTSIDE_BORDER = RegistryKey<DamageType>(Key.key("minecraft:outside_border"))
    val PLAYER_ATTACK = RegistryKey<DamageType>(Key.key("minecraft:player_attack"))
    val PLAYER_EXPLOSION = RegistryKey<DamageType>(Key.key("minecraft:player_explosion"))
    val SONIC_BOOM = RegistryKey<DamageType>(Key.key("minecraft:sonic_boom"))
    val SPIT = RegistryKey<DamageType>(Key.key("minecraft:spit"))
    val STALAGMITE = RegistryKey<DamageType>(Key.key("minecraft:stalagmite"))
    val STARVE = RegistryKey<DamageType>(Key.key("minecraft:starve"))
    val STING = RegistryKey<DamageType>(Key.key("minecraft:sting"))
    val SWEET_BERRY_BUSH = RegistryKey<DamageType>(Key.key("minecraft:sweet_berry_bush"))
    val THORNS = RegistryKey<DamageType>(Key.key("minecraft:thorns"))
    val THROWN = RegistryKey<DamageType>(Key.key("minecraft:thrown"))
    val TRIDENT = RegistryKey<DamageType>(Key.key("minecraft:trident"))
    val UNATTRIBUTED_FIREBALL = RegistryKey<DamageType>(Key.key("minecraft:unattributed_fireball"))
    val WIND_CHARGE = RegistryKey<DamageType>(Key.key("minecraft:wind_charge"))
    val WITHER = RegistryKey<DamageType>(Key.key("minecraft:wither"))
    val WITHER_SKULL = RegistryKey<DamageType>(Key.key("minecraft:wither_skull"))
}
