package ru.cherryngine.lib.minecraft.registry

import ru.cherryngine.lib.minecraft.registry.registries.FrogVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object FrogVariants {
    val COLD = FrogVariantRegistry["minecraft:cold"]
    val TEMPERATE = FrogVariantRegistry["minecraft:temperate"]
    val WARM = FrogVariantRegistry["minecraft:warm"]
}
