package ru.cherryngine.lib.minecraft.registry

import net.kyori.adventure.key.Key
import ru.cherryngine.lib.minecraft.registry.registries.PaintingVariant

object PaintingVariants {
    val ALBAN = RegistryKey<PaintingVariant>(Key.key("minecraft:alban"))
    val AZTEC = RegistryKey<PaintingVariant>(Key.key("minecraft:aztec"))
    val AZTEC2 = RegistryKey<PaintingVariant>(Key.key("minecraft:aztec2"))
    val BACKYARD = RegistryKey<PaintingVariant>(Key.key("minecraft:backyard"))
    val BAROQUE = RegistryKey<PaintingVariant>(Key.key("minecraft:baroque"))
    val BOMB = RegistryKey<PaintingVariant>(Key.key("minecraft:bomb"))
    val BOUQUET = RegistryKey<PaintingVariant>(Key.key("minecraft:bouquet"))
    val BURNING_SKULL = RegistryKey<PaintingVariant>(Key.key("minecraft:burning_skull"))
    val BUST = RegistryKey<PaintingVariant>(Key.key("minecraft:bust"))
    val CAVEBIRD = RegistryKey<PaintingVariant>(Key.key("minecraft:cavebird"))
    val CHANGING = RegistryKey<PaintingVariant>(Key.key("minecraft:changing"))
    val COTAN = RegistryKey<PaintingVariant>(Key.key("minecraft:cotan"))
    val COURBET = RegistryKey<PaintingVariant>(Key.key("minecraft:courbet"))
    val CREEBET = RegistryKey<PaintingVariant>(Key.key("minecraft:creebet"))
    val DENNIS = RegistryKey<PaintingVariant>(Key.key("minecraft:dennis"))
    val DONKEY_KONG = RegistryKey<PaintingVariant>(Key.key("minecraft:donkey_kong"))
    val EARTH = RegistryKey<PaintingVariant>(Key.key("minecraft:earth"))
    val ENDBOSS = RegistryKey<PaintingVariant>(Key.key("minecraft:endboss"))
    val FERN = RegistryKey<PaintingVariant>(Key.key("minecraft:fern"))
    val FIGHTERS = RegistryKey<PaintingVariant>(Key.key("minecraft:fighters"))
    val FINDING = RegistryKey<PaintingVariant>(Key.key("minecraft:finding"))
    val FIRE = RegistryKey<PaintingVariant>(Key.key("minecraft:fire"))
    val GRAHAM = RegistryKey<PaintingVariant>(Key.key("minecraft:graham"))
    val HUMBLE = RegistryKey<PaintingVariant>(Key.key("minecraft:humble"))
    val KEBAB = RegistryKey<PaintingVariant>(Key.key("minecraft:kebab"))
    val LOWMIST = RegistryKey<PaintingVariant>(Key.key("minecraft:lowmist"))
    val MATCH = RegistryKey<PaintingVariant>(Key.key("minecraft:match"))
    val MEDITATIVE = RegistryKey<PaintingVariant>(Key.key("minecraft:meditative"))
    val ORB = RegistryKey<PaintingVariant>(Key.key("minecraft:orb"))
    val OWLEMONS = RegistryKey<PaintingVariant>(Key.key("minecraft:owlemons"))
    val PASSAGE = RegistryKey<PaintingVariant>(Key.key("minecraft:passage"))
    val PIGSCENE = RegistryKey<PaintingVariant>(Key.key("minecraft:pigscene"))
    val PLANT = RegistryKey<PaintingVariant>(Key.key("minecraft:plant"))
    val POINTER = RegistryKey<PaintingVariant>(Key.key("minecraft:pointer"))
    val POND = RegistryKey<PaintingVariant>(Key.key("minecraft:pond"))
    val POOL = RegistryKey<PaintingVariant>(Key.key("minecraft:pool"))
    val PRAIRIE_RIDE = RegistryKey<PaintingVariant>(Key.key("minecraft:prairie_ride"))
    val SEA = RegistryKey<PaintingVariant>(Key.key("minecraft:sea"))
    val SKELETON = RegistryKey<PaintingVariant>(Key.key("minecraft:skeleton"))
    val SKULL_AND_ROSES = RegistryKey<PaintingVariant>(Key.key("minecraft:skull_and_roses"))
    val STAGE = RegistryKey<PaintingVariant>(Key.key("minecraft:stage"))
    val SUNFLOWERS = RegistryKey<PaintingVariant>(Key.key("minecraft:sunflowers"))
    val SUNSET = RegistryKey<PaintingVariant>(Key.key("minecraft:sunset"))
    val TIDES = RegistryKey<PaintingVariant>(Key.key("minecraft:tides"))
    val UNPACKED = RegistryKey<PaintingVariant>(Key.key("minecraft:unpacked"))
    val VOID = RegistryKey<PaintingVariant>(Key.key("minecraft:void"))
    val WANDERER = RegistryKey<PaintingVariant>(Key.key("minecraft:wanderer"))
    val WASTELAND = RegistryKey<PaintingVariant>(Key.key("minecraft:wasteland"))
    val WATER = RegistryKey<PaintingVariant>(Key.key("minecraft:water"))
    val WIND = RegistryKey<PaintingVariant>(Key.key("minecraft:wind"))
    val WITHER = RegistryKey<PaintingVariant>(Key.key("minecraft:wither"))
}
