package ru.cherryngine.lib.minecraft.registry

import net.kyori.adventure.key.Key
import ru.cherryngine.lib.minecraft.registry.registries.PotionEffect

object PotionEffects {
    val SPEED = RegistryKey<PotionEffect>(Key.key("minecraft:speed"))
    val SLOWNESS = RegistryKey<PotionEffect>(Key.key("minecraft:slowness"))
    val HASTE = RegistryKey<PotionEffect>(Key.key("minecraft:haste"))
    val MINING_FATIGUE = RegistryKey<PotionEffect>(Key.key("minecraft:mining_fatigue"))
    val STRENGTH = RegistryKey<PotionEffect>(Key.key("minecraft:strength"))
    val INSTANT_HEALTH = RegistryKey<PotionEffect>(Key.key("minecraft:instant_health"))
    val INSTANT_DAMAGE = RegistryKey<PotionEffect>(Key.key("minecraft:instant_damage"))
    val JUMP_BOOST = RegistryKey<PotionEffect>(Key.key("minecraft:jump_boost"))
    val NAUSEA = RegistryKey<PotionEffect>(Key.key("minecraft:nausea"))
    val REGENERATION = RegistryKey<PotionEffect>(Key.key("minecraft:regeneration"))
    val RESISTANCE = RegistryKey<PotionEffect>(Key.key("minecraft:resistance"))
    val FIRE_RESISTANCE = RegistryKey<PotionEffect>(Key.key("minecraft:fire_resistance"))
    val WATER_BREATHING = RegistryKey<PotionEffect>(Key.key("minecraft:water_breathing"))
    val INVISIBILITY = RegistryKey<PotionEffect>(Key.key("minecraft:invisibility"))
    val BLINDNESS = RegistryKey<PotionEffect>(Key.key("minecraft:blindness"))
    val NIGHT_VISION = RegistryKey<PotionEffect>(Key.key("minecraft:night_vision"))
    val HUNGER = RegistryKey<PotionEffect>(Key.key("minecraft:hunger"))
    val WEAKNESS = RegistryKey<PotionEffect>(Key.key("minecraft:weakness"))
    val POISON = RegistryKey<PotionEffect>(Key.key("minecraft:poison"))
    val WITHER = RegistryKey<PotionEffect>(Key.key("minecraft:wither"))
    val HEALTH_BOOST = RegistryKey<PotionEffect>(Key.key("minecraft:health_boost"))
    val ABSORPTION = RegistryKey<PotionEffect>(Key.key("minecraft:absorption"))
    val SATURATION = RegistryKey<PotionEffect>(Key.key("minecraft:saturation"))
    val GLOWING = RegistryKey<PotionEffect>(Key.key("minecraft:glowing"))
    val LEVITATION = RegistryKey<PotionEffect>(Key.key("minecraft:levitation"))
    val LUCK = RegistryKey<PotionEffect>(Key.key("minecraft:luck"))
    val UNLUCK = RegistryKey<PotionEffect>(Key.key("minecraft:unluck"))
    val SLOW_FALLING = RegistryKey<PotionEffect>(Key.key("minecraft:slow_falling"))
    val CONDUIT_POWER = RegistryKey<PotionEffect>(Key.key("minecraft:conduit_power"))
    val DOLPHINS_GRACE = RegistryKey<PotionEffect>(Key.key("minecraft:dolphins_grace"))
    val BAD_OMEN = RegistryKey<PotionEffect>(Key.key("minecraft:bad_omen"))
    val HERO_OF_THE_VILLAGE = RegistryKey<PotionEffect>(Key.key("minecraft:hero_of_the_village"))
    val DARKNESS = RegistryKey<PotionEffect>(Key.key("minecraft:darkness"))
    val TRIAL_OMEN = RegistryKey<PotionEffect>(Key.key("minecraft:trial_omen"))
    val RAID_OMEN = RegistryKey<PotionEffect>(Key.key("minecraft:raid_omen"))
    val WIND_CHARGED = RegistryKey<PotionEffect>(Key.key("minecraft:wind_charged"))
    val WEAVING = RegistryKey<PotionEffect>(Key.key("minecraft:weaving"))
    val OOZING = RegistryKey<PotionEffect>(Key.key("minecraft:oozing"))
    val INFESTED = RegistryKey<PotionEffect>(Key.key("minecraft:infested"))
}
