// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.Attribute
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object Attributes {
  public val ARMOR: Key<Attribute> = fromKey("minecraft:armor")

  public val ARMOR_TOUGHNESS: Key<Attribute> = fromKey("minecraft:armor_toughness")

  public val ATTACK_DAMAGE: Key<Attribute> = fromKey("minecraft:attack_damage")

  public val ATTACK_KNOCKBACK: Key<Attribute> = fromKey("minecraft:attack_knockback")

  public val ATTACK_SPEED: Key<Attribute> = fromKey("minecraft:attack_speed")

  public val BLOCK_BREAK_SPEED: Key<Attribute> = fromKey("minecraft:block_break_speed")

  public val BLOCK_INTERACTION_RANGE: Key<Attribute> = fromKey("minecraft:block_interaction_range")

  public val BURNING_TIME: Key<Attribute> = fromKey("minecraft:burning_time")

  public val CAMERA_DISTANCE: Key<Attribute> = fromKey("minecraft:camera_distance")

  public val EXPLOSION_KNOCKBACK_RESISTANCE: Key<Attribute> =
      fromKey("minecraft:explosion_knockback_resistance")

  public val ENTITY_INTERACTION_RANGE: Key<Attribute> =
      fromKey("minecraft:entity_interaction_range")

  public val FALL_DAMAGE_MULTIPLIER: Key<Attribute> = fromKey("minecraft:fall_damage_multiplier")

  public val FLYING_SPEED: Key<Attribute> = fromKey("minecraft:flying_speed")

  public val FOLLOW_RANGE: Key<Attribute> = fromKey("minecraft:follow_range")

  public val GRAVITY: Key<Attribute> = fromKey("minecraft:gravity")

  public val JUMP_STRENGTH: Key<Attribute> = fromKey("minecraft:jump_strength")

  public val KNOCKBACK_RESISTANCE: Key<Attribute> = fromKey("minecraft:knockback_resistance")

  public val LUCK: Key<Attribute> = fromKey("minecraft:luck")

  public val MAX_ABSORPTION: Key<Attribute> = fromKey("minecraft:max_absorption")

  public val MAX_HEALTH: Key<Attribute> = fromKey("minecraft:max_health")

  public val MINING_EFFICIENCY: Key<Attribute> = fromKey("minecraft:mining_efficiency")

  public val MOVEMENT_EFFICIENCY: Key<Attribute> = fromKey("minecraft:movement_efficiency")

  public val MOVEMENT_SPEED: Key<Attribute> = fromKey("minecraft:movement_speed")

  public val OXYGEN_BONUS: Key<Attribute> = fromKey("minecraft:oxygen_bonus")

  public val SAFE_FALL_DISTANCE: Key<Attribute> = fromKey("minecraft:safe_fall_distance")

  public val SCALE: Key<Attribute> = fromKey("minecraft:scale")

  public val SNEAKING_SPEED: Key<Attribute> = fromKey("minecraft:sneaking_speed")

  public val SPAWN_REINFORCEMENTS: Key<Attribute> = fromKey("minecraft:spawn_reinforcements")

  public val STEP_HEIGHT: Key<Attribute> = fromKey("minecraft:step_height")

  public val SUBMERGED_MINING_SPEED: Key<Attribute> = fromKey("minecraft:submerged_mining_speed")

  public val SWEEPING_DAMAGE_RATIO: Key<Attribute> = fromKey("minecraft:sweeping_damage_ratio")

  public val TEMPT_RANGE: Key<Attribute> = fromKey("minecraft:tempt_range")

  public val WATER_MOVEMENT_EFFICIENCY: Key<Attribute> =
      fromKey("minecraft:water_movement_efficiency")

  public val WAYPOINT_TRANSMIT_RANGE: Key<Attribute> = fromKey("minecraft:waypoint_transmit_range")

  public val WAYPOINT_RECEIVE_RANGE: Key<Attribute> = fromKey("minecraft:waypoint_receive_range")
}
