// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.Attribute
import ru.cherryngine.lib.minecraft.registry.registries.AttributeRegistry

public object Attributes {
  public val ARMOR: Attribute = AttributeRegistry["minecraft:armor"]

  public val ARMOR_TOUGHNESS: Attribute = AttributeRegistry["minecraft:armor_toughness"]

  public val ATTACK_DAMAGE: Attribute = AttributeRegistry["minecraft:attack_damage"]

  public val ATTACK_KNOCKBACK: Attribute = AttributeRegistry["minecraft:attack_knockback"]

  public val ATTACK_SPEED: Attribute = AttributeRegistry["minecraft:attack_speed"]

  public val BLOCK_BREAK_SPEED: Attribute = AttributeRegistry["minecraft:block_break_speed"]

  public val BLOCK_INTERACTION_RANGE: Attribute =
      AttributeRegistry["minecraft:block_interaction_range"]

  public val BURNING_TIME: Attribute = AttributeRegistry["minecraft:burning_time"]

  public val CAMERA_DISTANCE: Attribute = AttributeRegistry["minecraft:camera_distance"]

  public val EXPLOSION_KNOCKBACK_RESISTANCE: Attribute =
      AttributeRegistry["minecraft:explosion_knockback_resistance"]

  public val ENTITY_INTERACTION_RANGE: Attribute =
      AttributeRegistry["minecraft:entity_interaction_range"]

  public val FALL_DAMAGE_MULTIPLIER: Attribute =
      AttributeRegistry["minecraft:fall_damage_multiplier"]

  public val FLYING_SPEED: Attribute = AttributeRegistry["minecraft:flying_speed"]

  public val FOLLOW_RANGE: Attribute = AttributeRegistry["minecraft:follow_range"]

  public val GRAVITY: Attribute = AttributeRegistry["minecraft:gravity"]

  public val JUMP_STRENGTH: Attribute = AttributeRegistry["minecraft:jump_strength"]

  public val KNOCKBACK_RESISTANCE: Attribute = AttributeRegistry["minecraft:knockback_resistance"]

  public val LUCK: Attribute = AttributeRegistry["minecraft:luck"]

  public val MAX_ABSORPTION: Attribute = AttributeRegistry["minecraft:max_absorption"]

  public val MAX_HEALTH: Attribute = AttributeRegistry["minecraft:max_health"]

  public val MINING_EFFICIENCY: Attribute = AttributeRegistry["minecraft:mining_efficiency"]

  public val MOVEMENT_EFFICIENCY: Attribute = AttributeRegistry["minecraft:movement_efficiency"]

  public val MOVEMENT_SPEED: Attribute = AttributeRegistry["minecraft:movement_speed"]

  public val OXYGEN_BONUS: Attribute = AttributeRegistry["minecraft:oxygen_bonus"]

  public val SAFE_FALL_DISTANCE: Attribute = AttributeRegistry["minecraft:safe_fall_distance"]

  public val SCALE: Attribute = AttributeRegistry["minecraft:scale"]

  public val SNEAKING_SPEED: Attribute = AttributeRegistry["minecraft:sneaking_speed"]

  public val SPAWN_REINFORCEMENTS: Attribute = AttributeRegistry["minecraft:spawn_reinforcements"]

  public val STEP_HEIGHT: Attribute = AttributeRegistry["minecraft:step_height"]

  public val SUBMERGED_MINING_SPEED: Attribute =
      AttributeRegistry["minecraft:submerged_mining_speed"]

  public val SWEEPING_DAMAGE_RATIO: Attribute = AttributeRegistry["minecraft:sweeping_damage_ratio"]

  public val TEMPT_RANGE: Attribute = AttributeRegistry["minecraft:tempt_range"]

  public val WATER_MOVEMENT_EFFICIENCY: Attribute =
      AttributeRegistry["minecraft:water_movement_efficiency"]

  public val WAYPOINT_TRANSMIT_RANGE: Attribute =
      AttributeRegistry["minecraft:waypoint_transmit_range"]

  public val WAYPOINT_RECEIVE_RANGE: Attribute =
      AttributeRegistry["minecraft:waypoint_receive_range"]
}
