// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.Attribute
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object Attributes {
  public val ARMOR: RegistryKey<Attribute> = createKey("minecraft:armor")

  public val ARMOR_TOUGHNESS: RegistryKey<Attribute> = createKey("minecraft:armor_toughness")

  public val ATTACK_DAMAGE: RegistryKey<Attribute> = createKey("minecraft:attack_damage")

  public val ATTACK_KNOCKBACK: RegistryKey<Attribute> = createKey("minecraft:attack_knockback")

  public val ATTACK_SPEED: RegistryKey<Attribute> = createKey("minecraft:attack_speed")

  public val BLOCK_BREAK_SPEED: RegistryKey<Attribute> = createKey("minecraft:block_break_speed")

  public val BLOCK_INTERACTION_RANGE: RegistryKey<Attribute> =
      createKey("minecraft:block_interaction_range")

  public val BURNING_TIME: RegistryKey<Attribute> = createKey("minecraft:burning_time")

  public val CAMERA_DISTANCE: RegistryKey<Attribute> = createKey("minecraft:camera_distance")

  public val EXPLOSION_KNOCKBACK_RESISTANCE: RegistryKey<Attribute> =
      createKey("minecraft:explosion_knockback_resistance")

  public val ENTITY_INTERACTION_RANGE: RegistryKey<Attribute> =
      createKey("minecraft:entity_interaction_range")

  public val FALL_DAMAGE_MULTIPLIER: RegistryKey<Attribute> =
      createKey("minecraft:fall_damage_multiplier")

  public val FLYING_SPEED: RegistryKey<Attribute> = createKey("minecraft:flying_speed")

  public val FOLLOW_RANGE: RegistryKey<Attribute> = createKey("minecraft:follow_range")

  public val GRAVITY: RegistryKey<Attribute> = createKey("minecraft:gravity")

  public val JUMP_STRENGTH: RegistryKey<Attribute> = createKey("minecraft:jump_strength")

  public val KNOCKBACK_RESISTANCE: RegistryKey<Attribute> =
      createKey("minecraft:knockback_resistance")

  public val LUCK: RegistryKey<Attribute> = createKey("minecraft:luck")

  public val MAX_ABSORPTION: RegistryKey<Attribute> = createKey("minecraft:max_absorption")

  public val MAX_HEALTH: RegistryKey<Attribute> = createKey("minecraft:max_health")

  public val MINING_EFFICIENCY: RegistryKey<Attribute> = createKey("minecraft:mining_efficiency")

  public val MOVEMENT_EFFICIENCY: RegistryKey<Attribute> =
      createKey("minecraft:movement_efficiency")

  public val MOVEMENT_SPEED: RegistryKey<Attribute> = createKey("minecraft:movement_speed")

  public val OXYGEN_BONUS: RegistryKey<Attribute> = createKey("minecraft:oxygen_bonus")

  public val SAFE_FALL_DISTANCE: RegistryKey<Attribute> = createKey("minecraft:safe_fall_distance")

  public val SCALE: RegistryKey<Attribute> = createKey("minecraft:scale")

  public val SNEAKING_SPEED: RegistryKey<Attribute> = createKey("minecraft:sneaking_speed")

  public val SPAWN_REINFORCEMENTS: RegistryKey<Attribute> =
      createKey("minecraft:spawn_reinforcements")

  public val STEP_HEIGHT: RegistryKey<Attribute> = createKey("minecraft:step_height")

  public val SUBMERGED_MINING_SPEED: RegistryKey<Attribute> =
      createKey("minecraft:submerged_mining_speed")

  public val SWEEPING_DAMAGE_RATIO: RegistryKey<Attribute> =
      createKey("minecraft:sweeping_damage_ratio")

  public val TEMPT_RANGE: RegistryKey<Attribute> = createKey("minecraft:tempt_range")

  public val WATER_MOVEMENT_EFFICIENCY: RegistryKey<Attribute> =
      createKey("minecraft:water_movement_efficiency")

  public val WAYPOINT_TRANSMIT_RANGE: RegistryKey<Attribute> =
      createKey("minecraft:waypoint_transmit_range")

  public val WAYPOINT_RECEIVE_RANGE: RegistryKey<Attribute> =
      createKey("minecraft:waypoint_receive_range")
}
