// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.BannerPattern
import ru.cherryngine.lib.minecraft.registry.registries.BannerPatternRegistry

public object BannerPatterns {
  public val BORDER: BannerPattern = BannerPatternRegistry["minecraft:border"]

  public val SQUARE_BOTTOM_RIGHT: BannerPattern =
      BannerPatternRegistry["minecraft:square_bottom_right"]

  public val STRIPE_RIGHT: BannerPattern = BannerPatternRegistry["minecraft:stripe_right"]

  public val FLOW: BannerPattern = BannerPatternRegistry["minecraft:flow"]

  public val RHOMBUS: BannerPattern = BannerPatternRegistry["minecraft:rhombus"]

  public val TRIANGLES_TOP: BannerPattern = BannerPatternRegistry["minecraft:triangles_top"]

  public val GRADIENT: BannerPattern = BannerPatternRegistry["minecraft:gradient"]

  public val GLOBE: BannerPattern = BannerPatternRegistry["minecraft:globe"]

  public val MOJANG: BannerPattern = BannerPatternRegistry["minecraft:mojang"]

  public val STRIPE_BOTTOM: BannerPattern = BannerPatternRegistry["minecraft:stripe_bottom"]

  public val STRIPE_MIDDLE: BannerPattern = BannerPatternRegistry["minecraft:stripe_middle"]

  public val FLOWER: BannerPattern = BannerPatternRegistry["minecraft:flower"]

  public val DIAGONAL_UP_RIGHT: BannerPattern = BannerPatternRegistry["minecraft:diagonal_up_right"]

  public val CIRCLE: BannerPattern = BannerPatternRegistry["minecraft:circle"]

  public val HALF_HORIZONTAL: BannerPattern = BannerPatternRegistry["minecraft:half_horizontal"]

  public val BRICKS: BannerPattern = BannerPatternRegistry["minecraft:bricks"]

  public val TRIANGLE_BOTTOM: BannerPattern = BannerPatternRegistry["minecraft:triangle_bottom"]

  public val CURLY_BORDER: BannerPattern = BannerPatternRegistry["minecraft:curly_border"]

  public val BASE: BannerPattern = BannerPatternRegistry["minecraft:base"]

  public val PIGLIN: BannerPattern = BannerPatternRegistry["minecraft:piglin"]

  public val STRIPE_CENTER: BannerPattern = BannerPatternRegistry["minecraft:stripe_center"]

  public val SQUARE_BOTTOM_LEFT: BannerPattern =
      BannerPatternRegistry["minecraft:square_bottom_left"]

  public val SQUARE_TOP_RIGHT: BannerPattern = BannerPatternRegistry["minecraft:square_top_right"]

  public val STRIPE_DOWNRIGHT: BannerPattern = BannerPatternRegistry["minecraft:stripe_downright"]

  public val GUSTER: BannerPattern = BannerPatternRegistry["minecraft:guster"]

  public val GRADIENT_UP: BannerPattern = BannerPatternRegistry["minecraft:gradient_up"]

  public val DIAGONAL_RIGHT: BannerPattern = BannerPatternRegistry["minecraft:diagonal_right"]

  public val HALF_VERTICAL_RIGHT: BannerPattern =
      BannerPatternRegistry["minecraft:half_vertical_right"]

  public val SMALL_STRIPES: BannerPattern = BannerPatternRegistry["minecraft:small_stripes"]

  public val CROSS: BannerPattern = BannerPatternRegistry["minecraft:cross"]

  public val DIAGONAL_LEFT: BannerPattern = BannerPatternRegistry["minecraft:diagonal_left"]

  public val SKULL: BannerPattern = BannerPatternRegistry["minecraft:skull"]

  public val STRIPE_DOWNLEFT: BannerPattern = BannerPatternRegistry["minecraft:stripe_downleft"]

  public val DIAGONAL_UP_LEFT: BannerPattern = BannerPatternRegistry["minecraft:diagonal_up_left"]

  public val HALF_VERTICAL: BannerPattern = BannerPatternRegistry["minecraft:half_vertical"]

  public val TRIANGLE_TOP: BannerPattern = BannerPatternRegistry["minecraft:triangle_top"]

  public val HALF_HORIZONTAL_BOTTOM: BannerPattern =
      BannerPatternRegistry["minecraft:half_horizontal_bottom"]

  public val SQUARE_TOP_LEFT: BannerPattern = BannerPatternRegistry["minecraft:square_top_left"]

  public val STRIPE_TOP: BannerPattern = BannerPatternRegistry["minecraft:stripe_top"]

  public val CREEPER: BannerPattern = BannerPatternRegistry["minecraft:creeper"]

  public val STRIPE_LEFT: BannerPattern = BannerPatternRegistry["minecraft:stripe_left"]

  public val TRIANGLES_BOTTOM: BannerPattern = BannerPatternRegistry["minecraft:triangles_bottom"]

  public val STRAIGHT_CROSS: BannerPattern = BannerPatternRegistry["minecraft:straight_cross"]
}
