// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.BannerPattern
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object BannerPatterns {
  public val BORDER: RegistryKey<BannerPattern> = createKey("minecraft:border")

  public val SQUARE_BOTTOM_RIGHT: RegistryKey<BannerPattern> =
      createKey("minecraft:square_bottom_right")

  public val STRIPE_RIGHT: RegistryKey<BannerPattern> = createKey("minecraft:stripe_right")

  public val FLOW: RegistryKey<BannerPattern> = createKey("minecraft:flow")

  public val RHOMBUS: RegistryKey<BannerPattern> = createKey("minecraft:rhombus")

  public val TRIANGLES_TOP: RegistryKey<BannerPattern> = createKey("minecraft:triangles_top")

  public val GRADIENT: RegistryKey<BannerPattern> = createKey("minecraft:gradient")

  public val GLOBE: RegistryKey<BannerPattern> = createKey("minecraft:globe")

  public val MOJANG: RegistryKey<BannerPattern> = createKey("minecraft:mojang")

  public val STRIPE_BOTTOM: RegistryKey<BannerPattern> = createKey("minecraft:stripe_bottom")

  public val STRIPE_MIDDLE: RegistryKey<BannerPattern> = createKey("minecraft:stripe_middle")

  public val FLOWER: RegistryKey<BannerPattern> = createKey("minecraft:flower")

  public val DIAGONAL_UP_RIGHT: RegistryKey<BannerPattern> =
      createKey("minecraft:diagonal_up_right")

  public val CIRCLE: RegistryKey<BannerPattern> = createKey("minecraft:circle")

  public val HALF_HORIZONTAL: RegistryKey<BannerPattern> = createKey("minecraft:half_horizontal")

  public val BRICKS: RegistryKey<BannerPattern> = createKey("minecraft:bricks")

  public val TRIANGLE_BOTTOM: RegistryKey<BannerPattern> = createKey("minecraft:triangle_bottom")

  public val CURLY_BORDER: RegistryKey<BannerPattern> = createKey("minecraft:curly_border")

  public val BASE: RegistryKey<BannerPattern> = createKey("minecraft:base")

  public val PIGLIN: RegistryKey<BannerPattern> = createKey("minecraft:piglin")

  public val STRIPE_CENTER: RegistryKey<BannerPattern> = createKey("minecraft:stripe_center")

  public val SQUARE_BOTTOM_LEFT: RegistryKey<BannerPattern> =
      createKey("minecraft:square_bottom_left")

  public val SQUARE_TOP_RIGHT: RegistryKey<BannerPattern> = createKey("minecraft:square_top_right")

  public val STRIPE_DOWNRIGHT: RegistryKey<BannerPattern> = createKey("minecraft:stripe_downright")

  public val GUSTER: RegistryKey<BannerPattern> = createKey("minecraft:guster")

  public val GRADIENT_UP: RegistryKey<BannerPattern> = createKey("minecraft:gradient_up")

  public val DIAGONAL_RIGHT: RegistryKey<BannerPattern> = createKey("minecraft:diagonal_right")

  public val HALF_VERTICAL_RIGHT: RegistryKey<BannerPattern> =
      createKey("minecraft:half_vertical_right")

  public val SMALL_STRIPES: RegistryKey<BannerPattern> = createKey("minecraft:small_stripes")

  public val CROSS: RegistryKey<BannerPattern> = createKey("minecraft:cross")

  public val DIAGONAL_LEFT: RegistryKey<BannerPattern> = createKey("minecraft:diagonal_left")

  public val SKULL: RegistryKey<BannerPattern> = createKey("minecraft:skull")

  public val STRIPE_DOWNLEFT: RegistryKey<BannerPattern> = createKey("minecraft:stripe_downleft")

  public val DIAGONAL_UP_LEFT: RegistryKey<BannerPattern> = createKey("minecraft:diagonal_up_left")

  public val HALF_VERTICAL: RegistryKey<BannerPattern> = createKey("minecraft:half_vertical")

  public val TRIANGLE_TOP: RegistryKey<BannerPattern> = createKey("minecraft:triangle_top")

  public val HALF_HORIZONTAL_BOTTOM: RegistryKey<BannerPattern> =
      createKey("minecraft:half_horizontal_bottom")

  public val SQUARE_TOP_LEFT: RegistryKey<BannerPattern> = createKey("minecraft:square_top_left")

  public val STRIPE_TOP: RegistryKey<BannerPattern> = createKey("minecraft:stripe_top")

  public val CREEPER: RegistryKey<BannerPattern> = createKey("minecraft:creeper")

  public val STRIPE_LEFT: RegistryKey<BannerPattern> = createKey("minecraft:stripe_left")

  public val TRIANGLES_BOTTOM: RegistryKey<BannerPattern> = createKey("minecraft:triangles_bottom")

  public val STRAIGHT_CROSS: RegistryKey<BannerPattern> = createKey("minecraft:straight_cross")
}
