// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.r2.BannerPattern
import ru.cherryngine.lib.minecraft.r2.Registries

public object BannerPatterns {
  public val BORDER: BannerPattern = Registries.bannerPattern["minecraft:border"]

  public val SQUARE_BOTTOM_RIGHT: BannerPattern =
      Registries.bannerPattern["minecraft:square_bottom_right"]

  public val STRIPE_RIGHT: BannerPattern = Registries.bannerPattern["minecraft:stripe_right"]

  public val FLOW: BannerPattern = Registries.bannerPattern["minecraft:flow"]

  public val RHOMBUS: BannerPattern = Registries.bannerPattern["minecraft:rhombus"]

  public val TRIANGLES_TOP: BannerPattern = Registries.bannerPattern["minecraft:triangles_top"]

  public val GRADIENT: BannerPattern = Registries.bannerPattern["minecraft:gradient"]

  public val GLOBE: BannerPattern = Registries.bannerPattern["minecraft:globe"]

  public val MOJANG: BannerPattern = Registries.bannerPattern["minecraft:mojang"]

  public val STRIPE_BOTTOM: BannerPattern = Registries.bannerPattern["minecraft:stripe_bottom"]

  public val STRIPE_MIDDLE: BannerPattern = Registries.bannerPattern["minecraft:stripe_middle"]

  public val FLOWER: BannerPattern = Registries.bannerPattern["minecraft:flower"]

  public val DIAGONAL_UP_RIGHT: BannerPattern = Registries.bannerPattern["minecraft:diagonal_up_right"]

  public val CIRCLE: BannerPattern = Registries.bannerPattern["minecraft:circle"]

  public val HALF_HORIZONTAL: BannerPattern = Registries.bannerPattern["minecraft:half_horizontal"]

  public val BRICKS: BannerPattern = Registries.bannerPattern["minecraft:bricks"]

  public val TRIANGLE_BOTTOM: BannerPattern = Registries.bannerPattern["minecraft:triangle_bottom"]

  public val CURLY_BORDER: BannerPattern = Registries.bannerPattern["minecraft:curly_border"]

  public val BASE: BannerPattern = Registries.bannerPattern["minecraft:base"]

  public val PIGLIN: BannerPattern = Registries.bannerPattern["minecraft:piglin"]

  public val STRIPE_CENTER: BannerPattern = Registries.bannerPattern["minecraft:stripe_center"]

  public val SQUARE_BOTTOM_LEFT: BannerPattern =
      Registries.bannerPattern["minecraft:square_bottom_left"]

  public val SQUARE_TOP_RIGHT: BannerPattern = Registries.bannerPattern["minecraft:square_top_right"]

  public val STRIPE_DOWNRIGHT: BannerPattern = Registries.bannerPattern["minecraft:stripe_downright"]

  public val GUSTER: BannerPattern = Registries.bannerPattern["minecraft:guster"]

  public val GRADIENT_UP: BannerPattern = Registries.bannerPattern["minecraft:gradient_up"]

  public val DIAGONAL_RIGHT: BannerPattern = Registries.bannerPattern["minecraft:diagonal_right"]

  public val HALF_VERTICAL_RIGHT: BannerPattern =
      Registries.bannerPattern["minecraft:half_vertical_right"]

  public val SMALL_STRIPES: BannerPattern = Registries.bannerPattern["minecraft:small_stripes"]

  public val CROSS: BannerPattern = Registries.bannerPattern["minecraft:cross"]

  public val DIAGONAL_LEFT: BannerPattern = Registries.bannerPattern["minecraft:diagonal_left"]

  public val SKULL: BannerPattern = Registries.bannerPattern["minecraft:skull"]

  public val STRIPE_DOWNLEFT: BannerPattern = Registries.bannerPattern["minecraft:stripe_downleft"]

  public val DIAGONAL_UP_LEFT: BannerPattern = Registries.bannerPattern["minecraft:diagonal_up_left"]

  public val HALF_VERTICAL: BannerPattern = Registries.bannerPattern["minecraft:half_vertical"]

  public val TRIANGLE_TOP: BannerPattern = Registries.bannerPattern["minecraft:triangle_top"]

  public val HALF_HORIZONTAL_BOTTOM: BannerPattern =
      Registries.bannerPattern["minecraft:half_horizontal_bottom"]

  public val SQUARE_TOP_LEFT: BannerPattern = Registries.bannerPattern["minecraft:square_top_left"]

  public val STRIPE_TOP: BannerPattern = Registries.bannerPattern["minecraft:stripe_top"]

  public val CREEPER: BannerPattern = Registries.bannerPattern["minecraft:creeper"]

  public val STRIPE_LEFT: BannerPattern = Registries.bannerPattern["minecraft:stripe_left"]

  public val TRIANGLES_BOTTOM: BannerPattern = Registries.bannerPattern["minecraft:triangles_bottom"]

  public val STRAIGHT_CROSS: BannerPattern = Registries.bannerPattern["minecraft:straight_cross"]
}
