// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.Biome
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object Biomes {
  public val BAMBOO_JUNGLE: RegistryKey<Biome> = createKey("minecraft:bamboo_jungle")

  public val JUNGLE: RegistryKey<Biome> = createKey("minecraft:jungle")

  public val LUKEWARM_OCEAN: RegistryKey<Biome> = createKey("minecraft:lukewarm_ocean")

  public val WINDSWEPT_SAVANNA: RegistryKey<Biome> = createKey("minecraft:windswept_savanna")

  public val MANGROVE_SWAMP: RegistryKey<Biome> = createKey("minecraft:mangrove_swamp")

  public val OCEAN: RegistryKey<Biome> = createKey("minecraft:ocean")

  public val STONY_SHORE: RegistryKey<Biome> = createKey("minecraft:stony_shore")

  public val END_HIGHLANDS: RegistryKey<Biome> = createKey("minecraft:end_highlands")

  public val FROZEN_RIVER: RegistryKey<Biome> = createKey("minecraft:frozen_river")

  public val DEEP_FROZEN_OCEAN: RegistryKey<Biome> = createKey("minecraft:deep_frozen_ocean")

  public val DEEP_COLD_OCEAN: RegistryKey<Biome> = createKey("minecraft:deep_cold_ocean")

  public val TAIGA: RegistryKey<Biome> = createKey("minecraft:taiga")

  public val DRIPSTONE_CAVES: RegistryKey<Biome> = createKey("minecraft:dripstone_caves")

  public val CHERRY_GROVE: RegistryKey<Biome> = createKey("minecraft:cherry_grove")

  public val FLOWER_FOREST: RegistryKey<Biome> = createKey("minecraft:flower_forest")

  public val WINDSWEPT_FOREST: RegistryKey<Biome> = createKey("minecraft:windswept_forest")

  public val SAVANNA_PLATEAU: RegistryKey<Biome> = createKey("minecraft:savanna_plateau")

  public val WARPED_FOREST: RegistryKey<Biome> = createKey("minecraft:warped_forest")

  public val WINDSWEPT_GRAVELLY_HILLS: RegistryKey<Biome> =
      createKey("minecraft:windswept_gravelly_hills")

  public val WINDSWEPT_HILLS: RegistryKey<Biome> = createKey("minecraft:windswept_hills")

  public val DARK_FOREST: RegistryKey<Biome> = createKey("minecraft:dark_forest")

  public val RIVER: RegistryKey<Biome> = createKey("minecraft:river")

  public val SAVANNA: RegistryKey<Biome> = createKey("minecraft:savanna")

  public val FROZEN_PEAKS: RegistryKey<Biome> = createKey("minecraft:frozen_peaks")

  public val SOUL_SAND_VALLEY: RegistryKey<Biome> = createKey("minecraft:soul_sand_valley")

  public val WOODED_BADLANDS: RegistryKey<Biome> = createKey("minecraft:wooded_badlands")

  public val END_BARRENS: RegistryKey<Biome> = createKey("minecraft:end_barrens")

  public val BADLANDS: RegistryKey<Biome> = createKey("minecraft:badlands")

  public val LUSH_CAVES: RegistryKey<Biome> = createKey("minecraft:lush_caves")

  public val SNOWY_PLAINS: RegistryKey<Biome> = createKey("minecraft:snowy_plains")

  public val THE_VOID: RegistryKey<Biome> = createKey("minecraft:the_void")

  public val BASALT_DELTAS: RegistryKey<Biome> = createKey("minecraft:basalt_deltas")

  public val DESERT: RegistryKey<Biome> = createKey("minecraft:desert")

  public val GROVE: RegistryKey<Biome> = createKey("minecraft:grove")

  public val BEACH: RegistryKey<Biome> = createKey("minecraft:beach")

  public val SNOWY_TAIGA: RegistryKey<Biome> = createKey("minecraft:snowy_taiga")

  public val THE_END: RegistryKey<Biome> = createKey("minecraft:the_end")

  public val PALE_GARDEN: RegistryKey<Biome> = createKey("minecraft:pale_garden")

  public val SNOWY_SLOPES: RegistryKey<Biome> = createKey("minecraft:snowy_slopes")

  public val DEEP_OCEAN: RegistryKey<Biome> = createKey("minecraft:deep_ocean")

  public val MEADOW: RegistryKey<Biome> = createKey("minecraft:meadow")

  public val SMALL_END_ISLANDS: RegistryKey<Biome> = createKey("minecraft:small_end_islands")

  public val SWAMP: RegistryKey<Biome> = createKey("minecraft:swamp")

  public val DEEP_LUKEWARM_OCEAN: RegistryKey<Biome> = createKey("minecraft:deep_lukewarm_ocean")

  public val COLD_OCEAN: RegistryKey<Biome> = createKey("minecraft:cold_ocean")

  public val STONY_PEAKS: RegistryKey<Biome> = createKey("minecraft:stony_peaks")

  public val CRIMSON_FOREST: RegistryKey<Biome> = createKey("minecraft:crimson_forest")

  public val END_MIDLANDS: RegistryKey<Biome> = createKey("minecraft:end_midlands")

  public val ERODED_BADLANDS: RegistryKey<Biome> = createKey("minecraft:eroded_badlands")

  public val SPARSE_JUNGLE: RegistryKey<Biome> = createKey("minecraft:sparse_jungle")

  public val DEEP_DARK: RegistryKey<Biome> = createKey("minecraft:deep_dark")

  public val OLD_GROWTH_BIRCH_FOREST: RegistryKey<Biome> =
      createKey("minecraft:old_growth_birch_forest")

  public val BIRCH_FOREST: RegistryKey<Biome> = createKey("minecraft:birch_forest")

  public val NETHER_WASTES: RegistryKey<Biome> = createKey("minecraft:nether_wastes")

  public val SUNFLOWER_PLAINS: RegistryKey<Biome> = createKey("minecraft:sunflower_plains")

  public val WARM_OCEAN: RegistryKey<Biome> = createKey("minecraft:warm_ocean")

  public val ICE_SPIKES: RegistryKey<Biome> = createKey("minecraft:ice_spikes")

  public val JAGGED_PEAKS: RegistryKey<Biome> = createKey("minecraft:jagged_peaks")

  public val PLAINS: RegistryKey<Biome> = createKey("minecraft:plains")

  public val MUSHROOM_FIELDS: RegistryKey<Biome> = createKey("minecraft:mushroom_fields")

  public val FOREST: RegistryKey<Biome> = createKey("minecraft:forest")

  public val FROZEN_OCEAN: RegistryKey<Biome> = createKey("minecraft:frozen_ocean")

  public val OLD_GROWTH_SPRUCE_TAIGA: RegistryKey<Biome> =
      createKey("minecraft:old_growth_spruce_taiga")

  public val SNOWY_BEACH: RegistryKey<Biome> = createKey("minecraft:snowy_beach")

  public val OLD_GROWTH_PINE_TAIGA: RegistryKey<Biome> =
      createKey("minecraft:old_growth_pine_taiga")
}
