// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.CatVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object CatVariants {
  public val BLACK: Key<CatVariant> = fromKey("minecraft:black")

  public val ALL_BLACK: Key<CatVariant> = fromKey("minecraft:all_black")

  public val CALICO: Key<CatVariant> = fromKey("minecraft:calico")

  public val JELLIE: Key<CatVariant> = fromKey("minecraft:jellie")

  public val TABBY: Key<CatVariant> = fromKey("minecraft:tabby")

  public val RAGDOLL: Key<CatVariant> = fromKey("minecraft:ragdoll")

  public val SIAMESE: Key<CatVariant> = fromKey("minecraft:siamese")

  public val PERSIAN: Key<CatVariant> = fromKey("minecraft:persian")

  public val BRITISH_SHORTHAIR: Key<CatVariant> = fromKey("minecraft:british_shorthair")

  public val RED: Key<CatVariant> = fromKey("minecraft:red")

  public val WHITE: Key<CatVariant> = fromKey("minecraft:white")
}
