// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.CatVariant
import ru.cherryngine.lib.minecraft.registry.registries.CatVariantRegistry

public object CatVariants {
  public val BLACK: CatVariant = CatVariantRegistry["minecraft:black"]

  public val ALL_BLACK: CatVariant = CatVariantRegistry["minecraft:all_black"]

  public val CALICO: CatVariant = CatVariantRegistry["minecraft:calico"]

  public val JELLIE: CatVariant = CatVariantRegistry["minecraft:jellie"]

  public val TABBY: CatVariant = CatVariantRegistry["minecraft:tabby"]

  public val RAGDOLL: CatVariant = CatVariantRegistry["minecraft:ragdoll"]

  public val SIAMESE: CatVariant = CatVariantRegistry["minecraft:siamese"]

  public val PERSIAN: CatVariant = CatVariantRegistry["minecraft:persian"]

  public val BRITISH_SHORTHAIR: CatVariant = CatVariantRegistry["minecraft:british_shorthair"]

  public val RED: CatVariant = CatVariantRegistry["minecraft:red"]

  public val WHITE: CatVariant = CatVariantRegistry["minecraft:white"]
}
