// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.CatVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object CatVariants {
  public val BLACK: RegistryKey<CatVariant> = createKey("minecraft:black")

  public val ALL_BLACK: RegistryKey<CatVariant> = createKey("minecraft:all_black")

  public val CALICO: RegistryKey<CatVariant> = createKey("minecraft:calico")

  public val JELLIE: RegistryKey<CatVariant> = createKey("minecraft:jellie")

  public val TABBY: RegistryKey<CatVariant> = createKey("minecraft:tabby")

  public val RAGDOLL: RegistryKey<CatVariant> = createKey("minecraft:ragdoll")

  public val SIAMESE: RegistryKey<CatVariant> = createKey("minecraft:siamese")

  public val PERSIAN: RegistryKey<CatVariant> = createKey("minecraft:persian")

  public val BRITISH_SHORTHAIR: RegistryKey<CatVariant> = createKey("minecraft:british_shorthair")

  public val RED: RegistryKey<CatVariant> = createKey("minecraft:red")

  public val WHITE: RegistryKey<CatVariant> = createKey("minecraft:white")
}
