// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.ChatType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object ChatTypes {
  public val EMOTE_COMMAND: RegistryKey<ChatType> = createKey("minecraft:emote_command")

  public val TEAM_MSG_COMMAND_INCOMING: RegistryKey<ChatType> =
      createKey("minecraft:team_msg_command_incoming")

  public val TEAM_MSG_COMMAND_OUTGOING: RegistryKey<ChatType> =
      createKey("minecraft:team_msg_command_outgoing")

  public val CHAT: RegistryKey<ChatType> = createKey("minecraft:chat")

  public val MSG_COMMAND_INCOMING: RegistryKey<ChatType> =
      createKey("minecraft:msg_command_incoming")

  public val MSG_COMMAND_OUTGOING: RegistryKey<ChatType> =
      createKey("minecraft:msg_command_outgoing")

  public val SAY_COMMAND: RegistryKey<ChatType> = createKey("minecraft:say_command")
}
