// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.ChatType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object ChatTypes {
  public val EMOTE_COMMAND: Key<ChatType> = fromKey("minecraft:emote_command")

  public val TEAM_MSG_COMMAND_INCOMING: Key<ChatType> =
      fromKey("minecraft:team_msg_command_incoming")

  public val TEAM_MSG_COMMAND_OUTGOING: Key<ChatType> =
      fromKey("minecraft:team_msg_command_outgoing")

  public val CHAT: Key<ChatType> = fromKey("minecraft:chat")

  public val MSG_COMMAND_INCOMING: Key<ChatType> = fromKey("minecraft:msg_command_incoming")

  public val MSG_COMMAND_OUTGOING: Key<ChatType> = fromKey("minecraft:msg_command_outgoing")

  public val SAY_COMMAND: Key<ChatType> = fromKey("minecraft:say_command")
}
