// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.ChickenVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object ChickenVariants {
  public val WARM: Key<ChickenVariant> = fromKey("minecraft:warm")

  public val COLD: Key<ChickenVariant> = fromKey("minecraft:cold")

  public val TEMPERATE: Key<ChickenVariant> = fromKey("minecraft:temperate")
}
