// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.ChickenVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object ChickenVariants {
  public val WARM: RegistryKey<ChickenVariant> = createKey("minecraft:warm")

  public val COLD: RegistryKey<ChickenVariant> = createKey("minecraft:cold")

  public val TEMPERATE: RegistryKey<ChickenVariant> = createKey("minecraft:temperate")
}
