// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.ChickenVariant
import ru.cherryngine.lib.minecraft.registry.registries.ChickenVariantRegistry

public object ChickenVariants {
  public val WARM: ChickenVariant = ChickenVariantRegistry["minecraft:warm"]

  public val COLD: ChickenVariant = ChickenVariantRegistry["minecraft:cold"]

  public val TEMPERATE: ChickenVariant = ChickenVariantRegistry["minecraft:temperate"]
}
