// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.CowVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object CowVariants {
  public val WARM: Key<CowVariant> = fromKey("minecraft:warm")

  public val COLD: Key<CowVariant> = fromKey("minecraft:cold")

  public val TEMPERATE: Key<CowVariant> = fromKey("minecraft:temperate")
}
