// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.CowVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object CowVariants {
  public val WARM: RegistryKey<CowVariant> = createKey("minecraft:warm")

  public val COLD: RegistryKey<CowVariant> = createKey("minecraft:cold")

  public val TEMPERATE: RegistryKey<CowVariant> = createKey("minecraft:temperate")
}
