// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.CowVariant
import ru.cherryngine.lib.minecraft.registry.registries.CowVariantRegistry

public object CowVariants {
  public val WARM: CowVariant = CowVariantRegistry["minecraft:warm"]

  public val COLD: CowVariant = CowVariantRegistry["minecraft:cold"]

  public val TEMPERATE: CowVariant = CowVariantRegistry["minecraft:temperate"]
}
