// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.DamageType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object DamageTypes {
  public val WITHER: RegistryKey<DamageType> = createKey("minecraft:wither")

  public val WITHER_SKULL: RegistryKey<DamageType> = createKey("minecraft:wither_skull")

  public val MACE_SMASH: RegistryKey<DamageType> = createKey("minecraft:mace_smash")

  public val TRIDENT: RegistryKey<DamageType> = createKey("minecraft:trident")

  public val ON_FIRE: RegistryKey<DamageType> = createKey("minecraft:on_fire")

  public val CAMPFIRE: RegistryKey<DamageType> = createKey("minecraft:campfire")

  public val FALLING_STALACTITE: RegistryKey<DamageType> = createKey("minecraft:falling_stalactite")

  public val FIREBALL: RegistryKey<DamageType> = createKey("minecraft:fireball")

  public val SPIT: RegistryKey<DamageType> = createKey("minecraft:spit")

  public val STING: RegistryKey<DamageType> = createKey("minecraft:sting")

  public val SPEAR: RegistryKey<DamageType> = createKey("minecraft:spear")

  public val IN_FIRE: RegistryKey<DamageType> = createKey("minecraft:in_fire")

  public val ARROW: RegistryKey<DamageType> = createKey("minecraft:arrow")

  public val HOT_FLOOR: RegistryKey<DamageType> = createKey("minecraft:hot_floor")

  public val DROWN: RegistryKey<DamageType> = createKey("minecraft:drown")

  public val GENERIC_KILL: RegistryKey<DamageType> = createKey("minecraft:generic_kill")

  public val DRAGON_BREATH: RegistryKey<DamageType> = createKey("minecraft:dragon_breath")

  public val LAVA: RegistryKey<DamageType> = createKey("minecraft:lava")

  public val FLY_INTO_WALL: RegistryKey<DamageType> = createKey("minecraft:fly_into_wall")

  public val PLAYER_ATTACK: RegistryKey<DamageType> = createKey("minecraft:player_attack")

  public val FREEZE: RegistryKey<DamageType> = createKey("minecraft:freeze")

  public val FALLING_ANVIL: RegistryKey<DamageType> = createKey("minecraft:falling_anvil")

  public val SWEET_BERRY_BUSH: RegistryKey<DamageType> = createKey("minecraft:sweet_berry_bush")

  public val FIREWORKS: RegistryKey<DamageType> = createKey("minecraft:fireworks")

  public val STALAGMITE: RegistryKey<DamageType> = createKey("minecraft:stalagmite")

  public val GENERIC: RegistryKey<DamageType> = createKey("minecraft:generic")

  public val SONIC_BOOM: RegistryKey<DamageType> = createKey("minecraft:sonic_boom")

  public val DRY_OUT: RegistryKey<DamageType> = createKey("minecraft:dry_out")

  public val ENDER_PEARL: RegistryKey<DamageType> = createKey("minecraft:ender_pearl")

  public val FALL: RegistryKey<DamageType> = createKey("minecraft:fall")

  public val MOB_ATTACK: RegistryKey<DamageType> = createKey("minecraft:mob_attack")

  public val MOB_PROJECTILE: RegistryKey<DamageType> = createKey("minecraft:mob_projectile")

  public val THROWN: RegistryKey<DamageType> = createKey("minecraft:thrown")

  public val FALLING_BLOCK: RegistryKey<DamageType> = createKey("minecraft:falling_block")

  public val WIND_CHARGE: RegistryKey<DamageType> = createKey("minecraft:wind_charge")

  public val PLAYER_EXPLOSION: RegistryKey<DamageType> = createKey("minecraft:player_explosion")

  public val UNATTRIBUTED_FIREBALL: RegistryKey<DamageType> =
      createKey("minecraft:unattributed_fireball")

  public val IN_WALL: RegistryKey<DamageType> = createKey("minecraft:in_wall")

  public val STARVE: RegistryKey<DamageType> = createKey("minecraft:starve")

  public val MOB_ATTACK_NO_AGGRO: RegistryKey<DamageType> =
      createKey("minecraft:mob_attack_no_aggro")

  public val OUTSIDE_BORDER: RegistryKey<DamageType> = createKey("minecraft:outside_border")

  public val LIGHTNING_BOLT: RegistryKey<DamageType> = createKey("minecraft:lightning_bolt")

  public val OUT_OF_WORLD: RegistryKey<DamageType> = createKey("minecraft:out_of_world")

  public val MAGIC: RegistryKey<DamageType> = createKey("minecraft:magic")

  public val EXPLOSION: RegistryKey<DamageType> = createKey("minecraft:explosion")

  public val BAD_RESPAWN_POINT: RegistryKey<DamageType> = createKey("minecraft:bad_respawn_point")

  public val THORNS: RegistryKey<DamageType> = createKey("minecraft:thorns")

  public val INDIRECT_MAGIC: RegistryKey<DamageType> = createKey("minecraft:indirect_magic")

  public val CRAMMING: RegistryKey<DamageType> = createKey("minecraft:cramming")

  public val CACTUS: RegistryKey<DamageType> = createKey("minecraft:cactus")
}
