// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.DamageType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object DamageTypes {
  public val WITHER: Key<DamageType> = fromKey("minecraft:wither")

  public val WITHER_SKULL: Key<DamageType> = fromKey("minecraft:wither_skull")

  public val MACE_SMASH: Key<DamageType> = fromKey("minecraft:mace_smash")

  public val TRIDENT: Key<DamageType> = fromKey("minecraft:trident")

  public val ON_FIRE: Key<DamageType> = fromKey("minecraft:on_fire")

  public val CAMPFIRE: Key<DamageType> = fromKey("minecraft:campfire")

  public val FALLING_STALACTITE: Key<DamageType> = fromKey("minecraft:falling_stalactite")

  public val FIREBALL: Key<DamageType> = fromKey("minecraft:fireball")

  public val SPIT: Key<DamageType> = fromKey("minecraft:spit")

  public val STING: Key<DamageType> = fromKey("minecraft:sting")

  public val SPEAR: Key<DamageType> = fromKey("minecraft:spear")

  public val IN_FIRE: Key<DamageType> = fromKey("minecraft:in_fire")

  public val ARROW: Key<DamageType> = fromKey("minecraft:arrow")

  public val HOT_FLOOR: Key<DamageType> = fromKey("minecraft:hot_floor")

  public val DROWN: Key<DamageType> = fromKey("minecraft:drown")

  public val GENERIC_KILL: Key<DamageType> = fromKey("minecraft:generic_kill")

  public val DRAGON_BREATH: Key<DamageType> = fromKey("minecraft:dragon_breath")

  public val LAVA: Key<DamageType> = fromKey("minecraft:lava")

  public val FLY_INTO_WALL: Key<DamageType> = fromKey("minecraft:fly_into_wall")

  public val PLAYER_ATTACK: Key<DamageType> = fromKey("minecraft:player_attack")

  public val FREEZE: Key<DamageType> = fromKey("minecraft:freeze")

  public val FALLING_ANVIL: Key<DamageType> = fromKey("minecraft:falling_anvil")

  public val SWEET_BERRY_BUSH: Key<DamageType> = fromKey("minecraft:sweet_berry_bush")

  public val FIREWORKS: Key<DamageType> = fromKey("minecraft:fireworks")

  public val STALAGMITE: Key<DamageType> = fromKey("minecraft:stalagmite")

  public val GENERIC: Key<DamageType> = fromKey("minecraft:generic")

  public val SONIC_BOOM: Key<DamageType> = fromKey("minecraft:sonic_boom")

  public val DRY_OUT: Key<DamageType> = fromKey("minecraft:dry_out")

  public val ENDER_PEARL: Key<DamageType> = fromKey("minecraft:ender_pearl")

  public val FALL: Key<DamageType> = fromKey("minecraft:fall")

  public val MOB_ATTACK: Key<DamageType> = fromKey("minecraft:mob_attack")

  public val MOB_PROJECTILE: Key<DamageType> = fromKey("minecraft:mob_projectile")

  public val THROWN: Key<DamageType> = fromKey("minecraft:thrown")

  public val FALLING_BLOCK: Key<DamageType> = fromKey("minecraft:falling_block")

  public val WIND_CHARGE: Key<DamageType> = fromKey("minecraft:wind_charge")

  public val PLAYER_EXPLOSION: Key<DamageType> = fromKey("minecraft:player_explosion")

  public val UNATTRIBUTED_FIREBALL: Key<DamageType> = fromKey("minecraft:unattributed_fireball")

  public val IN_WALL: Key<DamageType> = fromKey("minecraft:in_wall")

  public val STARVE: Key<DamageType> = fromKey("minecraft:starve")

  public val MOB_ATTACK_NO_AGGRO: Key<DamageType> = fromKey("minecraft:mob_attack_no_aggro")

  public val OUTSIDE_BORDER: Key<DamageType> = fromKey("minecraft:outside_border")

  public val LIGHTNING_BOLT: Key<DamageType> = fromKey("minecraft:lightning_bolt")

  public val OUT_OF_WORLD: Key<DamageType> = fromKey("minecraft:out_of_world")

  public val MAGIC: Key<DamageType> = fromKey("minecraft:magic")

  public val EXPLOSION: Key<DamageType> = fromKey("minecraft:explosion")

  public val BAD_RESPAWN_POINT: Key<DamageType> = fromKey("minecraft:bad_respawn_point")

  public val THORNS: Key<DamageType> = fromKey("minecraft:thorns")

  public val INDIRECT_MAGIC: Key<DamageType> = fromKey("minecraft:indirect_magic")

  public val CRAMMING: Key<DamageType> = fromKey("minecraft:cramming")

  public val CACTUS: Key<DamageType> = fromKey("minecraft:cactus")
}
