// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.DamageType
import ru.cherryngine.lib.minecraft.registry.registries.DamageTypeRegistry

public object DamageTypes {
  public val WITHER: DamageType = DamageTypeRegistry["minecraft:wither"]

  public val WITHER_SKULL: DamageType = DamageTypeRegistry["minecraft:wither_skull"]

  public val MACE_SMASH: DamageType = DamageTypeRegistry["minecraft:mace_smash"]

  public val TRIDENT: DamageType = DamageTypeRegistry["minecraft:trident"]

  public val ON_FIRE: DamageType = DamageTypeRegistry["minecraft:on_fire"]

  public val CAMPFIRE: DamageType = DamageTypeRegistry["minecraft:campfire"]

  public val FALLING_STALACTITE: DamageType = DamageTypeRegistry["minecraft:falling_stalactite"]

  public val FIREBALL: DamageType = DamageTypeRegistry["minecraft:fireball"]

  public val SPIT: DamageType = DamageTypeRegistry["minecraft:spit"]

  public val STING: DamageType = DamageTypeRegistry["minecraft:sting"]

  public val IN_FIRE: DamageType = DamageTypeRegistry["minecraft:in_fire"]

  public val ARROW: DamageType = DamageTypeRegistry["minecraft:arrow"]

  public val HOT_FLOOR: DamageType = DamageTypeRegistry["minecraft:hot_floor"]

  public val DROWN: DamageType = DamageTypeRegistry["minecraft:drown"]

  public val GENERIC_KILL: DamageType = DamageTypeRegistry["minecraft:generic_kill"]

  public val DRAGON_BREATH: DamageType = DamageTypeRegistry["minecraft:dragon_breath"]

  public val LAVA: DamageType = DamageTypeRegistry["minecraft:lava"]

  public val FLY_INTO_WALL: DamageType = DamageTypeRegistry["minecraft:fly_into_wall"]

  public val PLAYER_ATTACK: DamageType = DamageTypeRegistry["minecraft:player_attack"]

  public val FREEZE: DamageType = DamageTypeRegistry["minecraft:freeze"]

  public val FALLING_ANVIL: DamageType = DamageTypeRegistry["minecraft:falling_anvil"]

  public val SWEET_BERRY_BUSH: DamageType = DamageTypeRegistry["minecraft:sweet_berry_bush"]

  public val FIREWORKS: DamageType = DamageTypeRegistry["minecraft:fireworks"]

  public val STALAGMITE: DamageType = DamageTypeRegistry["minecraft:stalagmite"]

  public val GENERIC: DamageType = DamageTypeRegistry["minecraft:generic"]

  public val SONIC_BOOM: DamageType = DamageTypeRegistry["minecraft:sonic_boom"]

  public val DRY_OUT: DamageType = DamageTypeRegistry["minecraft:dry_out"]

  public val ENDER_PEARL: DamageType = DamageTypeRegistry["minecraft:ender_pearl"]

  public val FALL: DamageType = DamageTypeRegistry["minecraft:fall"]

  public val MOB_ATTACK: DamageType = DamageTypeRegistry["minecraft:mob_attack"]

  public val MOB_PROJECTILE: DamageType = DamageTypeRegistry["minecraft:mob_projectile"]

  public val THROWN: DamageType = DamageTypeRegistry["minecraft:thrown"]

  public val FALLING_BLOCK: DamageType = DamageTypeRegistry["minecraft:falling_block"]

  public val WIND_CHARGE: DamageType = DamageTypeRegistry["minecraft:wind_charge"]

  public val PLAYER_EXPLOSION: DamageType = DamageTypeRegistry["minecraft:player_explosion"]

  public val UNATTRIBUTED_FIREBALL: DamageType =
      DamageTypeRegistry["minecraft:unattributed_fireball"]

  public val IN_WALL: DamageType = DamageTypeRegistry["minecraft:in_wall"]

  public val STARVE: DamageType = DamageTypeRegistry["minecraft:starve"]

  public val MOB_ATTACK_NO_AGGRO: DamageType = DamageTypeRegistry["minecraft:mob_attack_no_aggro"]

  public val OUTSIDE_BORDER: DamageType = DamageTypeRegistry["minecraft:outside_border"]

  public val LIGHTNING_BOLT: DamageType = DamageTypeRegistry["minecraft:lightning_bolt"]

  public val OUT_OF_WORLD: DamageType = DamageTypeRegistry["minecraft:out_of_world"]

  public val MAGIC: DamageType = DamageTypeRegistry["minecraft:magic"]

  public val EXPLOSION: DamageType = DamageTypeRegistry["minecraft:explosion"]

  public val BAD_RESPAWN_POINT: DamageType = DamageTypeRegistry["minecraft:bad_respawn_point"]

  public val THORNS: DamageType = DamageTypeRegistry["minecraft:thorns"]

  public val INDIRECT_MAGIC: DamageType = DamageTypeRegistry["minecraft:indirect_magic"]

  public val CRAMMING: DamageType = DamageTypeRegistry["minecraft:cramming"]

  public val CACTUS: DamageType = DamageTypeRegistry["minecraft:cactus"]
}
