// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.dialog.Dialog
import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object Dialogs {
  public val QUICK_ACTIONS: RegistryKey<Dialog> = createKey("minecraft:quick_actions")

  public val CUSTOM_OPTIONS: RegistryKey<Dialog> = createKey("minecraft:custom_options")

  public val SERVER_LINKS: RegistryKey<Dialog> = createKey("minecraft:server_links")
}
