// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.DimensionType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object DimensionTypes {
  public val THE_END: Key<DimensionType> = fromKey("minecraft:the_end")

  public val OVERWORLD_CAVES: Key<DimensionType> = fromKey("minecraft:overworld_caves")

  public val THE_NETHER: Key<DimensionType> = fromKey("minecraft:the_nether")

  public val OVERWORLD: Key<DimensionType> = fromKey("minecraft:overworld")
}
