// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.DimensionType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object DimensionTypes {
  public val THE_END: RegistryKey<DimensionType> = createKey("minecraft:the_end")

  public val OVERWORLD_CAVES: RegistryKey<DimensionType> = createKey("minecraft:overworld_caves")

  public val THE_NETHER: RegistryKey<DimensionType> = createKey("minecraft:the_nether")

  public val OVERWORLD: RegistryKey<DimensionType> = createKey("minecraft:overworld")
}
