// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.EntityType
import ru.cherryngine.lib.minecraft.registry.registries.EntityTypeRegistry

public object EntityTypes {
  public val ACACIA_BOAT: EntityType = EntityTypeRegistry["minecraft:acacia_boat"]

  public val ACACIA_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:acacia_chest_boat"]

  public val ALLAY: EntityType = EntityTypeRegistry["minecraft:allay"]

  public val AREA_EFFECT_CLOUD: EntityType = EntityTypeRegistry["minecraft:area_effect_cloud"]

  public val ARMADILLO: EntityType = EntityTypeRegistry["minecraft:armadillo"]

  public val ARMOR_STAND: EntityType = EntityTypeRegistry["minecraft:armor_stand"]

  public val ARROW: EntityType = EntityTypeRegistry["minecraft:arrow"]

  public val AXOLOTL: EntityType = EntityTypeRegistry["minecraft:axolotl"]

  public val BAMBOO_CHEST_RAFT: EntityType = EntityTypeRegistry["minecraft:bamboo_chest_raft"]

  public val BAMBOO_RAFT: EntityType = EntityTypeRegistry["minecraft:bamboo_raft"]

  public val BAT: EntityType = EntityTypeRegistry["minecraft:bat"]

  public val BEE: EntityType = EntityTypeRegistry["minecraft:bee"]

  public val BIRCH_BOAT: EntityType = EntityTypeRegistry["minecraft:birch_boat"]

  public val BIRCH_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:birch_chest_boat"]

  public val BLAZE: EntityType = EntityTypeRegistry["minecraft:blaze"]

  public val BLOCK_DISPLAY: EntityType = EntityTypeRegistry["minecraft:block_display"]

  public val BOGGED: EntityType = EntityTypeRegistry["minecraft:bogged"]

  public val BREEZE: EntityType = EntityTypeRegistry["minecraft:breeze"]

  public val BREEZE_WIND_CHARGE: EntityType = EntityTypeRegistry["minecraft:breeze_wind_charge"]

  public val CAMEL: EntityType = EntityTypeRegistry["minecraft:camel"]

  public val CAT: EntityType = EntityTypeRegistry["minecraft:cat"]

  public val CAVE_SPIDER: EntityType = EntityTypeRegistry["minecraft:cave_spider"]

  public val CHERRY_BOAT: EntityType = EntityTypeRegistry["minecraft:cherry_boat"]

  public val CHERRY_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:cherry_chest_boat"]

  public val CHEST_MINECART: EntityType = EntityTypeRegistry["minecraft:chest_minecart"]

  public val CHICKEN: EntityType = EntityTypeRegistry["minecraft:chicken"]

  public val COD: EntityType = EntityTypeRegistry["minecraft:cod"]

  public val COPPER_GOLEM: EntityType = EntityTypeRegistry["minecraft:copper_golem"]

  public val COMMAND_BLOCK_MINECART: EntityType =
      EntityTypeRegistry["minecraft:command_block_minecart"]

  public val COW: EntityType = EntityTypeRegistry["minecraft:cow"]

  public val CREAKING: EntityType = EntityTypeRegistry["minecraft:creaking"]

  public val CREEPER: EntityType = EntityTypeRegistry["minecraft:creeper"]

  public val DARK_OAK_BOAT: EntityType = EntityTypeRegistry["minecraft:dark_oak_boat"]

  public val DARK_OAK_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:dark_oak_chest_boat"]

  public val DOLPHIN: EntityType = EntityTypeRegistry["minecraft:dolphin"]

  public val DONKEY: EntityType = EntityTypeRegistry["minecraft:donkey"]

  public val DRAGON_FIREBALL: EntityType = EntityTypeRegistry["minecraft:dragon_fireball"]

  public val DROWNED: EntityType = EntityTypeRegistry["minecraft:drowned"]

  public val EGG: EntityType = EntityTypeRegistry["minecraft:egg"]

  public val ELDER_GUARDIAN: EntityType = EntityTypeRegistry["minecraft:elder_guardian"]

  public val ENDERMAN: EntityType = EntityTypeRegistry["minecraft:enderman"]

  public val ENDERMITE: EntityType = EntityTypeRegistry["minecraft:endermite"]

  public val ENDER_DRAGON: EntityType = EntityTypeRegistry["minecraft:ender_dragon"]

  public val ENDER_PEARL: EntityType = EntityTypeRegistry["minecraft:ender_pearl"]

  public val END_CRYSTAL: EntityType = EntityTypeRegistry["minecraft:end_crystal"]

  public val EVOKER: EntityType = EntityTypeRegistry["minecraft:evoker"]

  public val EVOKER_FANGS: EntityType = EntityTypeRegistry["minecraft:evoker_fangs"]

  public val EXPERIENCE_BOTTLE: EntityType = EntityTypeRegistry["minecraft:experience_bottle"]

  public val EXPERIENCE_ORB: EntityType = EntityTypeRegistry["minecraft:experience_orb"]

  public val EYE_OF_ENDER: EntityType = EntityTypeRegistry["minecraft:eye_of_ender"]

  public val FALLING_BLOCK: EntityType = EntityTypeRegistry["minecraft:falling_block"]

  public val FIREBALL: EntityType = EntityTypeRegistry["minecraft:fireball"]

  public val FIREWORK_ROCKET: EntityType = EntityTypeRegistry["minecraft:firework_rocket"]

  public val FOX: EntityType = EntityTypeRegistry["minecraft:fox"]

  public val FROG: EntityType = EntityTypeRegistry["minecraft:frog"]

  public val FURNACE_MINECART: EntityType = EntityTypeRegistry["minecraft:furnace_minecart"]

  public val GHAST: EntityType = EntityTypeRegistry["minecraft:ghast"]

  public val HAPPY_GHAST: EntityType = EntityTypeRegistry["minecraft:happy_ghast"]

  public val GIANT: EntityType = EntityTypeRegistry["minecraft:giant"]

  public val GLOW_ITEM_FRAME: EntityType = EntityTypeRegistry["minecraft:glow_item_frame"]

  public val GLOW_SQUID: EntityType = EntityTypeRegistry["minecraft:glow_squid"]

  public val GOAT: EntityType = EntityTypeRegistry["minecraft:goat"]

  public val GUARDIAN: EntityType = EntityTypeRegistry["minecraft:guardian"]

  public val HOGLIN: EntityType = EntityTypeRegistry["minecraft:hoglin"]

  public val HOPPER_MINECART: EntityType = EntityTypeRegistry["minecraft:hopper_minecart"]

  public val HORSE: EntityType = EntityTypeRegistry["minecraft:horse"]

  public val HUSK: EntityType = EntityTypeRegistry["minecraft:husk"]

  public val ILLUSIONER: EntityType = EntityTypeRegistry["minecraft:illusioner"]

  public val INTERACTION: EntityType = EntityTypeRegistry["minecraft:interaction"]

  public val IRON_GOLEM: EntityType = EntityTypeRegistry["minecraft:iron_golem"]

  public val ITEM: EntityType = EntityTypeRegistry["minecraft:item"]

  public val ITEM_DISPLAY: EntityType = EntityTypeRegistry["minecraft:item_display"]

  public val ITEM_FRAME: EntityType = EntityTypeRegistry["minecraft:item_frame"]

  public val JUNGLE_BOAT: EntityType = EntityTypeRegistry["minecraft:jungle_boat"]

  public val JUNGLE_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:jungle_chest_boat"]

  public val LEASH_KNOT: EntityType = EntityTypeRegistry["minecraft:leash_knot"]

  public val LIGHTNING_BOLT: EntityType = EntityTypeRegistry["minecraft:lightning_bolt"]

  public val LLAMA: EntityType = EntityTypeRegistry["minecraft:llama"]

  public val LLAMA_SPIT: EntityType = EntityTypeRegistry["minecraft:llama_spit"]

  public val MAGMA_CUBE: EntityType = EntityTypeRegistry["minecraft:magma_cube"]

  public val MANGROVE_BOAT: EntityType = EntityTypeRegistry["minecraft:mangrove_boat"]

  public val MANGROVE_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:mangrove_chest_boat"]

  public val MANNEQUIN: EntityType = EntityTypeRegistry["minecraft:mannequin"]

  public val MARKER: EntityType = EntityTypeRegistry["minecraft:marker"]

  public val MINECART: EntityType = EntityTypeRegistry["minecraft:minecart"]

  public val MOOSHROOM: EntityType = EntityTypeRegistry["minecraft:mooshroom"]

  public val MULE: EntityType = EntityTypeRegistry["minecraft:mule"]

  public val OAK_BOAT: EntityType = EntityTypeRegistry["minecraft:oak_boat"]

  public val OAK_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:oak_chest_boat"]

  public val OCELOT: EntityType = EntityTypeRegistry["minecraft:ocelot"]

  public val OMINOUS_ITEM_SPAWNER: EntityType = EntityTypeRegistry["minecraft:ominous_item_spawner"]

  public val PAINTING: EntityType = EntityTypeRegistry["minecraft:painting"]

  public val PALE_OAK_BOAT: EntityType = EntityTypeRegistry["minecraft:pale_oak_boat"]

  public val PALE_OAK_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:pale_oak_chest_boat"]

  public val PANDA: EntityType = EntityTypeRegistry["minecraft:panda"]

  public val PARROT: EntityType = EntityTypeRegistry["minecraft:parrot"]

  public val PHANTOM: EntityType = EntityTypeRegistry["minecraft:phantom"]

  public val PIG: EntityType = EntityTypeRegistry["minecraft:pig"]

  public val PIGLIN: EntityType = EntityTypeRegistry["minecraft:piglin"]

  public val PIGLIN_BRUTE: EntityType = EntityTypeRegistry["minecraft:piglin_brute"]

  public val PILLAGER: EntityType = EntityTypeRegistry["minecraft:pillager"]

  public val POLAR_BEAR: EntityType = EntityTypeRegistry["minecraft:polar_bear"]

  public val SPLASH_POTION: EntityType = EntityTypeRegistry["minecraft:splash_potion"]

  public val LINGERING_POTION: EntityType = EntityTypeRegistry["minecraft:lingering_potion"]

  public val PUFFERFISH: EntityType = EntityTypeRegistry["minecraft:pufferfish"]

  public val RABBIT: EntityType = EntityTypeRegistry["minecraft:rabbit"]

  public val RAVAGER: EntityType = EntityTypeRegistry["minecraft:ravager"]

  public val SALMON: EntityType = EntityTypeRegistry["minecraft:salmon"]

  public val SHEEP: EntityType = EntityTypeRegistry["minecraft:sheep"]

  public val SHULKER: EntityType = EntityTypeRegistry["minecraft:shulker"]

  public val SHULKER_BULLET: EntityType = EntityTypeRegistry["minecraft:shulker_bullet"]

  public val SILVERFISH: EntityType = EntityTypeRegistry["minecraft:silverfish"]

  public val SKELETON: EntityType = EntityTypeRegistry["minecraft:skeleton"]

  public val SKELETON_HORSE: EntityType = EntityTypeRegistry["minecraft:skeleton_horse"]

  public val SLIME: EntityType = EntityTypeRegistry["minecraft:slime"]

  public val SMALL_FIREBALL: EntityType = EntityTypeRegistry["minecraft:small_fireball"]

  public val SNIFFER: EntityType = EntityTypeRegistry["minecraft:sniffer"]

  public val SNOWBALL: EntityType = EntityTypeRegistry["minecraft:snowball"]

  public val SNOW_GOLEM: EntityType = EntityTypeRegistry["minecraft:snow_golem"]

  public val SPAWNER_MINECART: EntityType = EntityTypeRegistry["minecraft:spawner_minecart"]

  public val SPECTRAL_ARROW: EntityType = EntityTypeRegistry["minecraft:spectral_arrow"]

  public val SPIDER: EntityType = EntityTypeRegistry["minecraft:spider"]

  public val SPRUCE_BOAT: EntityType = EntityTypeRegistry["minecraft:spruce_boat"]

  public val SPRUCE_CHEST_BOAT: EntityType = EntityTypeRegistry["minecraft:spruce_chest_boat"]

  public val SQUID: EntityType = EntityTypeRegistry["minecraft:squid"]

  public val STRAY: EntityType = EntityTypeRegistry["minecraft:stray"]

  public val STRIDER: EntityType = EntityTypeRegistry["minecraft:strider"]

  public val TADPOLE: EntityType = EntityTypeRegistry["minecraft:tadpole"]

  public val TEXT_DISPLAY: EntityType = EntityTypeRegistry["minecraft:text_display"]

  public val TNT: EntityType = EntityTypeRegistry["minecraft:tnt"]

  public val TNT_MINECART: EntityType = EntityTypeRegistry["minecraft:tnt_minecart"]

  public val TRADER_LLAMA: EntityType = EntityTypeRegistry["minecraft:trader_llama"]

  public val TRIDENT: EntityType = EntityTypeRegistry["minecraft:trident"]

  public val TROPICAL_FISH: EntityType = EntityTypeRegistry["minecraft:tropical_fish"]

  public val TURTLE: EntityType = EntityTypeRegistry["minecraft:turtle"]

  public val VEX: EntityType = EntityTypeRegistry["minecraft:vex"]

  public val VILLAGER: EntityType = EntityTypeRegistry["minecraft:villager"]

  public val VINDICATOR: EntityType = EntityTypeRegistry["minecraft:vindicator"]

  public val WANDERING_TRADER: EntityType = EntityTypeRegistry["minecraft:wandering_trader"]

  public val WARDEN: EntityType = EntityTypeRegistry["minecraft:warden"]

  public val WIND_CHARGE: EntityType = EntityTypeRegistry["minecraft:wind_charge"]

  public val WITCH: EntityType = EntityTypeRegistry["minecraft:witch"]

  public val WITHER: EntityType = EntityTypeRegistry["minecraft:wither"]

  public val WITHER_SKELETON: EntityType = EntityTypeRegistry["minecraft:wither_skeleton"]

  public val WITHER_SKULL: EntityType = EntityTypeRegistry["minecraft:wither_skull"]

  public val WOLF: EntityType = EntityTypeRegistry["minecraft:wolf"]

  public val ZOGLIN: EntityType = EntityTypeRegistry["minecraft:zoglin"]

  public val ZOMBIE: EntityType = EntityTypeRegistry["minecraft:zombie"]

  public val ZOMBIE_HORSE: EntityType = EntityTypeRegistry["minecraft:zombie_horse"]

  public val ZOMBIE_VILLAGER: EntityType = EntityTypeRegistry["minecraft:zombie_villager"]

  public val ZOMBIFIED_PIGLIN: EntityType = EntityTypeRegistry["minecraft:zombified_piglin"]

  public val PLAYER: EntityType = EntityTypeRegistry["minecraft:player"]

  public val FISHING_BOBBER: EntityType = EntityTypeRegistry["minecraft:fishing_bobber"]
}
