// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.EntityType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object EntityTypes {
  public val ACACIA_BOAT: Key<EntityType> = fromKey("minecraft:acacia_boat")

  public val ACACIA_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:acacia_chest_boat")

  public val ALLAY: Key<EntityType> = fromKey("minecraft:allay")

  public val AREA_EFFECT_CLOUD: Key<EntityType> = fromKey("minecraft:area_effect_cloud")

  public val ARMADILLO: Key<EntityType> = fromKey("minecraft:armadillo")

  public val ARMOR_STAND: Key<EntityType> = fromKey("minecraft:armor_stand")

  public val ARROW: Key<EntityType> = fromKey("minecraft:arrow")

  public val AXOLOTL: Key<EntityType> = fromKey("minecraft:axolotl")

  public val BAMBOO_CHEST_RAFT: Key<EntityType> = fromKey("minecraft:bamboo_chest_raft")

  public val BAMBOO_RAFT: Key<EntityType> = fromKey("minecraft:bamboo_raft")

  public val BAT: Key<EntityType> = fromKey("minecraft:bat")

  public val BEE: Key<EntityType> = fromKey("minecraft:bee")

  public val BIRCH_BOAT: Key<EntityType> = fromKey("minecraft:birch_boat")

  public val BIRCH_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:birch_chest_boat")

  public val BLAZE: Key<EntityType> = fromKey("minecraft:blaze")

  public val BLOCK_DISPLAY: Key<EntityType> = fromKey("minecraft:block_display")

  public val BOGGED: Key<EntityType> = fromKey("minecraft:bogged")

  public val BREEZE: Key<EntityType> = fromKey("minecraft:breeze")

  public val BREEZE_WIND_CHARGE: Key<EntityType> = fromKey("minecraft:breeze_wind_charge")

  public val CAMEL: Key<EntityType> = fromKey("minecraft:camel")

  public val CAMEL_HUSK: Key<EntityType> = fromKey("minecraft:camel_husk")

  public val CAT: Key<EntityType> = fromKey("minecraft:cat")

  public val CAVE_SPIDER: Key<EntityType> = fromKey("minecraft:cave_spider")

  public val CHERRY_BOAT: Key<EntityType> = fromKey("minecraft:cherry_boat")

  public val CHERRY_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:cherry_chest_boat")

  public val CHEST_MINECART: Key<EntityType> = fromKey("minecraft:chest_minecart")

  public val CHICKEN: Key<EntityType> = fromKey("minecraft:chicken")

  public val COD: Key<EntityType> = fromKey("minecraft:cod")

  public val COPPER_GOLEM: Key<EntityType> = fromKey("minecraft:copper_golem")

  public val COMMAND_BLOCK_MINECART: Key<EntityType> = fromKey("minecraft:command_block_minecart")

  public val COW: Key<EntityType> = fromKey("minecraft:cow")

  public val CREAKING: Key<EntityType> = fromKey("minecraft:creaking")

  public val CREEPER: Key<EntityType> = fromKey("minecraft:creeper")

  public val DARK_OAK_BOAT: Key<EntityType> = fromKey("minecraft:dark_oak_boat")

  public val DARK_OAK_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:dark_oak_chest_boat")

  public val DOLPHIN: Key<EntityType> = fromKey("minecraft:dolphin")

  public val DONKEY: Key<EntityType> = fromKey("minecraft:donkey")

  public val DRAGON_FIREBALL: Key<EntityType> = fromKey("minecraft:dragon_fireball")

  public val DROWNED: Key<EntityType> = fromKey("minecraft:drowned")

  public val EGG: Key<EntityType> = fromKey("minecraft:egg")

  public val ELDER_GUARDIAN: Key<EntityType> = fromKey("minecraft:elder_guardian")

  public val ENDERMAN: Key<EntityType> = fromKey("minecraft:enderman")

  public val ENDERMITE: Key<EntityType> = fromKey("minecraft:endermite")

  public val ENDER_DRAGON: Key<EntityType> = fromKey("minecraft:ender_dragon")

  public val ENDER_PEARL: Key<EntityType> = fromKey("minecraft:ender_pearl")

  public val END_CRYSTAL: Key<EntityType> = fromKey("minecraft:end_crystal")

  public val EVOKER: Key<EntityType> = fromKey("minecraft:evoker")

  public val EVOKER_FANGS: Key<EntityType> = fromKey("minecraft:evoker_fangs")

  public val EXPERIENCE_BOTTLE: Key<EntityType> = fromKey("minecraft:experience_bottle")

  public val EXPERIENCE_ORB: Key<EntityType> = fromKey("minecraft:experience_orb")

  public val EYE_OF_ENDER: Key<EntityType> = fromKey("minecraft:eye_of_ender")

  public val FALLING_BLOCK: Key<EntityType> = fromKey("minecraft:falling_block")

  public val FIREBALL: Key<EntityType> = fromKey("minecraft:fireball")

  public val FIREWORK_ROCKET: Key<EntityType> = fromKey("minecraft:firework_rocket")

  public val FOX: Key<EntityType> = fromKey("minecraft:fox")

  public val FROG: Key<EntityType> = fromKey("minecraft:frog")

  public val FURNACE_MINECART: Key<EntityType> = fromKey("minecraft:furnace_minecart")

  public val GHAST: Key<EntityType> = fromKey("minecraft:ghast")

  public val HAPPY_GHAST: Key<EntityType> = fromKey("minecraft:happy_ghast")

  public val GIANT: Key<EntityType> = fromKey("minecraft:giant")

  public val GLOW_ITEM_FRAME: Key<EntityType> = fromKey("minecraft:glow_item_frame")

  public val GLOW_SQUID: Key<EntityType> = fromKey("minecraft:glow_squid")

  public val GOAT: Key<EntityType> = fromKey("minecraft:goat")

  public val GUARDIAN: Key<EntityType> = fromKey("minecraft:guardian")

  public val HOGLIN: Key<EntityType> = fromKey("minecraft:hoglin")

  public val HOPPER_MINECART: Key<EntityType> = fromKey("minecraft:hopper_minecart")

  public val HORSE: Key<EntityType> = fromKey("minecraft:horse")

  public val HUSK: Key<EntityType> = fromKey("minecraft:husk")

  public val ILLUSIONER: Key<EntityType> = fromKey("minecraft:illusioner")

  public val INTERACTION: Key<EntityType> = fromKey("minecraft:interaction")

  public val IRON_GOLEM: Key<EntityType> = fromKey("minecraft:iron_golem")

  public val ITEM: Key<EntityType> = fromKey("minecraft:item")

  public val ITEM_DISPLAY: Key<EntityType> = fromKey("minecraft:item_display")

  public val ITEM_FRAME: Key<EntityType> = fromKey("minecraft:item_frame")

  public val JUNGLE_BOAT: Key<EntityType> = fromKey("minecraft:jungle_boat")

  public val JUNGLE_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:jungle_chest_boat")

  public val LEASH_KNOT: Key<EntityType> = fromKey("minecraft:leash_knot")

  public val LIGHTNING_BOLT: Key<EntityType> = fromKey("minecraft:lightning_bolt")

  public val LLAMA: Key<EntityType> = fromKey("minecraft:llama")

  public val LLAMA_SPIT: Key<EntityType> = fromKey("minecraft:llama_spit")

  public val MAGMA_CUBE: Key<EntityType> = fromKey("minecraft:magma_cube")

  public val MANGROVE_BOAT: Key<EntityType> = fromKey("minecraft:mangrove_boat")

  public val MANGROVE_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:mangrove_chest_boat")

  public val MANNEQUIN: Key<EntityType> = fromKey("minecraft:mannequin")

  public val MARKER: Key<EntityType> = fromKey("minecraft:marker")

  public val MINECART: Key<EntityType> = fromKey("minecraft:minecart")

  public val MOOSHROOM: Key<EntityType> = fromKey("minecraft:mooshroom")

  public val MULE: Key<EntityType> = fromKey("minecraft:mule")

  public val NAUTILUS: Key<EntityType> = fromKey("minecraft:nautilus")

  public val OAK_BOAT: Key<EntityType> = fromKey("minecraft:oak_boat")

  public val OAK_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:oak_chest_boat")

  public val OCELOT: Key<EntityType> = fromKey("minecraft:ocelot")

  public val OMINOUS_ITEM_SPAWNER: Key<EntityType> = fromKey("minecraft:ominous_item_spawner")

  public val PAINTING: Key<EntityType> = fromKey("minecraft:painting")

  public val PALE_OAK_BOAT: Key<EntityType> = fromKey("minecraft:pale_oak_boat")

  public val PALE_OAK_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:pale_oak_chest_boat")

  public val PANDA: Key<EntityType> = fromKey("minecraft:panda")

  public val PARCHED: Key<EntityType> = fromKey("minecraft:parched")

  public val PARROT: Key<EntityType> = fromKey("minecraft:parrot")

  public val PHANTOM: Key<EntityType> = fromKey("minecraft:phantom")

  public val PIG: Key<EntityType> = fromKey("minecraft:pig")

  public val PIGLIN: Key<EntityType> = fromKey("minecraft:piglin")

  public val PIGLIN_BRUTE: Key<EntityType> = fromKey("minecraft:piglin_brute")

  public val PILLAGER: Key<EntityType> = fromKey("minecraft:pillager")

  public val POLAR_BEAR: Key<EntityType> = fromKey("minecraft:polar_bear")

  public val SPLASH_POTION: Key<EntityType> = fromKey("minecraft:splash_potion")

  public val LINGERING_POTION: Key<EntityType> = fromKey("minecraft:lingering_potion")

  public val PUFFERFISH: Key<EntityType> = fromKey("minecraft:pufferfish")

  public val RABBIT: Key<EntityType> = fromKey("minecraft:rabbit")

  public val RAVAGER: Key<EntityType> = fromKey("minecraft:ravager")

  public val SALMON: Key<EntityType> = fromKey("minecraft:salmon")

  public val SHEEP: Key<EntityType> = fromKey("minecraft:sheep")

  public val SHULKER: Key<EntityType> = fromKey("minecraft:shulker")

  public val SHULKER_BULLET: Key<EntityType> = fromKey("minecraft:shulker_bullet")

  public val SILVERFISH: Key<EntityType> = fromKey("minecraft:silverfish")

  public val SKELETON: Key<EntityType> = fromKey("minecraft:skeleton")

  public val SKELETON_HORSE: Key<EntityType> = fromKey("minecraft:skeleton_horse")

  public val SLIME: Key<EntityType> = fromKey("minecraft:slime")

  public val SMALL_FIREBALL: Key<EntityType> = fromKey("minecraft:small_fireball")

  public val SNIFFER: Key<EntityType> = fromKey("minecraft:sniffer")

  public val SNOWBALL: Key<EntityType> = fromKey("minecraft:snowball")

  public val SNOW_GOLEM: Key<EntityType> = fromKey("minecraft:snow_golem")

  public val SPAWNER_MINECART: Key<EntityType> = fromKey("minecraft:spawner_minecart")

  public val SPECTRAL_ARROW: Key<EntityType> = fromKey("minecraft:spectral_arrow")

  public val SPIDER: Key<EntityType> = fromKey("minecraft:spider")

  public val SPRUCE_BOAT: Key<EntityType> = fromKey("minecraft:spruce_boat")

  public val SPRUCE_CHEST_BOAT: Key<EntityType> = fromKey("minecraft:spruce_chest_boat")

  public val SQUID: Key<EntityType> = fromKey("minecraft:squid")

  public val STRAY: Key<EntityType> = fromKey("minecraft:stray")

  public val STRIDER: Key<EntityType> = fromKey("minecraft:strider")

  public val TADPOLE: Key<EntityType> = fromKey("minecraft:tadpole")

  public val TEXT_DISPLAY: Key<EntityType> = fromKey("minecraft:text_display")

  public val TNT: Key<EntityType> = fromKey("minecraft:tnt")

  public val TNT_MINECART: Key<EntityType> = fromKey("minecraft:tnt_minecart")

  public val TRADER_LLAMA: Key<EntityType> = fromKey("minecraft:trader_llama")

  public val TRIDENT: Key<EntityType> = fromKey("minecraft:trident")

  public val TROPICAL_FISH: Key<EntityType> = fromKey("minecraft:tropical_fish")

  public val TURTLE: Key<EntityType> = fromKey("minecraft:turtle")

  public val VEX: Key<EntityType> = fromKey("minecraft:vex")

  public val VILLAGER: Key<EntityType> = fromKey("minecraft:villager")

  public val VINDICATOR: Key<EntityType> = fromKey("minecraft:vindicator")

  public val WANDERING_TRADER: Key<EntityType> = fromKey("minecraft:wandering_trader")

  public val WARDEN: Key<EntityType> = fromKey("minecraft:warden")

  public val WIND_CHARGE: Key<EntityType> = fromKey("minecraft:wind_charge")

  public val WITCH: Key<EntityType> = fromKey("minecraft:witch")

  public val WITHER: Key<EntityType> = fromKey("minecraft:wither")

  public val WITHER_SKELETON: Key<EntityType> = fromKey("minecraft:wither_skeleton")

  public val WITHER_SKULL: Key<EntityType> = fromKey("minecraft:wither_skull")

  public val WOLF: Key<EntityType> = fromKey("minecraft:wolf")

  public val ZOGLIN: Key<EntityType> = fromKey("minecraft:zoglin")

  public val ZOMBIE: Key<EntityType> = fromKey("minecraft:zombie")

  public val ZOMBIE_HORSE: Key<EntityType> = fromKey("minecraft:zombie_horse")

  public val ZOMBIE_NAUTILUS: Key<EntityType> = fromKey("minecraft:zombie_nautilus")

  public val ZOMBIE_VILLAGER: Key<EntityType> = fromKey("minecraft:zombie_villager")

  public val ZOMBIFIED_PIGLIN: Key<EntityType> = fromKey("minecraft:zombified_piglin")

  public val PLAYER: Key<EntityType> = fromKey("minecraft:player")

  public val FISHING_BOBBER: Key<EntityType> = fromKey("minecraft:fishing_bobber")
}
