// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.EntityType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object EntityTypes {
  public val ACACIA_BOAT: RegistryKey<EntityType> = createKey("minecraft:acacia_boat")

  public val ACACIA_CHEST_BOAT: RegistryKey<EntityType> = createKey("minecraft:acacia_chest_boat")

  public val ALLAY: RegistryKey<EntityType> = createKey("minecraft:allay")

  public val AREA_EFFECT_CLOUD: RegistryKey<EntityType> = createKey("minecraft:area_effect_cloud")

  public val ARMADILLO: RegistryKey<EntityType> = createKey("minecraft:armadillo")

  public val ARMOR_STAND: RegistryKey<EntityType> = createKey("minecraft:armor_stand")

  public val ARROW: RegistryKey<EntityType> = createKey("minecraft:arrow")

  public val AXOLOTL: RegistryKey<EntityType> = createKey("minecraft:axolotl")

  public val BAMBOO_CHEST_RAFT: RegistryKey<EntityType> = createKey("minecraft:bamboo_chest_raft")

  public val BAMBOO_RAFT: RegistryKey<EntityType> = createKey("minecraft:bamboo_raft")

  public val BAT: RegistryKey<EntityType> = createKey("minecraft:bat")

  public val BEE: RegistryKey<EntityType> = createKey("minecraft:bee")

  public val BIRCH_BOAT: RegistryKey<EntityType> = createKey("minecraft:birch_boat")

  public val BIRCH_CHEST_BOAT: RegistryKey<EntityType> = createKey("minecraft:birch_chest_boat")

  public val BLAZE: RegistryKey<EntityType> = createKey("minecraft:blaze")

  public val BLOCK_DISPLAY: RegistryKey<EntityType> = createKey("minecraft:block_display")

  public val BOGGED: RegistryKey<EntityType> = createKey("minecraft:bogged")

  public val BREEZE: RegistryKey<EntityType> = createKey("minecraft:breeze")

  public val BREEZE_WIND_CHARGE: RegistryKey<EntityType> = createKey("minecraft:breeze_wind_charge")

  public val CAMEL: RegistryKey<EntityType> = createKey("minecraft:camel")

  public val CAMEL_HUSK: RegistryKey<EntityType> = createKey("minecraft:camel_husk")

  public val CAT: RegistryKey<EntityType> = createKey("minecraft:cat")

  public val CAVE_SPIDER: RegistryKey<EntityType> = createKey("minecraft:cave_spider")

  public val CHERRY_BOAT: RegistryKey<EntityType> = createKey("minecraft:cherry_boat")

  public val CHERRY_CHEST_BOAT: RegistryKey<EntityType> = createKey("minecraft:cherry_chest_boat")

  public val CHEST_MINECART: RegistryKey<EntityType> = createKey("minecraft:chest_minecart")

  public val CHICKEN: RegistryKey<EntityType> = createKey("minecraft:chicken")

  public val COD: RegistryKey<EntityType> = createKey("minecraft:cod")

  public val COPPER_GOLEM: RegistryKey<EntityType> = createKey("minecraft:copper_golem")

  public val COMMAND_BLOCK_MINECART: RegistryKey<EntityType> =
      createKey("minecraft:command_block_minecart")

  public val COW: RegistryKey<EntityType> = createKey("minecraft:cow")

  public val CREAKING: RegistryKey<EntityType> = createKey("minecraft:creaking")

  public val CREEPER: RegistryKey<EntityType> = createKey("minecraft:creeper")

  public val DARK_OAK_BOAT: RegistryKey<EntityType> = createKey("minecraft:dark_oak_boat")

  public val DARK_OAK_CHEST_BOAT: RegistryKey<EntityType> =
      createKey("minecraft:dark_oak_chest_boat")

  public val DOLPHIN: RegistryKey<EntityType> = createKey("minecraft:dolphin")

  public val DONKEY: RegistryKey<EntityType> = createKey("minecraft:donkey")

  public val DRAGON_FIREBALL: RegistryKey<EntityType> = createKey("minecraft:dragon_fireball")

  public val DROWNED: RegistryKey<EntityType> = createKey("minecraft:drowned")

  public val EGG: RegistryKey<EntityType> = createKey("minecraft:egg")

  public val ELDER_GUARDIAN: RegistryKey<EntityType> = createKey("minecraft:elder_guardian")

  public val ENDERMAN: RegistryKey<EntityType> = createKey("minecraft:enderman")

  public val ENDERMITE: RegistryKey<EntityType> = createKey("minecraft:endermite")

  public val ENDER_DRAGON: RegistryKey<EntityType> = createKey("minecraft:ender_dragon")

  public val ENDER_PEARL: RegistryKey<EntityType> = createKey("minecraft:ender_pearl")

  public val END_CRYSTAL: RegistryKey<EntityType> = createKey("minecraft:end_crystal")

  public val EVOKER: RegistryKey<EntityType> = createKey("minecraft:evoker")

  public val EVOKER_FANGS: RegistryKey<EntityType> = createKey("minecraft:evoker_fangs")

  public val EXPERIENCE_BOTTLE: RegistryKey<EntityType> = createKey("minecraft:experience_bottle")

  public val EXPERIENCE_ORB: RegistryKey<EntityType> = createKey("minecraft:experience_orb")

  public val EYE_OF_ENDER: RegistryKey<EntityType> = createKey("minecraft:eye_of_ender")

  public val FALLING_BLOCK: RegistryKey<EntityType> = createKey("minecraft:falling_block")

  public val FIREBALL: RegistryKey<EntityType> = createKey("minecraft:fireball")

  public val FIREWORK_ROCKET: RegistryKey<EntityType> = createKey("minecraft:firework_rocket")

  public val FOX: RegistryKey<EntityType> = createKey("minecraft:fox")

  public val FROG: RegistryKey<EntityType> = createKey("minecraft:frog")

  public val FURNACE_MINECART: RegistryKey<EntityType> = createKey("minecraft:furnace_minecart")

  public val GHAST: RegistryKey<EntityType> = createKey("minecraft:ghast")

  public val HAPPY_GHAST: RegistryKey<EntityType> = createKey("minecraft:happy_ghast")

  public val GIANT: RegistryKey<EntityType> = createKey("minecraft:giant")

  public val GLOW_ITEM_FRAME: RegistryKey<EntityType> = createKey("minecraft:glow_item_frame")

  public val GLOW_SQUID: RegistryKey<EntityType> = createKey("minecraft:glow_squid")

  public val GOAT: RegistryKey<EntityType> = createKey("minecraft:goat")

  public val GUARDIAN: RegistryKey<EntityType> = createKey("minecraft:guardian")

  public val HOGLIN: RegistryKey<EntityType> = createKey("minecraft:hoglin")

  public val HOPPER_MINECART: RegistryKey<EntityType> = createKey("minecraft:hopper_minecart")

  public val HORSE: RegistryKey<EntityType> = createKey("minecraft:horse")

  public val HUSK: RegistryKey<EntityType> = createKey("minecraft:husk")

  public val ILLUSIONER: RegistryKey<EntityType> = createKey("minecraft:illusioner")

  public val INTERACTION: RegistryKey<EntityType> = createKey("minecraft:interaction")

  public val IRON_GOLEM: RegistryKey<EntityType> = createKey("minecraft:iron_golem")

  public val ITEM: RegistryKey<EntityType> = createKey("minecraft:item")

  public val ITEM_DISPLAY: RegistryKey<EntityType> = createKey("minecraft:item_display")

  public val ITEM_FRAME: RegistryKey<EntityType> = createKey("minecraft:item_frame")

  public val JUNGLE_BOAT: RegistryKey<EntityType> = createKey("minecraft:jungle_boat")

  public val JUNGLE_CHEST_BOAT: RegistryKey<EntityType> = createKey("minecraft:jungle_chest_boat")

  public val LEASH_KNOT: RegistryKey<EntityType> = createKey("minecraft:leash_knot")

  public val LIGHTNING_BOLT: RegistryKey<EntityType> = createKey("minecraft:lightning_bolt")

  public val LLAMA: RegistryKey<EntityType> = createKey("minecraft:llama")

  public val LLAMA_SPIT: RegistryKey<EntityType> = createKey("minecraft:llama_spit")

  public val MAGMA_CUBE: RegistryKey<EntityType> = createKey("minecraft:magma_cube")

  public val MANGROVE_BOAT: RegistryKey<EntityType> = createKey("minecraft:mangrove_boat")

  public val MANGROVE_CHEST_BOAT: RegistryKey<EntityType> =
      createKey("minecraft:mangrove_chest_boat")

  public val MANNEQUIN: RegistryKey<EntityType> = createKey("minecraft:mannequin")

  public val MARKER: RegistryKey<EntityType> = createKey("minecraft:marker")

  public val MINECART: RegistryKey<EntityType> = createKey("minecraft:minecart")

  public val MOOSHROOM: RegistryKey<EntityType> = createKey("minecraft:mooshroom")

  public val MULE: RegistryKey<EntityType> = createKey("minecraft:mule")

  public val NAUTILUS: RegistryKey<EntityType> = createKey("minecraft:nautilus")

  public val OAK_BOAT: RegistryKey<EntityType> = createKey("minecraft:oak_boat")

  public val OAK_CHEST_BOAT: RegistryKey<EntityType> = createKey("minecraft:oak_chest_boat")

  public val OCELOT: RegistryKey<EntityType> = createKey("minecraft:ocelot")

  public val OMINOUS_ITEM_SPAWNER: RegistryKey<EntityType> =
      createKey("minecraft:ominous_item_spawner")

  public val PAINTING: RegistryKey<EntityType> = createKey("minecraft:painting")

  public val PALE_OAK_BOAT: RegistryKey<EntityType> = createKey("minecraft:pale_oak_boat")

  public val PALE_OAK_CHEST_BOAT: RegistryKey<EntityType> =
      createKey("minecraft:pale_oak_chest_boat")

  public val PANDA: RegistryKey<EntityType> = createKey("minecraft:panda")

  public val PARCHED: RegistryKey<EntityType> = createKey("minecraft:parched")

  public val PARROT: RegistryKey<EntityType> = createKey("minecraft:parrot")

  public val PHANTOM: RegistryKey<EntityType> = createKey("minecraft:phantom")

  public val PIG: RegistryKey<EntityType> = createKey("minecraft:pig")

  public val PIGLIN: RegistryKey<EntityType> = createKey("minecraft:piglin")

  public val PIGLIN_BRUTE: RegistryKey<EntityType> = createKey("minecraft:piglin_brute")

  public val PILLAGER: RegistryKey<EntityType> = createKey("minecraft:pillager")

  public val POLAR_BEAR: RegistryKey<EntityType> = createKey("minecraft:polar_bear")

  public val SPLASH_POTION: RegistryKey<EntityType> = createKey("minecraft:splash_potion")

  public val LINGERING_POTION: RegistryKey<EntityType> = createKey("minecraft:lingering_potion")

  public val PUFFERFISH: RegistryKey<EntityType> = createKey("minecraft:pufferfish")

  public val RABBIT: RegistryKey<EntityType> = createKey("minecraft:rabbit")

  public val RAVAGER: RegistryKey<EntityType> = createKey("minecraft:ravager")

  public val SALMON: RegistryKey<EntityType> = createKey("minecraft:salmon")

  public val SHEEP: RegistryKey<EntityType> = createKey("minecraft:sheep")

  public val SHULKER: RegistryKey<EntityType> = createKey("minecraft:shulker")

  public val SHULKER_BULLET: RegistryKey<EntityType> = createKey("minecraft:shulker_bullet")

  public val SILVERFISH: RegistryKey<EntityType> = createKey("minecraft:silverfish")

  public val SKELETON: RegistryKey<EntityType> = createKey("minecraft:skeleton")

  public val SKELETON_HORSE: RegistryKey<EntityType> = createKey("minecraft:skeleton_horse")

  public val SLIME: RegistryKey<EntityType> = createKey("minecraft:slime")

  public val SMALL_FIREBALL: RegistryKey<EntityType> = createKey("minecraft:small_fireball")

  public val SNIFFER: RegistryKey<EntityType> = createKey("minecraft:sniffer")

  public val SNOWBALL: RegistryKey<EntityType> = createKey("minecraft:snowball")

  public val SNOW_GOLEM: RegistryKey<EntityType> = createKey("minecraft:snow_golem")

  public val SPAWNER_MINECART: RegistryKey<EntityType> = createKey("minecraft:spawner_minecart")

  public val SPECTRAL_ARROW: RegistryKey<EntityType> = createKey("minecraft:spectral_arrow")

  public val SPIDER: RegistryKey<EntityType> = createKey("minecraft:spider")

  public val SPRUCE_BOAT: RegistryKey<EntityType> = createKey("minecraft:spruce_boat")

  public val SPRUCE_CHEST_BOAT: RegistryKey<EntityType> = createKey("minecraft:spruce_chest_boat")

  public val SQUID: RegistryKey<EntityType> = createKey("minecraft:squid")

  public val STRAY: RegistryKey<EntityType> = createKey("minecraft:stray")

  public val STRIDER: RegistryKey<EntityType> = createKey("minecraft:strider")

  public val TADPOLE: RegistryKey<EntityType> = createKey("minecraft:tadpole")

  public val TEXT_DISPLAY: RegistryKey<EntityType> = createKey("minecraft:text_display")

  public val TNT: RegistryKey<EntityType> = createKey("minecraft:tnt")

  public val TNT_MINECART: RegistryKey<EntityType> = createKey("minecraft:tnt_minecart")

  public val TRADER_LLAMA: RegistryKey<EntityType> = createKey("minecraft:trader_llama")

  public val TRIDENT: RegistryKey<EntityType> = createKey("minecraft:trident")

  public val TROPICAL_FISH: RegistryKey<EntityType> = createKey("minecraft:tropical_fish")

  public val TURTLE: RegistryKey<EntityType> = createKey("minecraft:turtle")

  public val VEX: RegistryKey<EntityType> = createKey("minecraft:vex")

  public val VILLAGER: RegistryKey<EntityType> = createKey("minecraft:villager")

  public val VINDICATOR: RegistryKey<EntityType> = createKey("minecraft:vindicator")

  public val WANDERING_TRADER: RegistryKey<EntityType> = createKey("minecraft:wandering_trader")

  public val WARDEN: RegistryKey<EntityType> = createKey("minecraft:warden")

  public val WIND_CHARGE: RegistryKey<EntityType> = createKey("minecraft:wind_charge")

  public val WITCH: RegistryKey<EntityType> = createKey("minecraft:witch")

  public val WITHER: RegistryKey<EntityType> = createKey("minecraft:wither")

  public val WITHER_SKELETON: RegistryKey<EntityType> = createKey("minecraft:wither_skeleton")

  public val WITHER_SKULL: RegistryKey<EntityType> = createKey("minecraft:wither_skull")

  public val WOLF: RegistryKey<EntityType> = createKey("minecraft:wolf")

  public val ZOGLIN: RegistryKey<EntityType> = createKey("minecraft:zoglin")

  public val ZOMBIE: RegistryKey<EntityType> = createKey("minecraft:zombie")

  public val ZOMBIE_HORSE: RegistryKey<EntityType> = createKey("minecraft:zombie_horse")

  public val ZOMBIE_NAUTILUS: RegistryKey<EntityType> = createKey("minecraft:zombie_nautilus")

  public val ZOMBIE_VILLAGER: RegistryKey<EntityType> = createKey("minecraft:zombie_villager")

  public val ZOMBIFIED_PIGLIN: RegistryKey<EntityType> = createKey("minecraft:zombified_piglin")

  public val PLAYER: RegistryKey<EntityType> = createKey("minecraft:player")

  public val FISHING_BOBBER: RegistryKey<EntityType> = createKey("minecraft:fishing_bobber")
}
