// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.Fluid
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object Fluids {
  public val EMPTY: Key<Fluid> = fromKey("minecraft:empty")

  public val FLOWING_WATER: Key<Fluid> = fromKey("minecraft:flowing_water")

  public val WATER: Key<Fluid> = fromKey("minecraft:water")

  public val FLOWING_LAVA: Key<Fluid> = fromKey("minecraft:flowing_lava")

  public val LAVA: Key<Fluid> = fromKey("minecraft:lava")
}
