// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.Fluid
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object Fluids {
  public val EMPTY: RegistryKey<Fluid> = createKey("minecraft:empty")

  public val FLOWING_WATER: RegistryKey<Fluid> = createKey("minecraft:flowing_water")

  public val WATER: RegistryKey<Fluid> = createKey("minecraft:water")

  public val FLOWING_LAVA: RegistryKey<Fluid> = createKey("minecraft:flowing_lava")

  public val LAVA: RegistryKey<Fluid> = createKey("minecraft:lava")
}
