// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.FrogVariant
import ru.cherryngine.lib.minecraft.registry.registries.FrogVariantRegistry

public object FrogVariants {
  public val WARM: FrogVariant = FrogVariantRegistry["minecraft:warm"]

  public val COLD: FrogVariant = FrogVariantRegistry["minecraft:cold"]

  public val TEMPERATE: FrogVariant = FrogVariantRegistry["minecraft:temperate"]
}
