// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.FrogVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object FrogVariants {
  public val WARM: RegistryKey<FrogVariant> = createKey("minecraft:warm")

  public val COLD: RegistryKey<FrogVariant> = createKey("minecraft:cold")

  public val TEMPERATE: RegistryKey<FrogVariant> = createKey("minecraft:temperate")
}
