// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.FrogVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object FrogVariants {
  public val WARM: Key<FrogVariant> = fromKey("minecraft:warm")

  public val COLD: Key<FrogVariant> = fromKey("minecraft:cold")

  public val TEMPERATE: Key<FrogVariant> = fromKey("minecraft:temperate")
}
