// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.JukeboxSong
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object JukeboxSongs {
  public val PRECIPICE: Key<JukeboxSong> = fromKey("minecraft:precipice")

  public val STAL: Key<JukeboxSong> = fromKey("minecraft:stal")

  public val STRAD: Key<JukeboxSong> = fromKey("minecraft:strad")

  public val CREATOR_MUSIC_BOX: Key<JukeboxSong> = fromKey("minecraft:creator_music_box")

  public val `13`: Key<JukeboxSong> = fromKey("minecraft:13")

  public val RELIC: Key<JukeboxSong> = fromKey("minecraft:relic")

  public val FAR: Key<JukeboxSong> = fromKey("minecraft:far")

  public val BLOCKS: Key<JukeboxSong> = fromKey("minecraft:blocks")

  public val `5`: Key<JukeboxSong> = fromKey("minecraft:5")

  public val LAVA_CHICKEN: Key<JukeboxSong> = fromKey("minecraft:lava_chicken")

  public val OTHERSIDE: Key<JukeboxSong> = fromKey("minecraft:otherside")

  public val TEARS: Key<JukeboxSong> = fromKey("minecraft:tears")

  public val MELLOHI: Key<JukeboxSong> = fromKey("minecraft:mellohi")

  public val MALL: Key<JukeboxSong> = fromKey("minecraft:mall")

  public val CHIRP: Key<JukeboxSong> = fromKey("minecraft:chirp")

  public val CREATOR: Key<JukeboxSong> = fromKey("minecraft:creator")

  public val PIGSTEP: Key<JukeboxSong> = fromKey("minecraft:pigstep")

  public val WARD: Key<JukeboxSong> = fromKey("minecraft:ward")

  public val CAT: Key<JukeboxSong> = fromKey("minecraft:cat")

  public val WAIT: Key<JukeboxSong> = fromKey("minecraft:wait")

  public val `11`: Key<JukeboxSong> = fromKey("minecraft:11")
}
