// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.JukeboxSong
import ru.cherryngine.lib.minecraft.registry.registries.JukeboxSongRegistry

public object JukeboxSongs {
  public val PRECIPICE: JukeboxSong = JukeboxSongRegistry["minecraft:precipice"]

  public val STAL: JukeboxSong = JukeboxSongRegistry["minecraft:stal"]

  public val STRAD: JukeboxSong = JukeboxSongRegistry["minecraft:strad"]

  public val CREATOR_MUSIC_BOX: JukeboxSong = JukeboxSongRegistry["minecraft:creator_music_box"]

  public val `13`: JukeboxSong = JukeboxSongRegistry["minecraft:13"]

  public val RELIC: JukeboxSong = JukeboxSongRegistry["minecraft:relic"]

  public val FAR: JukeboxSong = JukeboxSongRegistry["minecraft:far"]

  public val BLOCKS: JukeboxSong = JukeboxSongRegistry["minecraft:blocks"]

  public val `5`: JukeboxSong = JukeboxSongRegistry["minecraft:5"]

  public val LAVA_CHICKEN: JukeboxSong = JukeboxSongRegistry["minecraft:lava_chicken"]

  public val OTHERSIDE: JukeboxSong = JukeboxSongRegistry["minecraft:otherside"]

  public val TEARS: JukeboxSong = JukeboxSongRegistry["minecraft:tears"]

  public val MELLOHI: JukeboxSong = JukeboxSongRegistry["minecraft:mellohi"]

  public val MALL: JukeboxSong = JukeboxSongRegistry["minecraft:mall"]

  public val CHIRP: JukeboxSong = JukeboxSongRegistry["minecraft:chirp"]

  public val CREATOR: JukeboxSong = JukeboxSongRegistry["minecraft:creator"]

  public val PIGSTEP: JukeboxSong = JukeboxSongRegistry["minecraft:pigstep"]

  public val WARD: JukeboxSong = JukeboxSongRegistry["minecraft:ward"]

  public val CAT: JukeboxSong = JukeboxSongRegistry["minecraft:cat"]

  public val WAIT: JukeboxSong = JukeboxSongRegistry["minecraft:wait"]

  public val `11`: JukeboxSong = JukeboxSongRegistry["minecraft:11"]
}
