// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.JukeboxSong
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object JukeboxSongs {
  public val PRECIPICE: RegistryKey<JukeboxSong> = createKey("minecraft:precipice")

  public val STAL: RegistryKey<JukeboxSong> = createKey("minecraft:stal")

  public val STRAD: RegistryKey<JukeboxSong> = createKey("minecraft:strad")

  public val CREATOR_MUSIC_BOX: RegistryKey<JukeboxSong> = createKey("minecraft:creator_music_box")

  public val `13`: RegistryKey<JukeboxSong> = createKey("minecraft:13")

  public val RELIC: RegistryKey<JukeboxSong> = createKey("minecraft:relic")

  public val FAR: RegistryKey<JukeboxSong> = createKey("minecraft:far")

  public val BLOCKS: RegistryKey<JukeboxSong> = createKey("minecraft:blocks")

  public val `5`: RegistryKey<JukeboxSong> = createKey("minecraft:5")

  public val LAVA_CHICKEN: RegistryKey<JukeboxSong> = createKey("minecraft:lava_chicken")

  public val OTHERSIDE: RegistryKey<JukeboxSong> = createKey("minecraft:otherside")

  public val TEARS: RegistryKey<JukeboxSong> = createKey("minecraft:tears")

  public val MELLOHI: RegistryKey<JukeboxSong> = createKey("minecraft:mellohi")

  public val MALL: RegistryKey<JukeboxSong> = createKey("minecraft:mall")

  public val CHIRP: RegistryKey<JukeboxSong> = createKey("minecraft:chirp")

  public val CREATOR: RegistryKey<JukeboxSong> = createKey("minecraft:creator")

  public val PIGSTEP: RegistryKey<JukeboxSong> = createKey("minecraft:pigstep")

  public val WARD: RegistryKey<JukeboxSong> = createKey("minecraft:ward")

  public val CAT: RegistryKey<JukeboxSong> = createKey("minecraft:cat")

  public val WAIT: RegistryKey<JukeboxSong> = createKey("minecraft:wait")

  public val `11`: RegistryKey<JukeboxSong> = createKey("minecraft:11")
}
