// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.PaintingVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object PaintingVariants {
  public val BOUQUET: RegistryKey<PaintingVariant> = createKey("minecraft:bouquet")

  public val WITHER: RegistryKey<PaintingVariant> = createKey("minecraft:wither")

  public val ALBAN: RegistryKey<PaintingVariant> = createKey("minecraft:alban")

  public val UNPACKED: RegistryKey<PaintingVariant> = createKey("minecraft:unpacked")

  public val AZTEC: RegistryKey<PaintingVariant> = createKey("minecraft:aztec")

  public val MATCH: RegistryKey<PaintingVariant> = createKey("minecraft:match")

  public val FINDING: RegistryKey<PaintingVariant> = createKey("minecraft:finding")

  public val BAROQUE: RegistryKey<PaintingVariant> = createKey("minecraft:baroque")

  public val ENDBOSS: RegistryKey<PaintingVariant> = createKey("minecraft:endboss")

  public val ORB: RegistryKey<PaintingVariant> = createKey("minecraft:orb")

  public val AZTEC2: RegistryKey<PaintingVariant> = createKey("minecraft:aztec2")

  public val SUNFLOWERS: RegistryKey<PaintingVariant> = createKey("minecraft:sunflowers")

  public val CHANGING: RegistryKey<PaintingVariant> = createKey("minecraft:changing")

  public val WASTELAND: RegistryKey<PaintingVariant> = createKey("minecraft:wasteland")

  public val DONKEY_KONG: RegistryKey<PaintingVariant> = createKey("minecraft:donkey_kong")

  public val BUST: RegistryKey<PaintingVariant> = createKey("minecraft:bust")

  public val POOL: RegistryKey<PaintingVariant> = createKey("minecraft:pool")

  public val PIGSCENE: RegistryKey<PaintingVariant> = createKey("minecraft:pigscene")

  public val BURNING_SKULL: RegistryKey<PaintingVariant> = createKey("minecraft:burning_skull")

  public val FIRE: RegistryKey<PaintingVariant> = createKey("minecraft:fire")

  public val SEA: RegistryKey<PaintingVariant> = createKey("minecraft:sea")

  public val SUNSET: RegistryKey<PaintingVariant> = createKey("minecraft:sunset")

  public val POND: RegistryKey<PaintingVariant> = createKey("minecraft:pond")

  public val HUMBLE: RegistryKey<PaintingVariant> = createKey("minecraft:humble")

  public val TIDES: RegistryKey<PaintingVariant> = createKey("minecraft:tides")

  public val PRAIRIE_RIDE: RegistryKey<PaintingVariant> = createKey("minecraft:prairie_ride")

  public val FERN: RegistryKey<PaintingVariant> = createKey("minecraft:fern")

  public val PASSAGE: RegistryKey<PaintingVariant> = createKey("minecraft:passage")

  public val LOWMIST: RegistryKey<PaintingVariant> = createKey("minecraft:lowmist")

  public val COURBET: RegistryKey<PaintingVariant> = createKey("minecraft:courbet")

  public val WANDERER: RegistryKey<PaintingVariant> = createKey("minecraft:wanderer")

  public val BACKYARD: RegistryKey<PaintingVariant> = createKey("minecraft:backyard")

  public val EARTH: RegistryKey<PaintingVariant> = createKey("minecraft:earth")

  public val SKULL_AND_ROSES: RegistryKey<PaintingVariant> = createKey("minecraft:skull_and_roses")

  public val CAVEBIRD: RegistryKey<PaintingVariant> = createKey("minecraft:cavebird")

  public val FIGHTERS: RegistryKey<PaintingVariant> = createKey("minecraft:fighters")

  public val COTAN: RegistryKey<PaintingVariant> = createKey("minecraft:cotan")

  public val CREEBET: RegistryKey<PaintingVariant> = createKey("minecraft:creebet")

  public val OWLEMONS: RegistryKey<PaintingVariant> = createKey("minecraft:owlemons")

  public val GRAHAM: RegistryKey<PaintingVariant> = createKey("minecraft:graham")

  public val DENNIS: RegistryKey<PaintingVariant> = createKey("minecraft:dennis")

  public val MEDITATIVE: RegistryKey<PaintingVariant> = createKey("minecraft:meditative")

  public val KEBAB: RegistryKey<PaintingVariant> = createKey("minecraft:kebab")

  public val STAGE: RegistryKey<PaintingVariant> = createKey("minecraft:stage")

  public val BOMB: RegistryKey<PaintingVariant> = createKey("minecraft:bomb")

  public val PLANT: RegistryKey<PaintingVariant> = createKey("minecraft:plant")

  public val WATER: RegistryKey<PaintingVariant> = createKey("minecraft:water")

  public val POINTER: RegistryKey<PaintingVariant> = createKey("minecraft:pointer")

  public val SKELETON: RegistryKey<PaintingVariant> = createKey("minecraft:skeleton")

  public val VOID: RegistryKey<PaintingVariant> = createKey("minecraft:void")

  public val WIND: RegistryKey<PaintingVariant> = createKey("minecraft:wind")
}
