// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.PaintingVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object PaintingVariants {
  public val BOUQUET: Key<PaintingVariant> = fromKey("minecraft:bouquet")

  public val WITHER: Key<PaintingVariant> = fromKey("minecraft:wither")

  public val ALBAN: Key<PaintingVariant> = fromKey("minecraft:alban")

  public val UNPACKED: Key<PaintingVariant> = fromKey("minecraft:unpacked")

  public val AZTEC: Key<PaintingVariant> = fromKey("minecraft:aztec")

  public val MATCH: Key<PaintingVariant> = fromKey("minecraft:match")

  public val FINDING: Key<PaintingVariant> = fromKey("minecraft:finding")

  public val BAROQUE: Key<PaintingVariant> = fromKey("minecraft:baroque")

  public val ENDBOSS: Key<PaintingVariant> = fromKey("minecraft:endboss")

  public val ORB: Key<PaintingVariant> = fromKey("minecraft:orb")

  public val AZTEC2: Key<PaintingVariant> = fromKey("minecraft:aztec2")

  public val SUNFLOWERS: Key<PaintingVariant> = fromKey("minecraft:sunflowers")

  public val CHANGING: Key<PaintingVariant> = fromKey("minecraft:changing")

  public val WASTELAND: Key<PaintingVariant> = fromKey("minecraft:wasteland")

  public val DONKEY_KONG: Key<PaintingVariant> = fromKey("minecraft:donkey_kong")

  public val BUST: Key<PaintingVariant> = fromKey("minecraft:bust")

  public val POOL: Key<PaintingVariant> = fromKey("minecraft:pool")

  public val PIGSCENE: Key<PaintingVariant> = fromKey("minecraft:pigscene")

  public val BURNING_SKULL: Key<PaintingVariant> = fromKey("minecraft:burning_skull")

  public val FIRE: Key<PaintingVariant> = fromKey("minecraft:fire")

  public val SEA: Key<PaintingVariant> = fromKey("minecraft:sea")

  public val SUNSET: Key<PaintingVariant> = fromKey("minecraft:sunset")

  public val POND: Key<PaintingVariant> = fromKey("minecraft:pond")

  public val HUMBLE: Key<PaintingVariant> = fromKey("minecraft:humble")

  public val TIDES: Key<PaintingVariant> = fromKey("minecraft:tides")

  public val PRAIRIE_RIDE: Key<PaintingVariant> = fromKey("minecraft:prairie_ride")

  public val FERN: Key<PaintingVariant> = fromKey("minecraft:fern")

  public val PASSAGE: Key<PaintingVariant> = fromKey("minecraft:passage")

  public val LOWMIST: Key<PaintingVariant> = fromKey("minecraft:lowmist")

  public val COURBET: Key<PaintingVariant> = fromKey("minecraft:courbet")

  public val WANDERER: Key<PaintingVariant> = fromKey("minecraft:wanderer")

  public val BACKYARD: Key<PaintingVariant> = fromKey("minecraft:backyard")

  public val EARTH: Key<PaintingVariant> = fromKey("minecraft:earth")

  public val SKULL_AND_ROSES: Key<PaintingVariant> = fromKey("minecraft:skull_and_roses")

  public val CAVEBIRD: Key<PaintingVariant> = fromKey("minecraft:cavebird")

  public val FIGHTERS: Key<PaintingVariant> = fromKey("minecraft:fighters")

  public val COTAN: Key<PaintingVariant> = fromKey("minecraft:cotan")

  public val CREEBET: Key<PaintingVariant> = fromKey("minecraft:creebet")

  public val OWLEMONS: Key<PaintingVariant> = fromKey("minecraft:owlemons")

  public val GRAHAM: Key<PaintingVariant> = fromKey("minecraft:graham")

  public val DENNIS: Key<PaintingVariant> = fromKey("minecraft:dennis")

  public val MEDITATIVE: Key<PaintingVariant> = fromKey("minecraft:meditative")

  public val KEBAB: Key<PaintingVariant> = fromKey("minecraft:kebab")

  public val STAGE: Key<PaintingVariant> = fromKey("minecraft:stage")

  public val BOMB: Key<PaintingVariant> = fromKey("minecraft:bomb")

  public val PLANT: Key<PaintingVariant> = fromKey("minecraft:plant")

  public val WATER: Key<PaintingVariant> = fromKey("minecraft:water")

  public val POINTER: Key<PaintingVariant> = fromKey("minecraft:pointer")

  public val SKELETON: Key<PaintingVariant> = fromKey("minecraft:skeleton")

  public val VOID: Key<PaintingVariant> = fromKey("minecraft:void")

  public val WIND: Key<PaintingVariant> = fromKey("minecraft:wind")
}
