// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.PaintingVariant
import ru.cherryngine.lib.minecraft.registry.registries.PaintingVariantRegistry

public object PaintingVariants {
  public val BOUQUET: PaintingVariant = PaintingVariantRegistry["minecraft:bouquet"]

  public val WITHER: PaintingVariant = PaintingVariantRegistry["minecraft:wither"]

  public val ALBAN: PaintingVariant = PaintingVariantRegistry["minecraft:alban"]

  public val UNPACKED: PaintingVariant = PaintingVariantRegistry["minecraft:unpacked"]

  public val AZTEC: PaintingVariant = PaintingVariantRegistry["minecraft:aztec"]

  public val MATCH: PaintingVariant = PaintingVariantRegistry["minecraft:match"]

  public val FINDING: PaintingVariant = PaintingVariantRegistry["minecraft:finding"]

  public val BAROQUE: PaintingVariant = PaintingVariantRegistry["minecraft:baroque"]

  public val ENDBOSS: PaintingVariant = PaintingVariantRegistry["minecraft:endboss"]

  public val ORB: PaintingVariant = PaintingVariantRegistry["minecraft:orb"]

  public val AZTEC2: PaintingVariant = PaintingVariantRegistry["minecraft:aztec2"]

  public val SUNFLOWERS: PaintingVariant = PaintingVariantRegistry["minecraft:sunflowers"]

  public val CHANGING: PaintingVariant = PaintingVariantRegistry["minecraft:changing"]

  public val WASTELAND: PaintingVariant = PaintingVariantRegistry["minecraft:wasteland"]

  public val DONKEY_KONG: PaintingVariant = PaintingVariantRegistry["minecraft:donkey_kong"]

  public val BUST: PaintingVariant = PaintingVariantRegistry["minecraft:bust"]

  public val POOL: PaintingVariant = PaintingVariantRegistry["minecraft:pool"]

  public val PIGSCENE: PaintingVariant = PaintingVariantRegistry["minecraft:pigscene"]

  public val BURNING_SKULL: PaintingVariant = PaintingVariantRegistry["minecraft:burning_skull"]

  public val FIRE: PaintingVariant = PaintingVariantRegistry["minecraft:fire"]

  public val SEA: PaintingVariant = PaintingVariantRegistry["minecraft:sea"]

  public val SUNSET: PaintingVariant = PaintingVariantRegistry["minecraft:sunset"]

  public val POND: PaintingVariant = PaintingVariantRegistry["minecraft:pond"]

  public val HUMBLE: PaintingVariant = PaintingVariantRegistry["minecraft:humble"]

  public val TIDES: PaintingVariant = PaintingVariantRegistry["minecraft:tides"]

  public val PRAIRIE_RIDE: PaintingVariant = PaintingVariantRegistry["minecraft:prairie_ride"]

  public val FERN: PaintingVariant = PaintingVariantRegistry["minecraft:fern"]

  public val PASSAGE: PaintingVariant = PaintingVariantRegistry["minecraft:passage"]

  public val LOWMIST: PaintingVariant = PaintingVariantRegistry["minecraft:lowmist"]

  public val COURBET: PaintingVariant = PaintingVariantRegistry["minecraft:courbet"]

  public val WANDERER: PaintingVariant = PaintingVariantRegistry["minecraft:wanderer"]

  public val BACKYARD: PaintingVariant = PaintingVariantRegistry["minecraft:backyard"]

  public val EARTH: PaintingVariant = PaintingVariantRegistry["minecraft:earth"]

  public val SKULL_AND_ROSES: PaintingVariant = PaintingVariantRegistry["minecraft:skull_and_roses"]

  public val CAVEBIRD: PaintingVariant = PaintingVariantRegistry["minecraft:cavebird"]

  public val FIGHTERS: PaintingVariant = PaintingVariantRegistry["minecraft:fighters"]

  public val COTAN: PaintingVariant = PaintingVariantRegistry["minecraft:cotan"]

  public val CREEBET: PaintingVariant = PaintingVariantRegistry["minecraft:creebet"]

  public val OWLEMONS: PaintingVariant = PaintingVariantRegistry["minecraft:owlemons"]

  public val GRAHAM: PaintingVariant = PaintingVariantRegistry["minecraft:graham"]

  public val DENNIS: PaintingVariant = PaintingVariantRegistry["minecraft:dennis"]

  public val MEDITATIVE: PaintingVariant = PaintingVariantRegistry["minecraft:meditative"]

  public val KEBAB: PaintingVariant = PaintingVariantRegistry["minecraft:kebab"]

  public val STAGE: PaintingVariant = PaintingVariantRegistry["minecraft:stage"]

  public val BOMB: PaintingVariant = PaintingVariantRegistry["minecraft:bomb"]

  public val PLANT: PaintingVariant = PaintingVariantRegistry["minecraft:plant"]

  public val WATER: PaintingVariant = PaintingVariantRegistry["minecraft:water"]

  public val POINTER: PaintingVariant = PaintingVariantRegistry["minecraft:pointer"]

  public val SKELETON: PaintingVariant = PaintingVariantRegistry["minecraft:skeleton"]

  public val VOID: PaintingVariant = PaintingVariantRegistry["minecraft:void"]

  public val WIND: PaintingVariant = PaintingVariantRegistry["minecraft:wind"]
}
