// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.Particle
import ru.cherryngine.lib.minecraft.registry.registries.ParticleRegistry

public object Particles {
  public val ANGRY_VILLAGER: Particle = ParticleRegistry["minecraft:angry_villager"]

  public val BLOCK: Particle = ParticleRegistry["minecraft:block"]

  public val BLOCK_MARKER: Particle = ParticleRegistry["minecraft:block_marker"]

  public val BUBBLE: Particle = ParticleRegistry["minecraft:bubble"]

  public val CLOUD: Particle = ParticleRegistry["minecraft:cloud"]

  public val COPPER_FIRE_FLAME: Particle = ParticleRegistry["minecraft:copper_fire_flame"]

  public val CRIT: Particle = ParticleRegistry["minecraft:crit"]

  public val DAMAGE_INDICATOR: Particle = ParticleRegistry["minecraft:damage_indicator"]

  public val DRAGON_BREATH: Particle = ParticleRegistry["minecraft:dragon_breath"]

  public val DRIPPING_LAVA: Particle = ParticleRegistry["minecraft:dripping_lava"]

  public val FALLING_LAVA: Particle = ParticleRegistry["minecraft:falling_lava"]

  public val LANDING_LAVA: Particle = ParticleRegistry["minecraft:landing_lava"]

  public val DRIPPING_WATER: Particle = ParticleRegistry["minecraft:dripping_water"]

  public val FALLING_WATER: Particle = ParticleRegistry["minecraft:falling_water"]

  public val DUST: Particle = ParticleRegistry["minecraft:dust"]

  public val DUST_COLOR_TRANSITION: Particle = ParticleRegistry["minecraft:dust_color_transition"]

  public val EFFECT: Particle = ParticleRegistry["minecraft:effect"]

  public val ELDER_GUARDIAN: Particle = ParticleRegistry["minecraft:elder_guardian"]

  public val ENCHANTED_HIT: Particle = ParticleRegistry["minecraft:enchanted_hit"]

  public val ENCHANT: Particle = ParticleRegistry["minecraft:enchant"]

  public val END_ROD: Particle = ParticleRegistry["minecraft:end_rod"]

  public val ENTITY_EFFECT: Particle = ParticleRegistry["minecraft:entity_effect"]

  public val EXPLOSION_EMITTER: Particle = ParticleRegistry["minecraft:explosion_emitter"]

  public val EXPLOSION: Particle = ParticleRegistry["minecraft:explosion"]

  public val GUST: Particle = ParticleRegistry["minecraft:gust"]

  public val SMALL_GUST: Particle = ParticleRegistry["minecraft:small_gust"]

  public val GUST_EMITTER_LARGE: Particle = ParticleRegistry["minecraft:gust_emitter_large"]

  public val GUST_EMITTER_SMALL: Particle = ParticleRegistry["minecraft:gust_emitter_small"]

  public val SONIC_BOOM: Particle = ParticleRegistry["minecraft:sonic_boom"]

  public val FALLING_DUST: Particle = ParticleRegistry["minecraft:falling_dust"]

  public val FIREWORK: Particle = ParticleRegistry["minecraft:firework"]

  public val FISHING: Particle = ParticleRegistry["minecraft:fishing"]

  public val FLAME: Particle = ParticleRegistry["minecraft:flame"]

  public val INFESTED: Particle = ParticleRegistry["minecraft:infested"]

  public val CHERRY_LEAVES: Particle = ParticleRegistry["minecraft:cherry_leaves"]

  public val PALE_OAK_LEAVES: Particle = ParticleRegistry["minecraft:pale_oak_leaves"]

  public val TINTED_LEAVES: Particle = ParticleRegistry["minecraft:tinted_leaves"]

  public val SCULK_SOUL: Particle = ParticleRegistry["minecraft:sculk_soul"]

  public val SCULK_CHARGE: Particle = ParticleRegistry["minecraft:sculk_charge"]

  public val SCULK_CHARGE_POP: Particle = ParticleRegistry["minecraft:sculk_charge_pop"]

  public val SOUL_FIRE_FLAME: Particle = ParticleRegistry["minecraft:soul_fire_flame"]

  public val SOUL: Particle = ParticleRegistry["minecraft:soul"]

  public val FLASH: Particle = ParticleRegistry["minecraft:flash"]

  public val HAPPY_VILLAGER: Particle = ParticleRegistry["minecraft:happy_villager"]

  public val COMPOSTER: Particle = ParticleRegistry["minecraft:composter"]

  public val HEART: Particle = ParticleRegistry["minecraft:heart"]

  public val INSTANT_EFFECT: Particle = ParticleRegistry["minecraft:instant_effect"]

  public val ITEM: Particle = ParticleRegistry["minecraft:item"]

  public val VIBRATION: Particle = ParticleRegistry["minecraft:vibration"]

  public val TRAIL: Particle = ParticleRegistry["minecraft:trail"]

  public val ITEM_SLIME: Particle = ParticleRegistry["minecraft:item_slime"]

  public val ITEM_COBWEB: Particle = ParticleRegistry["minecraft:item_cobweb"]

  public val ITEM_SNOWBALL: Particle = ParticleRegistry["minecraft:item_snowball"]

  public val LARGE_SMOKE: Particle = ParticleRegistry["minecraft:large_smoke"]

  public val LAVA: Particle = ParticleRegistry["minecraft:lava"]

  public val MYCELIUM: Particle = ParticleRegistry["minecraft:mycelium"]

  public val NOTE: Particle = ParticleRegistry["minecraft:note"]

  public val POOF: Particle = ParticleRegistry["minecraft:poof"]

  public val PORTAL: Particle = ParticleRegistry["minecraft:portal"]

  public val RAIN: Particle = ParticleRegistry["minecraft:rain"]

  public val SMOKE: Particle = ParticleRegistry["minecraft:smoke"]

  public val WHITE_SMOKE: Particle = ParticleRegistry["minecraft:white_smoke"]

  public val SNEEZE: Particle = ParticleRegistry["minecraft:sneeze"]

  public val SPIT: Particle = ParticleRegistry["minecraft:spit"]

  public val SQUID_INK: Particle = ParticleRegistry["minecraft:squid_ink"]

  public val SWEEP_ATTACK: Particle = ParticleRegistry["minecraft:sweep_attack"]

  public val TOTEM_OF_UNDYING: Particle = ParticleRegistry["minecraft:totem_of_undying"]

  public val UNDERWATER: Particle = ParticleRegistry["minecraft:underwater"]

  public val SPLASH: Particle = ParticleRegistry["minecraft:splash"]

  public val WITCH: Particle = ParticleRegistry["minecraft:witch"]

  public val BUBBLE_POP: Particle = ParticleRegistry["minecraft:bubble_pop"]

  public val CURRENT_DOWN: Particle = ParticleRegistry["minecraft:current_down"]

  public val BUBBLE_COLUMN_UP: Particle = ParticleRegistry["minecraft:bubble_column_up"]

  public val NAUTILUS: Particle = ParticleRegistry["minecraft:nautilus"]

  public val DOLPHIN: Particle = ParticleRegistry["minecraft:dolphin"]

  public val CAMPFIRE_COSY_SMOKE: Particle = ParticleRegistry["minecraft:campfire_cosy_smoke"]

  public val CAMPFIRE_SIGNAL_SMOKE: Particle = ParticleRegistry["minecraft:campfire_signal_smoke"]

  public val DRIPPING_HONEY: Particle = ParticleRegistry["minecraft:dripping_honey"]

  public val FALLING_HONEY: Particle = ParticleRegistry["minecraft:falling_honey"]

  public val LANDING_HONEY: Particle = ParticleRegistry["minecraft:landing_honey"]

  public val FALLING_NECTAR: Particle = ParticleRegistry["minecraft:falling_nectar"]

  public val FALLING_SPORE_BLOSSOM: Particle = ParticleRegistry["minecraft:falling_spore_blossom"]

  public val ASH: Particle = ParticleRegistry["minecraft:ash"]

  public val CRIMSON_SPORE: Particle = ParticleRegistry["minecraft:crimson_spore"]

  public val WARPED_SPORE: Particle = ParticleRegistry["minecraft:warped_spore"]

  public val SPORE_BLOSSOM_AIR: Particle = ParticleRegistry["minecraft:spore_blossom_air"]

  public val DRIPPING_OBSIDIAN_TEAR: Particle = ParticleRegistry["minecraft:dripping_obsidian_tear"]

  public val FALLING_OBSIDIAN_TEAR: Particle = ParticleRegistry["minecraft:falling_obsidian_tear"]

  public val LANDING_OBSIDIAN_TEAR: Particle = ParticleRegistry["minecraft:landing_obsidian_tear"]

  public val REVERSE_PORTAL: Particle = ParticleRegistry["minecraft:reverse_portal"]

  public val WHITE_ASH: Particle = ParticleRegistry["minecraft:white_ash"]

  public val SMALL_FLAME: Particle = ParticleRegistry["minecraft:small_flame"]

  public val SNOWFLAKE: Particle = ParticleRegistry["minecraft:snowflake"]

  public val DRIPPING_DRIPSTONE_LAVA: Particle =
      ParticleRegistry["minecraft:dripping_dripstone_lava"]

  public val FALLING_DRIPSTONE_LAVA: Particle = ParticleRegistry["minecraft:falling_dripstone_lava"]

  public val DRIPPING_DRIPSTONE_WATER: Particle =
      ParticleRegistry["minecraft:dripping_dripstone_water"]

  public val FALLING_DRIPSTONE_WATER: Particle =
      ParticleRegistry["minecraft:falling_dripstone_water"]

  public val GLOW_SQUID_INK: Particle = ParticleRegistry["minecraft:glow_squid_ink"]

  public val GLOW: Particle = ParticleRegistry["minecraft:glow"]

  public val WAX_ON: Particle = ParticleRegistry["minecraft:wax_on"]

  public val WAX_OFF: Particle = ParticleRegistry["minecraft:wax_off"]

  public val ELECTRIC_SPARK: Particle = ParticleRegistry["minecraft:electric_spark"]

  public val SCRAPE: Particle = ParticleRegistry["minecraft:scrape"]

  public val SHRIEK: Particle = ParticleRegistry["minecraft:shriek"]

  public val EGG_CRACK: Particle = ParticleRegistry["minecraft:egg_crack"]

  public val DUST_PLUME: Particle = ParticleRegistry["minecraft:dust_plume"]

  public val TRIAL_SPAWNER_DETECTION: Particle =
      ParticleRegistry["minecraft:trial_spawner_detection"]

  public val TRIAL_SPAWNER_DETECTION_OMINOUS: Particle =
      ParticleRegistry["minecraft:trial_spawner_detection_ominous"]

  public val VAULT_CONNECTION: Particle = ParticleRegistry["minecraft:vault_connection"]

  public val DUST_PILLAR: Particle = ParticleRegistry["minecraft:dust_pillar"]

  public val OMINOUS_SPAWNING: Particle = ParticleRegistry["minecraft:ominous_spawning"]

  public val RAID_OMEN: Particle = ParticleRegistry["minecraft:raid_omen"]

  public val TRIAL_OMEN: Particle = ParticleRegistry["minecraft:trial_omen"]

  public val BLOCK_CRUMBLE: Particle = ParticleRegistry["minecraft:block_crumble"]

  public val FIREFLY: Particle = ParticleRegistry["minecraft:firefly"]
}
