// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.Particle
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object Particles {
  public val ANGRY_VILLAGER: Key<Particle> = fromKey("minecraft:angry_villager")

  public val BLOCK: Key<Particle> = fromKey("minecraft:block")

  public val BLOCK_MARKER: Key<Particle> = fromKey("minecraft:block_marker")

  public val BUBBLE: Key<Particle> = fromKey("minecraft:bubble")

  public val CLOUD: Key<Particle> = fromKey("minecraft:cloud")

  public val COPPER_FIRE_FLAME: Key<Particle> = fromKey("minecraft:copper_fire_flame")

  public val CRIT: Key<Particle> = fromKey("minecraft:crit")

  public val DAMAGE_INDICATOR: Key<Particle> = fromKey("minecraft:damage_indicator")

  public val DRAGON_BREATH: Key<Particle> = fromKey("minecraft:dragon_breath")

  public val DRIPPING_LAVA: Key<Particle> = fromKey("minecraft:dripping_lava")

  public val FALLING_LAVA: Key<Particle> = fromKey("minecraft:falling_lava")

  public val LANDING_LAVA: Key<Particle> = fromKey("minecraft:landing_lava")

  public val DRIPPING_WATER: Key<Particle> = fromKey("minecraft:dripping_water")

  public val FALLING_WATER: Key<Particle> = fromKey("minecraft:falling_water")

  public val DUST: Key<Particle> = fromKey("minecraft:dust")

  public val DUST_COLOR_TRANSITION: Key<Particle> = fromKey("minecraft:dust_color_transition")

  public val EFFECT: Key<Particle> = fromKey("minecraft:effect")

  public val ELDER_GUARDIAN: Key<Particle> = fromKey("minecraft:elder_guardian")

  public val ENCHANTED_HIT: Key<Particle> = fromKey("minecraft:enchanted_hit")

  public val ENCHANT: Key<Particle> = fromKey("minecraft:enchant")

  public val END_ROD: Key<Particle> = fromKey("minecraft:end_rod")

  public val ENTITY_EFFECT: Key<Particle> = fromKey("minecraft:entity_effect")

  public val EXPLOSION_EMITTER: Key<Particle> = fromKey("minecraft:explosion_emitter")

  public val EXPLOSION: Key<Particle> = fromKey("minecraft:explosion")

  public val GUST: Key<Particle> = fromKey("minecraft:gust")

  public val SMALL_GUST: Key<Particle> = fromKey("minecraft:small_gust")

  public val GUST_EMITTER_LARGE: Key<Particle> = fromKey("minecraft:gust_emitter_large")

  public val GUST_EMITTER_SMALL: Key<Particle> = fromKey("minecraft:gust_emitter_small")

  public val SONIC_BOOM: Key<Particle> = fromKey("minecraft:sonic_boom")

  public val FALLING_DUST: Key<Particle> = fromKey("minecraft:falling_dust")

  public val FIREWORK: Key<Particle> = fromKey("minecraft:firework")

  public val FISHING: Key<Particle> = fromKey("minecraft:fishing")

  public val FLAME: Key<Particle> = fromKey("minecraft:flame")

  public val INFESTED: Key<Particle> = fromKey("minecraft:infested")

  public val CHERRY_LEAVES: Key<Particle> = fromKey("minecraft:cherry_leaves")

  public val PALE_OAK_LEAVES: Key<Particle> = fromKey("minecraft:pale_oak_leaves")

  public val TINTED_LEAVES: Key<Particle> = fromKey("minecraft:tinted_leaves")

  public val SCULK_SOUL: Key<Particle> = fromKey("minecraft:sculk_soul")

  public val SCULK_CHARGE: Key<Particle> = fromKey("minecraft:sculk_charge")

  public val SCULK_CHARGE_POP: Key<Particle> = fromKey("minecraft:sculk_charge_pop")

  public val SOUL_FIRE_FLAME: Key<Particle> = fromKey("minecraft:soul_fire_flame")

  public val SOUL: Key<Particle> = fromKey("minecraft:soul")

  public val FLASH: Key<Particle> = fromKey("minecraft:flash")

  public val HAPPY_VILLAGER: Key<Particle> = fromKey("minecraft:happy_villager")

  public val COMPOSTER: Key<Particle> = fromKey("minecraft:composter")

  public val HEART: Key<Particle> = fromKey("minecraft:heart")

  public val INSTANT_EFFECT: Key<Particle> = fromKey("minecraft:instant_effect")

  public val ITEM: Key<Particle> = fromKey("minecraft:item")

  public val VIBRATION: Key<Particle> = fromKey("minecraft:vibration")

  public val TRAIL: Key<Particle> = fromKey("minecraft:trail")

  public val ITEM_SLIME: Key<Particle> = fromKey("minecraft:item_slime")

  public val ITEM_COBWEB: Key<Particle> = fromKey("minecraft:item_cobweb")

  public val ITEM_SNOWBALL: Key<Particle> = fromKey("minecraft:item_snowball")

  public val LARGE_SMOKE: Key<Particle> = fromKey("minecraft:large_smoke")

  public val LAVA: Key<Particle> = fromKey("minecraft:lava")

  public val MYCELIUM: Key<Particle> = fromKey("minecraft:mycelium")

  public val NOTE: Key<Particle> = fromKey("minecraft:note")

  public val POOF: Key<Particle> = fromKey("minecraft:poof")

  public val PORTAL: Key<Particle> = fromKey("minecraft:portal")

  public val RAIN: Key<Particle> = fromKey("minecraft:rain")

  public val SMOKE: Key<Particle> = fromKey("minecraft:smoke")

  public val WHITE_SMOKE: Key<Particle> = fromKey("minecraft:white_smoke")

  public val SNEEZE: Key<Particle> = fromKey("minecraft:sneeze")

  public val SPIT: Key<Particle> = fromKey("minecraft:spit")

  public val SQUID_INK: Key<Particle> = fromKey("minecraft:squid_ink")

  public val SWEEP_ATTACK: Key<Particle> = fromKey("minecraft:sweep_attack")

  public val TOTEM_OF_UNDYING: Key<Particle> = fromKey("minecraft:totem_of_undying")

  public val UNDERWATER: Key<Particle> = fromKey("minecraft:underwater")

  public val SPLASH: Key<Particle> = fromKey("minecraft:splash")

  public val WITCH: Key<Particle> = fromKey("minecraft:witch")

  public val BUBBLE_POP: Key<Particle> = fromKey("minecraft:bubble_pop")

  public val CURRENT_DOWN: Key<Particle> = fromKey("minecraft:current_down")

  public val BUBBLE_COLUMN_UP: Key<Particle> = fromKey("minecraft:bubble_column_up")

  public val NAUTILUS: Key<Particle> = fromKey("minecraft:nautilus")

  public val DOLPHIN: Key<Particle> = fromKey("minecraft:dolphin")

  public val CAMPFIRE_COSY_SMOKE: Key<Particle> = fromKey("minecraft:campfire_cosy_smoke")

  public val CAMPFIRE_SIGNAL_SMOKE: Key<Particle> = fromKey("minecraft:campfire_signal_smoke")

  public val DRIPPING_HONEY: Key<Particle> = fromKey("minecraft:dripping_honey")

  public val FALLING_HONEY: Key<Particle> = fromKey("minecraft:falling_honey")

  public val LANDING_HONEY: Key<Particle> = fromKey("minecraft:landing_honey")

  public val FALLING_NECTAR: Key<Particle> = fromKey("minecraft:falling_nectar")

  public val FALLING_SPORE_BLOSSOM: Key<Particle> = fromKey("minecraft:falling_spore_blossom")

  public val ASH: Key<Particle> = fromKey("minecraft:ash")

  public val CRIMSON_SPORE: Key<Particle> = fromKey("minecraft:crimson_spore")

  public val WARPED_SPORE: Key<Particle> = fromKey("minecraft:warped_spore")

  public val SPORE_BLOSSOM_AIR: Key<Particle> = fromKey("minecraft:spore_blossom_air")

  public val DRIPPING_OBSIDIAN_TEAR: Key<Particle> = fromKey("minecraft:dripping_obsidian_tear")

  public val FALLING_OBSIDIAN_TEAR: Key<Particle> = fromKey("minecraft:falling_obsidian_tear")

  public val LANDING_OBSIDIAN_TEAR: Key<Particle> = fromKey("minecraft:landing_obsidian_tear")

  public val REVERSE_PORTAL: Key<Particle> = fromKey("minecraft:reverse_portal")

  public val WHITE_ASH: Key<Particle> = fromKey("minecraft:white_ash")

  public val SMALL_FLAME: Key<Particle> = fromKey("minecraft:small_flame")

  public val SNOWFLAKE: Key<Particle> = fromKey("minecraft:snowflake")

  public val DRIPPING_DRIPSTONE_LAVA: Key<Particle> = fromKey("minecraft:dripping_dripstone_lava")

  public val FALLING_DRIPSTONE_LAVA: Key<Particle> = fromKey("minecraft:falling_dripstone_lava")

  public val DRIPPING_DRIPSTONE_WATER: Key<Particle> = fromKey("minecraft:dripping_dripstone_water")

  public val FALLING_DRIPSTONE_WATER: Key<Particle> = fromKey("minecraft:falling_dripstone_water")

  public val GLOW_SQUID_INK: Key<Particle> = fromKey("minecraft:glow_squid_ink")

  public val GLOW: Key<Particle> = fromKey("minecraft:glow")

  public val WAX_ON: Key<Particle> = fromKey("minecraft:wax_on")

  public val WAX_OFF: Key<Particle> = fromKey("minecraft:wax_off")

  public val ELECTRIC_SPARK: Key<Particle> = fromKey("minecraft:electric_spark")

  public val SCRAPE: Key<Particle> = fromKey("minecraft:scrape")

  public val SHRIEK: Key<Particle> = fromKey("minecraft:shriek")

  public val EGG_CRACK: Key<Particle> = fromKey("minecraft:egg_crack")

  public val DUST_PLUME: Key<Particle> = fromKey("minecraft:dust_plume")

  public val TRIAL_SPAWNER_DETECTION: Key<Particle> = fromKey("minecraft:trial_spawner_detection")

  public val TRIAL_SPAWNER_DETECTION_OMINOUS: Key<Particle> =
      fromKey("minecraft:trial_spawner_detection_ominous")

  public val VAULT_CONNECTION: Key<Particle> = fromKey("minecraft:vault_connection")

  public val DUST_PILLAR: Key<Particle> = fromKey("minecraft:dust_pillar")

  public val OMINOUS_SPAWNING: Key<Particle> = fromKey("minecraft:ominous_spawning")

  public val RAID_OMEN: Key<Particle> = fromKey("minecraft:raid_omen")

  public val TRIAL_OMEN: Key<Particle> = fromKey("minecraft:trial_omen")

  public val BLOCK_CRUMBLE: Key<Particle> = fromKey("minecraft:block_crumble")

  public val FIREFLY: Key<Particle> = fromKey("minecraft:firefly")
}
