// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.Particle
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object Particles {
  public val ANGRY_VILLAGER: RegistryKey<Particle> = createKey("minecraft:angry_villager")

  public val BLOCK: RegistryKey<Particle> = createKey("minecraft:block")

  public val BLOCK_MARKER: RegistryKey<Particle> = createKey("minecraft:block_marker")

  public val BUBBLE: RegistryKey<Particle> = createKey("minecraft:bubble")

  public val CLOUD: RegistryKey<Particle> = createKey("minecraft:cloud")

  public val COPPER_FIRE_FLAME: RegistryKey<Particle> = createKey("minecraft:copper_fire_flame")

  public val CRIT: RegistryKey<Particle> = createKey("minecraft:crit")

  public val DAMAGE_INDICATOR: RegistryKey<Particle> = createKey("minecraft:damage_indicator")

  public val DRAGON_BREATH: RegistryKey<Particle> = createKey("minecraft:dragon_breath")

  public val DRIPPING_LAVA: RegistryKey<Particle> = createKey("minecraft:dripping_lava")

  public val FALLING_LAVA: RegistryKey<Particle> = createKey("minecraft:falling_lava")

  public val LANDING_LAVA: RegistryKey<Particle> = createKey("minecraft:landing_lava")

  public val DRIPPING_WATER: RegistryKey<Particle> = createKey("minecraft:dripping_water")

  public val FALLING_WATER: RegistryKey<Particle> = createKey("minecraft:falling_water")

  public val DUST: RegistryKey<Particle> = createKey("minecraft:dust")

  public val DUST_COLOR_TRANSITION: RegistryKey<Particle> =
      createKey("minecraft:dust_color_transition")

  public val EFFECT: RegistryKey<Particle> = createKey("minecraft:effect")

  public val ELDER_GUARDIAN: RegistryKey<Particle> = createKey("minecraft:elder_guardian")

  public val ENCHANTED_HIT: RegistryKey<Particle> = createKey("minecraft:enchanted_hit")

  public val ENCHANT: RegistryKey<Particle> = createKey("minecraft:enchant")

  public val END_ROD: RegistryKey<Particle> = createKey("minecraft:end_rod")

  public val ENTITY_EFFECT: RegistryKey<Particle> = createKey("minecraft:entity_effect")

  public val EXPLOSION_EMITTER: RegistryKey<Particle> = createKey("minecraft:explosion_emitter")

  public val EXPLOSION: RegistryKey<Particle> = createKey("minecraft:explosion")

  public val GUST: RegistryKey<Particle> = createKey("minecraft:gust")

  public val SMALL_GUST: RegistryKey<Particle> = createKey("minecraft:small_gust")

  public val GUST_EMITTER_LARGE: RegistryKey<Particle> = createKey("minecraft:gust_emitter_large")

  public val GUST_EMITTER_SMALL: RegistryKey<Particle> = createKey("minecraft:gust_emitter_small")

  public val SONIC_BOOM: RegistryKey<Particle> = createKey("minecraft:sonic_boom")

  public val FALLING_DUST: RegistryKey<Particle> = createKey("minecraft:falling_dust")

  public val FIREWORK: RegistryKey<Particle> = createKey("minecraft:firework")

  public val FISHING: RegistryKey<Particle> = createKey("minecraft:fishing")

  public val FLAME: RegistryKey<Particle> = createKey("minecraft:flame")

  public val INFESTED: RegistryKey<Particle> = createKey("minecraft:infested")

  public val CHERRY_LEAVES: RegistryKey<Particle> = createKey("minecraft:cherry_leaves")

  public val PALE_OAK_LEAVES: RegistryKey<Particle> = createKey("minecraft:pale_oak_leaves")

  public val TINTED_LEAVES: RegistryKey<Particle> = createKey("minecraft:tinted_leaves")

  public val SCULK_SOUL: RegistryKey<Particle> = createKey("minecraft:sculk_soul")

  public val SCULK_CHARGE: RegistryKey<Particle> = createKey("minecraft:sculk_charge")

  public val SCULK_CHARGE_POP: RegistryKey<Particle> = createKey("minecraft:sculk_charge_pop")

  public val SOUL_FIRE_FLAME: RegistryKey<Particle> = createKey("minecraft:soul_fire_flame")

  public val SOUL: RegistryKey<Particle> = createKey("minecraft:soul")

  public val FLASH: RegistryKey<Particle> = createKey("minecraft:flash")

  public val HAPPY_VILLAGER: RegistryKey<Particle> = createKey("minecraft:happy_villager")

  public val COMPOSTER: RegistryKey<Particle> = createKey("minecraft:composter")

  public val HEART: RegistryKey<Particle> = createKey("minecraft:heart")

  public val INSTANT_EFFECT: RegistryKey<Particle> = createKey("minecraft:instant_effect")

  public val ITEM: RegistryKey<Particle> = createKey("minecraft:item")

  public val VIBRATION: RegistryKey<Particle> = createKey("minecraft:vibration")

  public val TRAIL: RegistryKey<Particle> = createKey("minecraft:trail")

  public val ITEM_SLIME: RegistryKey<Particle> = createKey("minecraft:item_slime")

  public val ITEM_COBWEB: RegistryKey<Particle> = createKey("minecraft:item_cobweb")

  public val ITEM_SNOWBALL: RegistryKey<Particle> = createKey("minecraft:item_snowball")

  public val LARGE_SMOKE: RegistryKey<Particle> = createKey("minecraft:large_smoke")

  public val LAVA: RegistryKey<Particle> = createKey("minecraft:lava")

  public val MYCELIUM: RegistryKey<Particle> = createKey("minecraft:mycelium")

  public val NOTE: RegistryKey<Particle> = createKey("minecraft:note")

  public val POOF: RegistryKey<Particle> = createKey("minecraft:poof")

  public val PORTAL: RegistryKey<Particle> = createKey("minecraft:portal")

  public val RAIN: RegistryKey<Particle> = createKey("minecraft:rain")

  public val SMOKE: RegistryKey<Particle> = createKey("minecraft:smoke")

  public val WHITE_SMOKE: RegistryKey<Particle> = createKey("minecraft:white_smoke")

  public val SNEEZE: RegistryKey<Particle> = createKey("minecraft:sneeze")

  public val SPIT: RegistryKey<Particle> = createKey("minecraft:spit")

  public val SQUID_INK: RegistryKey<Particle> = createKey("minecraft:squid_ink")

  public val SWEEP_ATTACK: RegistryKey<Particle> = createKey("minecraft:sweep_attack")

  public val TOTEM_OF_UNDYING: RegistryKey<Particle> = createKey("minecraft:totem_of_undying")

  public val UNDERWATER: RegistryKey<Particle> = createKey("minecraft:underwater")

  public val SPLASH: RegistryKey<Particle> = createKey("minecraft:splash")

  public val WITCH: RegistryKey<Particle> = createKey("minecraft:witch")

  public val BUBBLE_POP: RegistryKey<Particle> = createKey("minecraft:bubble_pop")

  public val CURRENT_DOWN: RegistryKey<Particle> = createKey("minecraft:current_down")

  public val BUBBLE_COLUMN_UP: RegistryKey<Particle> = createKey("minecraft:bubble_column_up")

  public val NAUTILUS: RegistryKey<Particle> = createKey("minecraft:nautilus")

  public val DOLPHIN: RegistryKey<Particle> = createKey("minecraft:dolphin")

  public val CAMPFIRE_COSY_SMOKE: RegistryKey<Particle> = createKey("minecraft:campfire_cosy_smoke")

  public val CAMPFIRE_SIGNAL_SMOKE: RegistryKey<Particle> =
      createKey("minecraft:campfire_signal_smoke")

  public val DRIPPING_HONEY: RegistryKey<Particle> = createKey("minecraft:dripping_honey")

  public val FALLING_HONEY: RegistryKey<Particle> = createKey("minecraft:falling_honey")

  public val LANDING_HONEY: RegistryKey<Particle> = createKey("minecraft:landing_honey")

  public val FALLING_NECTAR: RegistryKey<Particle> = createKey("minecraft:falling_nectar")

  public val FALLING_SPORE_BLOSSOM: RegistryKey<Particle> =
      createKey("minecraft:falling_spore_blossom")

  public val ASH: RegistryKey<Particle> = createKey("minecraft:ash")

  public val CRIMSON_SPORE: RegistryKey<Particle> = createKey("minecraft:crimson_spore")

  public val WARPED_SPORE: RegistryKey<Particle> = createKey("minecraft:warped_spore")

  public val SPORE_BLOSSOM_AIR: RegistryKey<Particle> = createKey("minecraft:spore_blossom_air")

  public val DRIPPING_OBSIDIAN_TEAR: RegistryKey<Particle> =
      createKey("minecraft:dripping_obsidian_tear")

  public val FALLING_OBSIDIAN_TEAR: RegistryKey<Particle> =
      createKey("minecraft:falling_obsidian_tear")

  public val LANDING_OBSIDIAN_TEAR: RegistryKey<Particle> =
      createKey("minecraft:landing_obsidian_tear")

  public val REVERSE_PORTAL: RegistryKey<Particle> = createKey("minecraft:reverse_portal")

  public val WHITE_ASH: RegistryKey<Particle> = createKey("minecraft:white_ash")

  public val SMALL_FLAME: RegistryKey<Particle> = createKey("minecraft:small_flame")

  public val SNOWFLAKE: RegistryKey<Particle> = createKey("minecraft:snowflake")

  public val DRIPPING_DRIPSTONE_LAVA: RegistryKey<Particle> =
      createKey("minecraft:dripping_dripstone_lava")

  public val FALLING_DRIPSTONE_LAVA: RegistryKey<Particle> =
      createKey("minecraft:falling_dripstone_lava")

  public val DRIPPING_DRIPSTONE_WATER: RegistryKey<Particle> =
      createKey("minecraft:dripping_dripstone_water")

  public val FALLING_DRIPSTONE_WATER: RegistryKey<Particle> =
      createKey("minecraft:falling_dripstone_water")

  public val GLOW_SQUID_INK: RegistryKey<Particle> = createKey("minecraft:glow_squid_ink")

  public val GLOW: RegistryKey<Particle> = createKey("minecraft:glow")

  public val WAX_ON: RegistryKey<Particle> = createKey("minecraft:wax_on")

  public val WAX_OFF: RegistryKey<Particle> = createKey("minecraft:wax_off")

  public val ELECTRIC_SPARK: RegistryKey<Particle> = createKey("minecraft:electric_spark")

  public val SCRAPE: RegistryKey<Particle> = createKey("minecraft:scrape")

  public val SHRIEK: RegistryKey<Particle> = createKey("minecraft:shriek")

  public val EGG_CRACK: RegistryKey<Particle> = createKey("minecraft:egg_crack")

  public val DUST_PLUME: RegistryKey<Particle> = createKey("minecraft:dust_plume")

  public val TRIAL_SPAWNER_DETECTION: RegistryKey<Particle> =
      createKey("minecraft:trial_spawner_detection")

  public val TRIAL_SPAWNER_DETECTION_OMINOUS: RegistryKey<Particle> =
      createKey("minecraft:trial_spawner_detection_ominous")

  public val VAULT_CONNECTION: RegistryKey<Particle> = createKey("minecraft:vault_connection")

  public val DUST_PILLAR: RegistryKey<Particle> = createKey("minecraft:dust_pillar")

  public val OMINOUS_SPAWNING: RegistryKey<Particle> = createKey("minecraft:ominous_spawning")

  public val RAID_OMEN: RegistryKey<Particle> = createKey("minecraft:raid_omen")

  public val TRIAL_OMEN: RegistryKey<Particle> = createKey("minecraft:trial_omen")

  public val BLOCK_CRUMBLE: RegistryKey<Particle> = createKey("minecraft:block_crumble")

  public val FIREFLY: RegistryKey<Particle> = createKey("minecraft:firefly")
}
