// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.PigVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object PigVariants {
  public val WARM: RegistryKey<PigVariant> = createKey("minecraft:warm")

  public val COLD: RegistryKey<PigVariant> = createKey("minecraft:cold")

  public val TEMPERATE: RegistryKey<PigVariant> = createKey("minecraft:temperate")
}
