// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.PigVariant
import ru.cherryngine.lib.minecraft.registry.registries.PigVariantRegistry

public object PigVariants {
  public val WARM: PigVariant = PigVariantRegistry["minecraft:warm"]

  public val COLD: PigVariant = PigVariantRegistry["minecraft:cold"]

  public val TEMPERATE: PigVariant = PigVariantRegistry["minecraft:temperate"]
}
