// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.PigVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object PigVariants {
  public val WARM: Key<PigVariant> = fromKey("minecraft:warm")

  public val COLD: Key<PigVariant> = fromKey("minecraft:cold")

  public val TEMPERATE: Key<PigVariant> = fromKey("minecraft:temperate")
}
