// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.PotionEffect
import ru.cherryngine.lib.minecraft.registry.registries.PotionEffectRegistry

public object PotionEffects {
  public val SPEED: PotionEffect = PotionEffectRegistry["minecraft:speed"]

  public val SLOWNESS: PotionEffect = PotionEffectRegistry["minecraft:slowness"]

  public val HASTE: PotionEffect = PotionEffectRegistry["minecraft:haste"]

  public val MINING_FATIGUE: PotionEffect = PotionEffectRegistry["minecraft:mining_fatigue"]

  public val STRENGTH: PotionEffect = PotionEffectRegistry["minecraft:strength"]

  public val INSTANT_HEALTH: PotionEffect = PotionEffectRegistry["minecraft:instant_health"]

  public val INSTANT_DAMAGE: PotionEffect = PotionEffectRegistry["minecraft:instant_damage"]

  public val JUMP_BOOST: PotionEffect = PotionEffectRegistry["minecraft:jump_boost"]

  public val NAUSEA: PotionEffect = PotionEffectRegistry["minecraft:nausea"]

  public val REGENERATION: PotionEffect = PotionEffectRegistry["minecraft:regeneration"]

  public val RESISTANCE: PotionEffect = PotionEffectRegistry["minecraft:resistance"]

  public val FIRE_RESISTANCE: PotionEffect = PotionEffectRegistry["minecraft:fire_resistance"]

  public val WATER_BREATHING: PotionEffect = PotionEffectRegistry["minecraft:water_breathing"]

  public val INVISIBILITY: PotionEffect = PotionEffectRegistry["minecraft:invisibility"]

  public val BLINDNESS: PotionEffect = PotionEffectRegistry["minecraft:blindness"]

  public val NIGHT_VISION: PotionEffect = PotionEffectRegistry["minecraft:night_vision"]

  public val HUNGER: PotionEffect = PotionEffectRegistry["minecraft:hunger"]

  public val WEAKNESS: PotionEffect = PotionEffectRegistry["minecraft:weakness"]

  public val POISON: PotionEffect = PotionEffectRegistry["minecraft:poison"]

  public val WITHER: PotionEffect = PotionEffectRegistry["minecraft:wither"]

  public val HEALTH_BOOST: PotionEffect = PotionEffectRegistry["minecraft:health_boost"]

  public val ABSORPTION: PotionEffect = PotionEffectRegistry["minecraft:absorption"]

  public val SATURATION: PotionEffect = PotionEffectRegistry["minecraft:saturation"]

  public val GLOWING: PotionEffect = PotionEffectRegistry["minecraft:glowing"]

  public val LEVITATION: PotionEffect = PotionEffectRegistry["minecraft:levitation"]

  public val LUCK: PotionEffect = PotionEffectRegistry["minecraft:luck"]

  public val UNLUCK: PotionEffect = PotionEffectRegistry["minecraft:unluck"]

  public val SLOW_FALLING: PotionEffect = PotionEffectRegistry["minecraft:slow_falling"]

  public val CONDUIT_POWER: PotionEffect = PotionEffectRegistry["minecraft:conduit_power"]

  public val DOLPHINS_GRACE: PotionEffect = PotionEffectRegistry["minecraft:dolphins_grace"]

  public val BAD_OMEN: PotionEffect = PotionEffectRegistry["minecraft:bad_omen"]

  public val HERO_OF_THE_VILLAGE: PotionEffect =
      PotionEffectRegistry["minecraft:hero_of_the_village"]

  public val DARKNESS: PotionEffect = PotionEffectRegistry["minecraft:darkness"]

  public val TRIAL_OMEN: PotionEffect = PotionEffectRegistry["minecraft:trial_omen"]

  public val RAID_OMEN: PotionEffect = PotionEffectRegistry["minecraft:raid_omen"]

  public val WIND_CHARGED: PotionEffect = PotionEffectRegistry["minecraft:wind_charged"]

  public val WEAVING: PotionEffect = PotionEffectRegistry["minecraft:weaving"]

  public val OOZING: PotionEffect = PotionEffectRegistry["minecraft:oozing"]

  public val INFESTED: PotionEffect = PotionEffectRegistry["minecraft:infested"]

  public val BREATH_OF_THE_NAUTILUS: PotionEffect =
      PotionEffectRegistry["minecraft:breath_of_the_nautilus"]
}
