// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.PotionEffect
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object PotionEffects {
  public val SPEED: Key<PotionEffect> = fromKey("minecraft:speed")

  public val SLOWNESS: Key<PotionEffect> = fromKey("minecraft:slowness")

  public val HASTE: Key<PotionEffect> = fromKey("minecraft:haste")

  public val MINING_FATIGUE: Key<PotionEffect> = fromKey("minecraft:mining_fatigue")

  public val STRENGTH: Key<PotionEffect> = fromKey("minecraft:strength")

  public val INSTANT_HEALTH: Key<PotionEffect> = fromKey("minecraft:instant_health")

  public val INSTANT_DAMAGE: Key<PotionEffect> = fromKey("minecraft:instant_damage")

  public val JUMP_BOOST: Key<PotionEffect> = fromKey("minecraft:jump_boost")

  public val NAUSEA: Key<PotionEffect> = fromKey("minecraft:nausea")

  public val REGENERATION: Key<PotionEffect> = fromKey("minecraft:regeneration")

  public val RESISTANCE: Key<PotionEffect> = fromKey("minecraft:resistance")

  public val FIRE_RESISTANCE: Key<PotionEffect> = fromKey("minecraft:fire_resistance")

  public val WATER_BREATHING: Key<PotionEffect> = fromKey("minecraft:water_breathing")

  public val INVISIBILITY: Key<PotionEffect> = fromKey("minecraft:invisibility")

  public val BLINDNESS: Key<PotionEffect> = fromKey("minecraft:blindness")

  public val NIGHT_VISION: Key<PotionEffect> = fromKey("minecraft:night_vision")

  public val HUNGER: Key<PotionEffect> = fromKey("minecraft:hunger")

  public val WEAKNESS: Key<PotionEffect> = fromKey("minecraft:weakness")

  public val POISON: Key<PotionEffect> = fromKey("minecraft:poison")

  public val WITHER: Key<PotionEffect> = fromKey("minecraft:wither")

  public val HEALTH_BOOST: Key<PotionEffect> = fromKey("minecraft:health_boost")

  public val ABSORPTION: Key<PotionEffect> = fromKey("minecraft:absorption")

  public val SATURATION: Key<PotionEffect> = fromKey("minecraft:saturation")

  public val GLOWING: Key<PotionEffect> = fromKey("minecraft:glowing")

  public val LEVITATION: Key<PotionEffect> = fromKey("minecraft:levitation")

  public val LUCK: Key<PotionEffect> = fromKey("minecraft:luck")

  public val UNLUCK: Key<PotionEffect> = fromKey("minecraft:unluck")

  public val SLOW_FALLING: Key<PotionEffect> = fromKey("minecraft:slow_falling")

  public val CONDUIT_POWER: Key<PotionEffect> = fromKey("minecraft:conduit_power")

  public val DOLPHINS_GRACE: Key<PotionEffect> = fromKey("minecraft:dolphins_grace")

  public val BAD_OMEN: Key<PotionEffect> = fromKey("minecraft:bad_omen")

  public val HERO_OF_THE_VILLAGE: Key<PotionEffect> = fromKey("minecraft:hero_of_the_village")

  public val DARKNESS: Key<PotionEffect> = fromKey("minecraft:darkness")

  public val TRIAL_OMEN: Key<PotionEffect> = fromKey("minecraft:trial_omen")

  public val RAID_OMEN: Key<PotionEffect> = fromKey("minecraft:raid_omen")

  public val WIND_CHARGED: Key<PotionEffect> = fromKey("minecraft:wind_charged")

  public val WEAVING: Key<PotionEffect> = fromKey("minecraft:weaving")

  public val OOZING: Key<PotionEffect> = fromKey("minecraft:oozing")

  public val INFESTED: Key<PotionEffect> = fromKey("minecraft:infested")

  public val BREATH_OF_THE_NAUTILUS: Key<PotionEffect> = fromKey("minecraft:breath_of_the_nautilus")
}
