// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.PotionEffect
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object PotionEffects {
  public val SPEED: RegistryKey<PotionEffect> = createKey("minecraft:speed")

  public val SLOWNESS: RegistryKey<PotionEffect> = createKey("minecraft:slowness")

  public val HASTE: RegistryKey<PotionEffect> = createKey("minecraft:haste")

  public val MINING_FATIGUE: RegistryKey<PotionEffect> = createKey("minecraft:mining_fatigue")

  public val STRENGTH: RegistryKey<PotionEffect> = createKey("minecraft:strength")

  public val INSTANT_HEALTH: RegistryKey<PotionEffect> = createKey("minecraft:instant_health")

  public val INSTANT_DAMAGE: RegistryKey<PotionEffect> = createKey("minecraft:instant_damage")

  public val JUMP_BOOST: RegistryKey<PotionEffect> = createKey("minecraft:jump_boost")

  public val NAUSEA: RegistryKey<PotionEffect> = createKey("minecraft:nausea")

  public val REGENERATION: RegistryKey<PotionEffect> = createKey("minecraft:regeneration")

  public val RESISTANCE: RegistryKey<PotionEffect> = createKey("minecraft:resistance")

  public val FIRE_RESISTANCE: RegistryKey<PotionEffect> = createKey("minecraft:fire_resistance")

  public val WATER_BREATHING: RegistryKey<PotionEffect> = createKey("minecraft:water_breathing")

  public val INVISIBILITY: RegistryKey<PotionEffect> = createKey("minecraft:invisibility")

  public val BLINDNESS: RegistryKey<PotionEffect> = createKey("minecraft:blindness")

  public val NIGHT_VISION: RegistryKey<PotionEffect> = createKey("minecraft:night_vision")

  public val HUNGER: RegistryKey<PotionEffect> = createKey("minecraft:hunger")

  public val WEAKNESS: RegistryKey<PotionEffect> = createKey("minecraft:weakness")

  public val POISON: RegistryKey<PotionEffect> = createKey("minecraft:poison")

  public val WITHER: RegistryKey<PotionEffect> = createKey("minecraft:wither")

  public val HEALTH_BOOST: RegistryKey<PotionEffect> = createKey("minecraft:health_boost")

  public val ABSORPTION: RegistryKey<PotionEffect> = createKey("minecraft:absorption")

  public val SATURATION: RegistryKey<PotionEffect> = createKey("minecraft:saturation")

  public val GLOWING: RegistryKey<PotionEffect> = createKey("minecraft:glowing")

  public val LEVITATION: RegistryKey<PotionEffect> = createKey("minecraft:levitation")

  public val LUCK: RegistryKey<PotionEffect> = createKey("minecraft:luck")

  public val UNLUCK: RegistryKey<PotionEffect> = createKey("minecraft:unluck")

  public val SLOW_FALLING: RegistryKey<PotionEffect> = createKey("minecraft:slow_falling")

  public val CONDUIT_POWER: RegistryKey<PotionEffect> = createKey("minecraft:conduit_power")

  public val DOLPHINS_GRACE: RegistryKey<PotionEffect> = createKey("minecraft:dolphins_grace")

  public val BAD_OMEN: RegistryKey<PotionEffect> = createKey("minecraft:bad_omen")

  public val HERO_OF_THE_VILLAGE: RegistryKey<PotionEffect> =
      createKey("minecraft:hero_of_the_village")

  public val DARKNESS: RegistryKey<PotionEffect> = createKey("minecraft:darkness")

  public val TRIAL_OMEN: RegistryKey<PotionEffect> = createKey("minecraft:trial_omen")

  public val RAID_OMEN: RegistryKey<PotionEffect> = createKey("minecraft:raid_omen")

  public val WIND_CHARGED: RegistryKey<PotionEffect> = createKey("minecraft:wind_charged")

  public val WEAVING: RegistryKey<PotionEffect> = createKey("minecraft:weaving")

  public val OOZING: RegistryKey<PotionEffect> = createKey("minecraft:oozing")

  public val INFESTED: RegistryKey<PotionEffect> = createKey("minecraft:infested")

  public val BREATH_OF_THE_NAUTILUS: RegistryKey<PotionEffect> =
      createKey("minecraft:breath_of_the_nautilus")
}
