// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.PotionType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object PotionTypes {
  public val WATER: RegistryKey<PotionType> = createKey("minecraft:water")

  public val MUNDANE: RegistryKey<PotionType> = createKey("minecraft:mundane")

  public val THICK: RegistryKey<PotionType> = createKey("minecraft:thick")

  public val AWKWARD: RegistryKey<PotionType> = createKey("minecraft:awkward")

  public val NIGHT_VISION: RegistryKey<PotionType> = createKey("minecraft:night_vision")

  public val LONG_NIGHT_VISION: RegistryKey<PotionType> = createKey("minecraft:long_night_vision")

  public val INVISIBILITY: RegistryKey<PotionType> = createKey("minecraft:invisibility")

  public val LONG_INVISIBILITY: RegistryKey<PotionType> = createKey("minecraft:long_invisibility")

  public val LEAPING: RegistryKey<PotionType> = createKey("minecraft:leaping")

  public val LONG_LEAPING: RegistryKey<PotionType> = createKey("minecraft:long_leaping")

  public val STRONG_LEAPING: RegistryKey<PotionType> = createKey("minecraft:strong_leaping")

  public val FIRE_RESISTANCE: RegistryKey<PotionType> = createKey("minecraft:fire_resistance")

  public val LONG_FIRE_RESISTANCE: RegistryKey<PotionType> =
      createKey("minecraft:long_fire_resistance")

  public val SWIFTNESS: RegistryKey<PotionType> = createKey("minecraft:swiftness")

  public val LONG_SWIFTNESS: RegistryKey<PotionType> = createKey("minecraft:long_swiftness")

  public val STRONG_SWIFTNESS: RegistryKey<PotionType> = createKey("minecraft:strong_swiftness")

  public val SLOWNESS: RegistryKey<PotionType> = createKey("minecraft:slowness")

  public val LONG_SLOWNESS: RegistryKey<PotionType> = createKey("minecraft:long_slowness")

  public val STRONG_SLOWNESS: RegistryKey<PotionType> = createKey("minecraft:strong_slowness")

  public val TURTLE_MASTER: RegistryKey<PotionType> = createKey("minecraft:turtle_master")

  public val LONG_TURTLE_MASTER: RegistryKey<PotionType> = createKey("minecraft:long_turtle_master")

  public val STRONG_TURTLE_MASTER: RegistryKey<PotionType> =
      createKey("minecraft:strong_turtle_master")

  public val WATER_BREATHING: RegistryKey<PotionType> = createKey("minecraft:water_breathing")

  public val LONG_WATER_BREATHING: RegistryKey<PotionType> =
      createKey("minecraft:long_water_breathing")

  public val HEALING: RegistryKey<PotionType> = createKey("minecraft:healing")

  public val STRONG_HEALING: RegistryKey<PotionType> = createKey("minecraft:strong_healing")

  public val HARMING: RegistryKey<PotionType> = createKey("minecraft:harming")

  public val STRONG_HARMING: RegistryKey<PotionType> = createKey("minecraft:strong_harming")

  public val POISON: RegistryKey<PotionType> = createKey("minecraft:poison")

  public val LONG_POISON: RegistryKey<PotionType> = createKey("minecraft:long_poison")

  public val STRONG_POISON: RegistryKey<PotionType> = createKey("minecraft:strong_poison")

  public val REGENERATION: RegistryKey<PotionType> = createKey("minecraft:regeneration")

  public val LONG_REGENERATION: RegistryKey<PotionType> = createKey("minecraft:long_regeneration")

  public val STRONG_REGENERATION: RegistryKey<PotionType> =
      createKey("minecraft:strong_regeneration")

  public val STRENGTH: RegistryKey<PotionType> = createKey("minecraft:strength")

  public val LONG_STRENGTH: RegistryKey<PotionType> = createKey("minecraft:long_strength")

  public val STRONG_STRENGTH: RegistryKey<PotionType> = createKey("minecraft:strong_strength")

  public val WEAKNESS: RegistryKey<PotionType> = createKey("minecraft:weakness")

  public val LONG_WEAKNESS: RegistryKey<PotionType> = createKey("minecraft:long_weakness")

  public val LUCK: RegistryKey<PotionType> = createKey("minecraft:luck")

  public val SLOW_FALLING: RegistryKey<PotionType> = createKey("minecraft:slow_falling")

  public val LONG_SLOW_FALLING: RegistryKey<PotionType> = createKey("minecraft:long_slow_falling")

  public val WIND_CHARGED: RegistryKey<PotionType> = createKey("minecraft:wind_charged")

  public val WEAVING: RegistryKey<PotionType> = createKey("minecraft:weaving")

  public val OOZING: RegistryKey<PotionType> = createKey("minecraft:oozing")

  public val INFESTED: RegistryKey<PotionType> = createKey("minecraft:infested")
}
