// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.PotionType
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object PotionTypes {
  public val WATER: Key<PotionType> = fromKey("minecraft:water")

  public val MUNDANE: Key<PotionType> = fromKey("minecraft:mundane")

  public val THICK: Key<PotionType> = fromKey("minecraft:thick")

  public val AWKWARD: Key<PotionType> = fromKey("minecraft:awkward")

  public val NIGHT_VISION: Key<PotionType> = fromKey("minecraft:night_vision")

  public val LONG_NIGHT_VISION: Key<PotionType> = fromKey("minecraft:long_night_vision")

  public val INVISIBILITY: Key<PotionType> = fromKey("minecraft:invisibility")

  public val LONG_INVISIBILITY: Key<PotionType> = fromKey("minecraft:long_invisibility")

  public val LEAPING: Key<PotionType> = fromKey("minecraft:leaping")

  public val LONG_LEAPING: Key<PotionType> = fromKey("minecraft:long_leaping")

  public val STRONG_LEAPING: Key<PotionType> = fromKey("minecraft:strong_leaping")

  public val FIRE_RESISTANCE: Key<PotionType> = fromKey("minecraft:fire_resistance")

  public val LONG_FIRE_RESISTANCE: Key<PotionType> = fromKey("minecraft:long_fire_resistance")

  public val SWIFTNESS: Key<PotionType> = fromKey("minecraft:swiftness")

  public val LONG_SWIFTNESS: Key<PotionType> = fromKey("minecraft:long_swiftness")

  public val STRONG_SWIFTNESS: Key<PotionType> = fromKey("minecraft:strong_swiftness")

  public val SLOWNESS: Key<PotionType> = fromKey("minecraft:slowness")

  public val LONG_SLOWNESS: Key<PotionType> = fromKey("minecraft:long_slowness")

  public val STRONG_SLOWNESS: Key<PotionType> = fromKey("minecraft:strong_slowness")

  public val TURTLE_MASTER: Key<PotionType> = fromKey("minecraft:turtle_master")

  public val LONG_TURTLE_MASTER: Key<PotionType> = fromKey("minecraft:long_turtle_master")

  public val STRONG_TURTLE_MASTER: Key<PotionType> = fromKey("minecraft:strong_turtle_master")

  public val WATER_BREATHING: Key<PotionType> = fromKey("minecraft:water_breathing")

  public val LONG_WATER_BREATHING: Key<PotionType> = fromKey("minecraft:long_water_breathing")

  public val HEALING: Key<PotionType> = fromKey("minecraft:healing")

  public val STRONG_HEALING: Key<PotionType> = fromKey("minecraft:strong_healing")

  public val HARMING: Key<PotionType> = fromKey("minecraft:harming")

  public val STRONG_HARMING: Key<PotionType> = fromKey("minecraft:strong_harming")

  public val POISON: Key<PotionType> = fromKey("minecraft:poison")

  public val LONG_POISON: Key<PotionType> = fromKey("minecraft:long_poison")

  public val STRONG_POISON: Key<PotionType> = fromKey("minecraft:strong_poison")

  public val REGENERATION: Key<PotionType> = fromKey("minecraft:regeneration")

  public val LONG_REGENERATION: Key<PotionType> = fromKey("minecraft:long_regeneration")

  public val STRONG_REGENERATION: Key<PotionType> = fromKey("minecraft:strong_regeneration")

  public val STRENGTH: Key<PotionType> = fromKey("minecraft:strength")

  public val LONG_STRENGTH: Key<PotionType> = fromKey("minecraft:long_strength")

  public val STRONG_STRENGTH: Key<PotionType> = fromKey("minecraft:strong_strength")

  public val WEAKNESS: Key<PotionType> = fromKey("minecraft:weakness")

  public val LONG_WEAKNESS: Key<PotionType> = fromKey("minecraft:long_weakness")

  public val LUCK: Key<PotionType> = fromKey("minecraft:luck")

  public val SLOW_FALLING: Key<PotionType> = fromKey("minecraft:slow_falling")

  public val LONG_SLOW_FALLING: Key<PotionType> = fromKey("minecraft:long_slow_falling")

  public val WIND_CHARGED: Key<PotionType> = fromKey("minecraft:wind_charged")

  public val WEAVING: Key<PotionType> = fromKey("minecraft:weaving")

  public val OOZING: Key<PotionType> = fromKey("minecraft:oozing")

  public val INFESTED: Key<PotionType> = fromKey("minecraft:infested")
}
