// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.TrimMaterial
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object TrimMaterials {
  public val LAPIS: RegistryKey<TrimMaterial> = createKey("minecraft:lapis")

  public val IRON: RegistryKey<TrimMaterial> = createKey("minecraft:iron")

  public val DIAMOND: RegistryKey<TrimMaterial> = createKey("minecraft:diamond")

  public val AMETHYST: RegistryKey<TrimMaterial> = createKey("minecraft:amethyst")

  public val COPPER: RegistryKey<TrimMaterial> = createKey("minecraft:copper")

  public val QUARTZ: RegistryKey<TrimMaterial> = createKey("minecraft:quartz")

  public val EMERALD: RegistryKey<TrimMaterial> = createKey("minecraft:emerald")

  public val RESIN: RegistryKey<TrimMaterial> = createKey("minecraft:resin")

  public val REDSTONE: RegistryKey<TrimMaterial> = createKey("minecraft:redstone")

  public val GOLD: RegistryKey<TrimMaterial> = createKey("minecraft:gold")

  public val NETHERITE: RegistryKey<TrimMaterial> = createKey("minecraft:netherite")
}
