// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.TrimPattern
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object TrimPatterns {
  public val TIDE: Key<TrimPattern> = fromKey("minecraft:tide")

  public val RIB: Key<TrimPattern> = fromKey("minecraft:rib")

  public val BOLT: Key<TrimPattern> = fromKey("minecraft:bolt")

  public val HOST: Key<TrimPattern> = fromKey("minecraft:host")

  public val SILENCE: Key<TrimPattern> = fromKey("minecraft:silence")

  public val WILD: Key<TrimPattern> = fromKey("minecraft:wild")

  public val WAYFINDER: Key<TrimPattern> = fromKey("minecraft:wayfinder")

  public val FLOW: Key<TrimPattern> = fromKey("minecraft:flow")

  public val DUNE: Key<TrimPattern> = fromKey("minecraft:dune")

  public val RAISER: Key<TrimPattern> = fromKey("minecraft:raiser")

  public val SNOUT: Key<TrimPattern> = fromKey("minecraft:snout")

  public val VEX: Key<TrimPattern> = fromKey("minecraft:vex")

  public val SPIRE: Key<TrimPattern> = fromKey("minecraft:spire")

  public val SENTRY: Key<TrimPattern> = fromKey("minecraft:sentry")

  public val EYE: Key<TrimPattern> = fromKey("minecraft:eye")

  public val WARD: Key<TrimPattern> = fromKey("minecraft:ward")

  public val COAST: Key<TrimPattern> = fromKey("minecraft:coast")

  public val SHAPER: Key<TrimPattern> = fromKey("minecraft:shaper")
}
