// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.TrimMaterial
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object TrimMaterials {
  public val LAPIS: Key<TrimMaterial> = fromKey("minecraft:lapis")

  public val IRON: Key<TrimMaterial> = fromKey("minecraft:iron")

  public val DIAMOND: Key<TrimMaterial> = fromKey("minecraft:diamond")

  public val AMETHYST: Key<TrimMaterial> = fromKey("minecraft:amethyst")

  public val COPPER: Key<TrimMaterial> = fromKey("minecraft:copper")

  public val QUARTZ: Key<TrimMaterial> = fromKey("minecraft:quartz")

  public val EMERALD: Key<TrimMaterial> = fromKey("minecraft:emerald")

  public val RESIN: Key<TrimMaterial> = fromKey("minecraft:resin")

  public val REDSTONE: Key<TrimMaterial> = fromKey("minecraft:redstone")

  public val GOLD: Key<TrimMaterial> = fromKey("minecraft:gold")

  public val NETHERITE: Key<TrimMaterial> = fromKey("minecraft:netherite")
}
