// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.TrimPattern
import ru.cherryngine.lib.minecraft.registry.registries.TrimPatternRegistry

public object TrimPatterns {
  public val TIDE: TrimPattern = TrimPatternRegistry["minecraft:tide"]

  public val RIB: TrimPattern = TrimPatternRegistry["minecraft:rib"]

  public val BOLT: TrimPattern = TrimPatternRegistry["minecraft:bolt"]

  public val HOST: TrimPattern = TrimPatternRegistry["minecraft:host"]

  public val SILENCE: TrimPattern = TrimPatternRegistry["minecraft:silence"]

  public val WILD: TrimPattern = TrimPatternRegistry["minecraft:wild"]

  public val WAYFINDER: TrimPattern = TrimPatternRegistry["minecraft:wayfinder"]

  public val FLOW: TrimPattern = TrimPatternRegistry["minecraft:flow"]

  public val DUNE: TrimPattern = TrimPatternRegistry["minecraft:dune"]

  public val RAISER: TrimPattern = TrimPatternRegistry["minecraft:raiser"]

  public val SNOUT: TrimPattern = TrimPatternRegistry["minecraft:snout"]

  public val VEX: TrimPattern = TrimPatternRegistry["minecraft:vex"]

  public val SPIRE: TrimPattern = TrimPatternRegistry["minecraft:spire"]

  public val SENTRY: TrimPattern = TrimPatternRegistry["minecraft:sentry"]

  public val EYE: TrimPattern = TrimPatternRegistry["minecraft:eye"]

  public val WARD: TrimPattern = TrimPatternRegistry["minecraft:ward"]

  public val COAST: TrimPattern = TrimPatternRegistry["minecraft:coast"]

  public val SHAPER: TrimPattern = TrimPatternRegistry["minecraft:shaper"]
}
