// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.TrimMaterial
import ru.cherryngine.lib.minecraft.registry.registries.TrimMaterialRegistry

public object TrimMaterials {
  public val LAPIS: TrimMaterial = TrimMaterialRegistry["minecraft:lapis"]

  public val IRON: TrimMaterial = TrimMaterialRegistry["minecraft:iron"]

  public val DIAMOND: TrimMaterial = TrimMaterialRegistry["minecraft:diamond"]

  public val AMETHYST: TrimMaterial = TrimMaterialRegistry["minecraft:amethyst"]

  public val COPPER: TrimMaterial = TrimMaterialRegistry["minecraft:copper"]

  public val QUARTZ: TrimMaterial = TrimMaterialRegistry["minecraft:quartz"]

  public val EMERALD: TrimMaterial = TrimMaterialRegistry["minecraft:emerald"]

  public val RESIN: TrimMaterial = TrimMaterialRegistry["minecraft:resin"]

  public val REDSTONE: TrimMaterial = TrimMaterialRegistry["minecraft:redstone"]

  public val GOLD: TrimMaterial = TrimMaterialRegistry["minecraft:gold"]

  public val NETHERITE: TrimMaterial = TrimMaterialRegistry["minecraft:netherite"]
}
