// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.TrimPattern
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object TrimPatterns {
  public val TIDE: RegistryKey<TrimPattern> = createKey("minecraft:tide")

  public val RIB: RegistryKey<TrimPattern> = createKey("minecraft:rib")

  public val BOLT: RegistryKey<TrimPattern> = createKey("minecraft:bolt")

  public val HOST: RegistryKey<TrimPattern> = createKey("minecraft:host")

  public val SILENCE: RegistryKey<TrimPattern> = createKey("minecraft:silence")

  public val WILD: RegistryKey<TrimPattern> = createKey("minecraft:wild")

  public val WAYFINDER: RegistryKey<TrimPattern> = createKey("minecraft:wayfinder")

  public val FLOW: RegistryKey<TrimPattern> = createKey("minecraft:flow")

  public val DUNE: RegistryKey<TrimPattern> = createKey("minecraft:dune")

  public val RAISER: RegistryKey<TrimPattern> = createKey("minecraft:raiser")

  public val SNOUT: RegistryKey<TrimPattern> = createKey("minecraft:snout")

  public val VEX: RegistryKey<TrimPattern> = createKey("minecraft:vex")

  public val SPIRE: RegistryKey<TrimPattern> = createKey("minecraft:spire")

  public val SENTRY: RegistryKey<TrimPattern> = createKey("minecraft:sentry")

  public val EYE: RegistryKey<TrimPattern> = createKey("minecraft:eye")

  public val WARD: RegistryKey<TrimPattern> = createKey("minecraft:ward")

  public val COAST: RegistryKey<TrimPattern> = createKey("minecraft:coast")

  public val SHAPER: RegistryKey<TrimPattern> = createKey("minecraft:shaper")
}
