// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.WolfSoundVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object WolfSoundVariants {
  public val SAD: Key<WolfSoundVariant> = fromKey("minecraft:sad")

  public val PUGLIN: Key<WolfSoundVariant> = fromKey("minecraft:puglin")

  public val CUTE: Key<WolfSoundVariant> = fromKey("minecraft:cute")

  public val GRUMPY: Key<WolfSoundVariant> = fromKey("minecraft:grumpy")

  public val BIG: Key<WolfSoundVariant> = fromKey("minecraft:big")

  public val ANGRY: Key<WolfSoundVariant> = fromKey("minecraft:angry")

  public val CLASSIC: Key<WolfSoundVariant> = fromKey("minecraft:classic")
}
