// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.WolfSoundVariant
import ru.cherryngine.lib.minecraft.registry.registries.WolfSoundVariantRegistry

public object WolfSoundVariants {
  public val SAD: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:sad"]

  public val PUGLIN: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:puglin"]

  public val CUTE: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:cute"]

  public val GRUMPY: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:grumpy"]

  public val BIG: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:big"]

  public val ANGRY: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:angry"]

  public val CLASSIC: WolfSoundVariant = WolfSoundVariantRegistry["minecraft:classic"]
}
