// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.WolfVariant
import ru.cherryngine.lib.minecraft.registry.registries.WolfVariantRegistry

public object WolfVariants {
  public val BLACK: WolfVariant = WolfVariantRegistry["minecraft:black"]

  public val CHESTNUT: WolfVariant = WolfVariantRegistry["minecraft:chestnut"]

  public val SNOWY: WolfVariant = WolfVariantRegistry["minecraft:snowy"]

  public val STRIPED: WolfVariant = WolfVariantRegistry["minecraft:striped"]

  public val ASHEN: WolfVariant = WolfVariantRegistry["minecraft:ashen"]

  public val SPOTTED: WolfVariant = WolfVariantRegistry["minecraft:spotted"]

  public val RUSTY: WolfVariant = WolfVariantRegistry["minecraft:rusty"]

  public val WOODS: WolfVariant = WolfVariantRegistry["minecraft:woods"]

  public val PALE: WolfVariant = WolfVariantRegistry["minecraft:pale"]
}
