// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.WolfSoundVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object WolfSoundVariants {
  public val SAD: RegistryKey<WolfSoundVariant> = createKey("minecraft:sad")

  public val PUGLIN: RegistryKey<WolfSoundVariant> = createKey("minecraft:puglin")

  public val CUTE: RegistryKey<WolfSoundVariant> = createKey("minecraft:cute")

  public val GRUMPY: RegistryKey<WolfSoundVariant> = createKey("minecraft:grumpy")

  public val BIG: RegistryKey<WolfSoundVariant> = createKey("minecraft:big")

  public val ANGRY: RegistryKey<WolfSoundVariant> = createKey("minecraft:angry")

  public val CLASSIC: RegistryKey<WolfSoundVariant> = createKey("minecraft:classic")
}
