// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.WolfVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object WolfVariants {
  public val BLACK: RegistryKey<WolfVariant> = createKey("minecraft:black")

  public val CHESTNUT: RegistryKey<WolfVariant> = createKey("minecraft:chestnut")

  public val SNOWY: RegistryKey<WolfVariant> = createKey("minecraft:snowy")

  public val STRIPED: RegistryKey<WolfVariant> = createKey("minecraft:striped")

  public val ASHEN: RegistryKey<WolfVariant> = createKey("minecraft:ashen")

  public val SPOTTED: RegistryKey<WolfVariant> = createKey("minecraft:spotted")

  public val RUSTY: RegistryKey<WolfVariant> = createKey("minecraft:rusty")

  public val WOODS: RegistryKey<WolfVariant> = createKey("minecraft:woods")

  public val PALE: RegistryKey<WolfVariant> = createKey("minecraft:pale")
}
