// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.WolfVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object WolfVariants {
  public val BLACK: Key<WolfVariant> = fromKey("minecraft:black")

  public val CHESTNUT: Key<WolfVariant> = fromKey("minecraft:chestnut")

  public val SNOWY: Key<WolfVariant> = fromKey("minecraft:snowy")

  public val STRIPED: Key<WolfVariant> = fromKey("minecraft:striped")

  public val ASHEN: Key<WolfVariant> = fromKey("minecraft:ashen")

  public val SPOTTED: Key<WolfVariant> = fromKey("minecraft:spotted")

  public val RUSTY: Key<WolfVariant> = fromKey("minecraft:rusty")

  public val WOODS: Key<WolfVariant> = fromKey("minecraft:woods")

  public val PALE: Key<WolfVariant> = fromKey("minecraft:pale")
}
