// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.types.ZombieNautilusVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Companion.fromKey
import ru.cherryngine.lib.minecraft.utils.registry.RegistryEntryHolder.Key

@Suppress("RedundantVisibilityModifier")
public object ZombieNautilusVariants {
  public val WARM: Key<ZombieNautilusVariant> = fromKey("minecraft:warm")

  public val TEMPERATE: Key<ZombieNautilusVariant> = fromKey("minecraft:temperate")
}
