// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.createKey
import ru.cherryngine.lib.minecraft.registry.types.ZombieNautilusVariant
import ru.cherryngine.lib.minecraft.utils.registry.RegistryKey

@Suppress("RedundantVisibilityModifier")
public object ZombieNautilusVariants {
  public val WARM: RegistryKey<ZombieNautilusVariant> = createKey("minecraft:warm")

  public val TEMPERATE: RegistryKey<ZombieNautilusVariant> = createKey("minecraft:temperate")
}
