// AUTOGENERATED. DO NOT EDIT.
package ru.cherryngine.lib.minecraft.registry.keys

import ru.cherryngine.lib.minecraft.registry.entries.ZombieNautilusVariant
import ru.cherryngine.lib.minecraft.registry.registries.ZombieNautilusVariantRegistry

public object ZombieNautilusVariants {
  public val WARM: ZombieNautilusVariant = ZombieNautilusVariantRegistry["minecraft:warm"]

  public val TEMPERATE: ZombieNautilusVariant = ZombieNautilusVariantRegistry["minecraft:temperate"]
}
